### PR TITLE
Initial commit of Cloud Search API

### PR DESCRIPTION
**Pull request by jgeewax**

### CODE REVIEW

**Comment by dhermes** [comment]
21 files in one commit is a mouthful! Can you start with an MVP and build up for the sake of review? The bigger the PR is, the less a chance any line actually has of being reviewed.

Also, it looks like you are using `_Monkey` on objects, but IIUC @tseaver only ever intended it to be used on modules.

**Comment by jgeewax** [comment]
@dhermes : Still don't merge. Want me to delete the PR until it's ready ? (_Monkey is all gone)

I get that it's a mouthful..... I can .... stop adding stuff now... but ... tearing it apart seems like a boatload of extra work just to put it back in... Any other ideas?

**Comment by jgeewax** [comment]
Maybe we can start with just the search-api.rst file...?

**Comment by dhermes** [comment]
It is a boatload of work, but we would never let a new contributor make a PR with a brain dump, so we should hold ourselves to the same standard. The quality of review goes down and burden on reviewers goes way up when the PR is a behemoth. At the very least it should be separated into small commits encapsulating single ideas.

Start with a skeleton of each class/method and then build out features piecemeal.

If you don't have cycles for it, I can pull apart your PR to make it easy to review.

**Comment by tseaver** [comment]
Obsoleted by #1162, #1164, #1165, #1173, #1177, #1178, #1179, #1183, #1184

**Pull request closed without merging**
