### PR TITLE
Upgrading version to 0.10.0.

### PR DESCRIPTION
**Pull request by dhermes**
Release notes will be forthcoming

### CODE REVIEW

**Comment by dhermes** [comment]
Running

```
$ git log -1 --pretty=%H
6c859686b0a4e8c07ccc183e209052036e631887
$ git log 0.9.0..HEAD \
> | grep 'Merge pull request ' \
> | awk -F ' ' '{print $4}' \
> | sort
```

yields

#1373
#1375
#1405
#1433
#1437
#1440
#1446
#1447
#1449
#1450
#1468
#1469
#1471
#1472
#1473
#1474
#1476
#1479

**Comment by jgeewax** [comment]
Woooo :+1:

**Comment by dhermes** [comment]
Admin commits: #1373, #1375, #1437, #1449, #1450, #1468 
Bigtable (unreleased): #1405, #1471, #1472, #1473, #1474, #1476

----

# Datastore

- Adding `Query.key_filter()` as a shorthand for `__key__` filters (#1433)

# Pubsub

- Bugfix: Properly handle responses without any subscriptions or topics (#1440)

# Storage

- Adding `content_type` to `Blob.generate_signed_url` (#1447)

# BigQuery

- Update docs to reflect API changes (#1469)

# Core

- Allowing pyOpenSSL imports to fail on App Engine (#1446)
- Upgrading to `oauth2client` 2.0.0 (#1479)

**Comment by cyluss** [comment]
:+1:

**Comment by tseaver** [comment]
LGTM.  I added a changelog entry for #1481, and tweaked the rest.

**Pull request merged**
