### PR TITLE
Pin 'Getting started with gcloud' section on every page.

### LINKED ISSUE #553: Pin the "getting started with gcloud" snippet at the top of every page
We do this on gcloud-node and it's *awesome* (http://googlecloudplatform.github.io/gcloud-node/#/docs/v0.12.0/datastore/transaction)

Can we make this happen on the docs for gcloud-python too ?

### PR DESCRIPTION
**Pull request by tseaver**
Make it togglable, like the node docs.

Fixes #553.

### CODE REVIEW

**Comment by tseaver** [comment]
To review, run `tox -e docs` and then open `docs/_build/html/index.html`.

**Comment by dhermes** [comment]
@silvolu Just had a [remark][1] about this. I'll leave the review to him.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/issues/553#issuecomment-70132934

**Comment by silvolu** [comment]
I think @jgeewax should review; I was just commenting on the historical reason why there is no pinning :)

**Comment by dhermes** [comment]
This is very much in limbo.

Do we need this and is #553 actually necessary?

**Comment by dhermes** [comment]
Since this has languished for 2.5 months, I'm closing out. If we decided #533 is relevant, we can revisit.

**Pull request closed without merging**
