### PR TITLE
Disable broken wheel building

### PR DESCRIPTION
**Pull request by tseaver**
See https://github.com/GoogleCloudPlatform/gcloud-python/issues/1879#issuecomment-229444782

### CODE REVIEW

**Comment by tseaver** [comment]
@daspecster, @dhermes, @jgeewax I'm proposing to merge *only* this PR to the `release-0.16.1` branch I just made off the `0.16.0` tag, and then tag *that* branch as `0.16.1`.  Because Travis will push only an `sdist`, everybody should be able to install it.  Because it is a newer version, users who have a copy of the invalid `none-any` wheel in their wheel caches will get to upgrade to a working version.

**Comment by daspecster** [comment]
@tseaver, don't we need to change the version number in setup.py as well?

**Comment by tseaver** [comment]
@daspecster I'll do that when making the `0.16.1` release.

**Comment by tseaver** [comment]
[0.16.1](https://github.com/GoogleCloudPlatform/gcloud-python/releases/tag/0.16.1) tagged w/ appropriate release notes.

**Comment by tseaver** [comment]
... and [on PyPI](https://pypi.python.org/pypi/gcloud/0.16.1).

**Pull request merged**
