### PR TITLE
Add bigtable generated files

### PR DESCRIPTION
**Pull request by dhermes**
@tseaver These are generated with

https://github.com/dhermes/gcloud-python-bigtable/blob/7c88583a4f772701228c2c94c32a847670fe6a52/Makefile

I had to modify

https://github.com/dhermes/gcloud-python-bigtable/blob/7c88583a4f772701228c2c94c32a847670fe6a52/scripts/rewrite_imports.py

so that it rewrote imports as `gcloud.bigtable` instead of `gcloud_bigtable`.

----

Should I try to port the `Makefile` over as well? The reason I hesitate is because it requires having a valid gRPC install.

### CODE REVIEW

**Comment by tseaver** [comment]
I don't think there is much to review here:  should we maybe be reviewing the generator first?

**Comment by dhermes** [comment]
Sure. That is contingent on whether we should add it to the repo. A `Makefile` is certainly not platform independent, so I hesitate a little bit. (NOTE: I want to do a similar thing with #594 but the gRPC plugin for `protoc` makes some imports that we can't use. I need to be less dumb using namespace packages though and maybe we could avoid import rewrites.)

**Comment by tseaver** [comment]
Should we be checking in the `.proto` files?

**Comment by dhermes** [comment]
Yeah good call!

**Comment by tseaver** [comment]
I think checking in the `Makefile` too is worthwhile:  even if it is Unix/Linux/Ubuntu-dependent, it "documents" how the generated files are created, allowing users to figure out how to replicate on their own systems.

**Comment by dhermes** [comment]
I just added the `.proto` files. I'll bring in the `Makefile` too and we can discuss once it's in.

Do you want me to re-arrange the commits to make it more clear what's going in?

**Comment by tseaver** [comment]
Commit order doesn't really matter to me -- I'm going to look primarily at the `Makefile` and one each of the `.proto` and `_pb2.py` files.  If you think it is cleaner to rebase down to a single commit, that would be fine.

**Comment by tseaver** [comment]
When the `Makefile` comes in, will I be able to regenerate from it (assuming `protoc` is on the path)?

**Comment by dhermes** [comment]
Not unless you also have the `grpc_python_plugin` installed. And you may need the latest and greatest version of `protoc` to support `proto3` (was `proto2` for awhile). I'm not sure about that one though.

**Comment by dhermes** [comment]
@tseaver PTAL (I added the `Makefile`)

**Comment by tseaver** [comment]
LGTM -- I wish we had directions (in `CONTRIBUTING.rst`, maybe) about the environment needed to be able to recreate the generated files.

**Comment by dhermes** [comment]
Take a look through

https://github.com/dhermes/gcloud-python-bigtable/blob/master/README.md
https://github.com/dhermes/gcloud-python-bigtable/blob/master/CONTRIBUTING.md

and let me know what you'd like to be brought over.

Unfortunately (or maybe it's fortunate?) the gRPC install story is ever-evolving so the docs will be out-of-date pretty soon.

**Pull request merged**
