### PR TITLE
Add retry for flaky 'topic.exists()' check.

### PR DESCRIPTION
**Pull request by tseaver**
Toward #2111.

### CODE REVIEW

**Comment by daspecster** [comment]
LGTM, might as well give it a try?

**Comment by tseaver** [comment]
[Curses, foiled again!](https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/155830290#L882-L910)

**Comment by daspecster** [comment]
Isn't that handled in the #2215 PR though?

**Comment by tseaver** [comment]
@daspecster #2214 is about the `test_fetch_delete_subscription_w_deleted_topic` failure:  this PR is supposed to fix the `test_list_subscriptions` testcase.

**Comment by daspecster** [comment]
Oh sorry, my browser started at the bottom line that you linked so I didn't even notice it. Silly chrome.

**Pull request merged**
