### PR TITLE
Add documentation for autogen packages maintained by googleapis team

### PR DESCRIPTION
**Pull request by bjwatson**
Updates https://github.com/GoogleCloudPlatform/gcloud-python/issues/1384

### CODE REVIEW

**Comment by bjwatson** [comment]
FYI @geigerj and @omaray

**Comment by dhermes** [comment]
1. I'm surprised you want this index in here. I expected it'd be in the docs for GAX or somewhere else.
1. What sort of process will keep this doc from going stale?

**Comment by bjwatson** [comment]
@dhermes Good questions:

1. I could move it to https://github.com/googleapis/googleapis/. That also makes sense as a place to keep this. Your preference, since y'all are the primary customer for this doc.

2. Mostly this doc will be additive, except when we sunset an API (probably years from now). As the GAX Python TL, I'll take ownership of keeping this doc up to date, regardless of where it's located.

**Comment by bjwatson** [comment]
Correction to (2): There will be updates when we rev a major version of an API, which I will have to keep in mind when updating the GAX wrapper.

**Comment by dhermes** [comment]
I'm inclined to say put it in https://github.com/googleapis/googleapis/ but I'll let others weigh in

**Comment by tseaver** [comment]
That repo SGTM:  it is where I would look for those docs if I weren't elbows-deep here every day.

**Comment by dhermes** [comment]
OK @bjwatson shall we close out?

**Comment by bjwatson** [comment]
@dhermes SGTM

**Pull request closed without merging**
