### PR TITLE
Py3k compatibility for snippet execution.

### PR DESCRIPTION
**Pull request by tseaver**
Exercising `grpcio` and related packages under Python 3.4, per https://github.com/grpc/grpc/issues/282#issuecomment-226014975

### CODE REVIEW

**Comment by tseaver** [comment]
@daspecster PTAL

**Comment by daspecster** [comment]
@tseaver  How do you run these? Or when are they run?

**Comment by tseaver** [comment]
> How do you run these? Or when are they run?

@daspecster I've been running them like system tests, in an environment with project / auth set up.  I use the following command:

```bash
$ .tox/system-tests/bin/python docs/pubsub_snippets.py
```

**Comment by daspecster** [comment]
@tseaver LGTM! Should we put this in the #1854 release?

**Comment by tseaver** [comment]
It isn't really user-visible, yet.

**Pull request merged**
