### PR TITLE
Adding cluster argument to Bigtable HappyBase connection.

### PR DESCRIPTION
**Pull request by dhermes**
~~@tseaver By adding this I go from 10 to 11 arguments (10 are part of the [original interface][1]) and I make [`pylint` angry][2].~~

----

Would you prefer I

- Use `**kwargs` for supporting the legacy signature (this breaks any argument order unless we also use `*args` and manually do the mapping, which would break existing code that uses `happybase`)
- Raise the global limit from 10 to 11
- `pylint: disable=` locally

----

@jgeewax How important is having the signature of our `gcloud.bigtable.happybase.Connection` the same as `happybase.Connection`?

[1]: https://github.com/wbolster/happybase/blob/9cbd718c10a3089f234f1eac1236b631e1f8e7cd/happybase/connection.py#L105-L108
[2]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/896044579b5dfaddb75e8c7cbf72b614b0d04c5e/scripts/pylintrc_default#L377

### CODE REVIEW

**Comment by dhermes** [comment]
@tseaver PTAL

**Comment by dhermes** [comment]
@jgeewax PTAL (pending question for you)

**Comment by dhermes** [comment]
@tseaver and @jgeewax PTAL

**Comment by dhermes** [comment]
Resolved with @jgeewax that warnings and `kwargs` would be better than perfectly good code failing.

**Comment by jonparrott** [comment]
LGTM

**Pull request merged**
