### PR TITLE
Installing twine before deploying.

### PR DESCRIPTION
**Pull request by dhermes**
See https://github.com/travis-ci/dpl/issues/299

Honestly `dpl` just needs to be fixed and I'd rather never submit this, but this is a fix if need be.

### CODE REVIEW

**Comment by dhermes** [comment]
See #1057 as well

**Comment by tseaver** [comment]
LGTM

**Comment by dhermes** [comment]
@tseaver I'm just going to leave this unmerged and hope the problem resolves itself before the next release. I'm subscribed to both travis-ci/dpl#296 and travis-ci/dpl#299 so hopefully I'll hear about a resolution soon.

**Comment by dhermes** [comment]
With the closing of travis-ci/dpl#296 and travis-ci/dpl#299 it seems this fix is no longer needed.

**Pull request closed without merging**
