### PR TITLE
Pin back oauth2client from breaking major version

### PR DESCRIPTION
**Pull request by bendemaree**
What it says on the tin; xref #1477.

### CODE REVIEW

**Comment by dhermes** [comment]
@bendemaree I plan on updating our usage to comply with `>= 2.0.0` in `HEAD`.

In order to keep the previous versions from being broken we'd need to manually re-push to PyPI (which is fine).

Though I'm not sure what our philosophy is here. @jgeewax WDYT?

**Comment by bendemaree** [comment]
@dhermes sounds good. In this case I'd personally tend towards a release and patch version bump, since installing as a first-time user right now from PyPI will leave you with a broken install and a bummer experience.

Just my 2 cents--not much else I can help with here. Thanks for taking a look!

**Comment by dhermes** [comment]
Yeah I planned on just doing a `0.9.1`

**Comment by tseaver** [comment]
@dhermes needs to be `0.10`, since we bump a dependency pin to a backward-incompatible version.

**Comment by tseaver** [comment]
@bendemaree thanks for the patch!  @dhermes handles the pinning to newer `oauthclient2` (and fixing #1477) in #1479, so I'm closing this one.

**Comment by bendemaree** [comment]
@tseaver :+1:

**Comment by dhermes** [comment]
Thanks for being heads up Ben!

**Pull request closed without merging**
