### PR TITLE
readme: point service links to readme intro documentation

### PR DESCRIPTION
**Pull request by stephenplusplus**
Hey, guys!

RE: https://github.com/GoogleCloudPlatform/gcloud-node/issues/637

@jgeewax thinks it makes more sense to point the Service links (Google Cloud Datastore and Google Cloud Storage) to their respective sections in the readme.

### CODE REVIEW

**Comment by dhermes** [comment]
I don't really mind either way, but where do users get linked to the web service docs? @jgeewax

**Comment by jgeewax** [comment]
We can add a link to those... but keep in mind that the links we currently have aren't to the docs... they're to the crappy marketing-focused landing page...

If someone makes it all the way to our README, it's super unlikely they want to go to that marketing page. Maybe add in parens "(Google service documentation)" -> https://cloud.google.com/storage/docs/json_api/v1/ ?

**Comment by dhermes** [comment]
Yes I like that. @stephenplusplus you want to change this PR or shall I do that?

**Comment by stephenplusplus** [comment]
I can add it in. Were you thinking (Google service documentation) would go in the header, or as one of the links in the service paragraph?

I'm partial to keeping it with the rest of the links, leaving the header service links as a table of contents to skip around the readme.

--

## Google Cloud Datastore

Google [Cloud Datastore](https://cloud.google.com/datastore/docs) ([service API docs](https://cloud.google.com/storage/docs/json_api/v1/)) is a fully managed, schemaless database for storing non-relational data. Cloud Datastore automatically scales with your users and supports ACID transactions, high availability of reads and writes, strong consistency for reads and ancestor queries, and eventual consistency for all other queries.

See the [Google Cloud Datastore docs](https://cloud.google.com/datastore/docs/activate) for more details on how to activate Cloud Datastore for your project.

See the gcloud-python API [datastore documentation](https://googlecloudplatform.github.io/gcloud-python/latest/datastore-api.html) to learn how to interact with the Cloud Datastore using this Client Library.

**Comment by jgeewax** [comment]
I'm all for that, but could we swap the order of the last two "See.."
paragraphs? And change "Google Cloud Datastore docs" to "Official Google
Cloud Datastore documentation" ?

**Comment by stephenplusplus** [comment]
TAL: https://github.com/stephenplusplus/gcloud-python

**Comment by dhermes** [comment]
LGTM

**Pull request merged**
