### PR TITLE
Upgrading version to 0.13.0.

### PR DESCRIPTION
**Pull request by dhermes**
```
$ git log -1 --pretty=%H
f227fdc96287d92ba7232f005a447b6af06a7525
$ git log 0.12.1..HEAD \
> | grep 'Merge pull request ' \
> | awk -F ' ' '{print $4}' \
> | sort
```

yields

#1700
#1733
#1734
#1736
#1737
#1738

#1691 didn't show up (because I merged it with GitHub's squash commit feature). If we use this feature I'll need to refine my release process to capture all PRs since the last release (maybe something already exists from GitHub that I don't know about).

### CODE REVIEW

**Comment by dhermes** [comment]
Left out of release notes

- #1700 / #1736 (re-plumbing the API calls for Pub/Sub)
- #1733 (docs CSS fix)
- #1734 / #1737 / #1738 (testing changes)

Release notes

----

## Monitoring API

- Added basic support for the Google Stackdriver [Monitoring API][1] (#1691)

[1]: https://cloud.google.com/monitoring/api/

----

@rimey PTAL at the release notes.

**Comment by tseaver** [comment]
LGTM.  I don't think we need to mention any of the currently-excluded PRs:  none of them are user-visible.

**Comment by dhermes** [comment]
@rimey I can always edit the release notes, LMK if you'd like different / more verbose content.

**Comment by dhermes** [comment]
Release has been uploaded: https://pypi.python.org/pypi/gcloud/0.13.0

**Comment by rimey** [comment]
Sorry, I was off-line for a bit. Shall I just hit the "Update release" button?

## Monitoring API

- Adds the Google Stackdriver [Monitoring API][1], with support for querying of time series, metric descriptors, and monitored resource descriptors. (#1691)

[1]: https://cloud.google.com/monitoring/api/

**Comment by dhermes** [comment]
I just updated it for you. Wasn't sure what your edit privileges would be for the release.

**Pull request merged**
