### PR TITLE
Backport PR #2065 to address issue #2066, then bump version to 0.18.1 for urgent release.

### PR DESCRIPTION
**Pull request by tseaver**
Issue #2065 brownbags our 0.18.0 release.

### CODE REVIEW

**Comment by dhermes** [comment]
LGTM. How was the `releases-0.18.x` branch created?

**Comment by tseaver** [comment]
> How was the releases-0.18.x branch created?

I created it locally via:

```bash
$ git checkout -b releases-0.18.x 0.18.1
```

 and pushed it directly to this repo.

**Comment by dhermes** [comment]
I assume you meant `0.18.0` the tag?

**Comment by tseaver** [comment]
Yup.

**Pull request merged**
