### PR TITLE
Dropping _has_field.

### PR DESCRIPTION
**Pull request by dhermes**
Can use `value.HasField()` for datastore `v1beta2` and for datastore `v1beta3` we can use `Value.value_type` (which is a oneof) along with `WhichOneof`.

### CODE REVIEW

**Comment by jonparrott** [comment]
Feel free to assign PRs to me, it helps me remember to review them.

**Comment by dhermes** [comment]
Will do. That makes way more sense than cc-ing you!

**Comment by jonparrott** [comment]
This LGTM, though my familiarity with grpc isn't as high as I'd like it to be to have confidence in my opinion here.

**Comment by dhermes** [comment]
Nothing gRPC happening here, just `proto`

**Pull request merged**
