### PR TITLE
Make handwritten JSON documents more uniform

### PR DESCRIPTION
**Pull request by dhermes**
Also

- removing no longer needed `toc-all.json`
- removing a section of `toc.json` in `exceptions` that didn't belong

Used the following script to update the content:

```python
import json

files = [
    'docs/json/json/master/index.json',
    'docs/json/json/master/toc.json',
    'docs/json/manifest.json',
]

for filename in files:
    with open(filename, 'rb') as file_obj:
        content = json.load(file_obj)
    with open(filename, 'wb') as file_obj:
        json.dump(content, file_obj, indent=2, sort_keys=True,
                  separators=(',', ': '))  # Added separators later
        file_obj.write('\n')  # Added later
```

### CODE REVIEW

**Comment by daspecster** [comment]
LGTM

**Comment by dhermes** [comment]
@daspecster This will also break #2167, so I'll hold off on merging until you get it in :wink: 

Ping me though so I don't forget?

**Comment by daspecster** [comment]
Ok yeah, just waiting on travis again... ⏳

**Comment by dhermes** [comment]
Just rebased after #2167. Note that I added a newline to the end of each JSON file and also used custom `json` separators since by default a trailing space is used after the comma separator.

**Comment by daspecster** [comment]
LGTM.

**Pull request merged**
