### PR TITLE
fix empty set

### PR DESCRIPTION
**Pull request by lucemia**
for issue https://github.com/GoogleCloudPlatform/gcloud-python/issues/403

for test case. I am curious about whether to create a new test case `test_save_entity_w_transaction_list_value` and included https://github.com/GoogleCloudPlatform/gcloud-python/pull/399.

### CODE REVIEW

**Comment by lucemia** [comment]
@dhermes  
It seems to me that `_set_protobuf_list` will face the same issue as `_set_protobuf_value`.
It cannot delete `Property` itself due to the protobuf api limit..., can it ?

**Comment by lucemia** [comment]
@dhermes 
For `PropertyFilter` usage, does that make sense to pass an empty list to `Value`?
If not, I think I can focus on solve the `Property` usage case first.

**Comment by dhermes** [comment]
ISTM both problems can be solved in the same way but maybe I'm missing something.

You can show the fix for `Property` and we can discuss?

**Comment by lucemia** [comment]
To solve the `Property`, I come up with two ways. (am I missing something?) 

## the original code in connection.py
```
for name, value in properties.items():
            prop = insert.property.add()
            # Set the name of the property.
            prop.name = name

            # Set the appropriate value.
            helpers._set_protobuf_value(prop.value, value)

            if name in exclude_from_indexes:
                if not isinstance(value, list):
                    prop.value.indexed = False

                for sub_value in prop.value.list_value:
                    sub_value.indexed = False
```

## 1. check the value type in first place
```
for name, value in properties.items():
    if isinstance(value, list) and len(value) == 0:
          continue
    prop = insert.property.add()
    # ....
```

## 2. define a new helper function
```
     for name, value in properties.items():
            helpers._set_protobuf_property(insert.property, name, value, 
                                           name in exclude_from_indexes)
```

**Comment by dhermes** [comment]
2. seems a much more robust solution

**Comment by lucemia** [comment]
ok i will create a PR with sol2. Thanks!

**Comment by dhermes** [comment]
Closing in favor of #512

**Pull request closed without merging**
