### PR TITLE
Add pandoc to travis-ci.

### PR DESCRIPTION
**Pull request by daspecster**
I want to make sure this installs on travis without issue.

### CODE REVIEW

**Comment by dhermes** [comment]
@daspecster I also didn't get a notification about this PR. I wonder what's up with GitHub?

**Comment by dhermes** [comment]
Also, we intentionally use `sudo: false` to get the new infra. on Travis.

This PR doesn't explain why pandoc is needed.

**Comment by daspecster** [comment]
Hmm, I didn't assign anyone to it. I just wanted to play with some stuff. That might be why you didn't get notified?

So I'm thinking of using pandoc to parse some of the RST `*-api.rst` and `*-usage.rst` files to then be inserted into the JSON tree somewhere.

**Comment by jonparrott** [comment]
why not just use the restructuredtext library?

**Comment by dhermes** [comment]
Big time :-1: on using `pandoc`. Agree with @jonparrott

**Comment by daspecster** [comment]
@jonparrott, `docutils`? I parsed it with that using the `rst2html.py` script, but when there's an error (like an unknown directive found), it injects the error into the html.

Pandoc seems to clean those up and handle the some of the navigation issues fairly well.

Example:
screen shot 2016-09-02 at 2 15 51 pm

**Comment by dhermes** [comment]
The `pan` in `pandoc` is the problem. We don't need a jackhammer, just like a tiny magnifying glass or something.

**Comment by jonparrott** [comment]
@daspecster the rst parser in docutils is really quite flexible, but perhaps you'd be better off starting with a sphinx extension to do what you need?

**Comment by daspecster** [comment]
@dhermes that is true. I'm sure there's more stuff out there.

@jonparrott, I spent a decent amount of time with sphinx extensions and the way that the node tree is built, I couldn't find a way to extract the correct parts of the docstrings. 

It would add the nav and references since those are sphinx directives anyway. Those links don't work in the JSON site.

It seems redundant to parse them with sphinx and then parse them again to clean it up.
You can kind of see what's happening under the hood by using the json or xml builders.

**Pull request closed without merging**
