### PR TITLE
Update to version 0.16.0

### LINKED ISSUE #1869: GAX API hangs during (second) 'publish'
/cc @bjwatson 

```python
======================================================================
ERROR: test_message_pull_mode_e2e (pubsub.TestPubsub)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/system_tests/pubsub.py", line 157, in test_message_pull_mode_e2e
    topic.publish(MESSAGE_1, extra=EXTRA_1)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/gcloud/pubsub/topic.py", line 246, in publish
    message_ids = api.topic_publish(self.full_name, [message_data])
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/gcloud/pubsub/_gax.py", line 171, in topic_publish
    event.wait()
AttributeError: 'exceptions.AttributeError' object has no attribute 'message_ids'
```

### PR DESCRIPTION
**Pull request by daspecster**
There's a few things we need to do before we cut this.

- [X] Merge #1868
- [X] Merge #1844
- [X] Merge #1816
- [X] Merge #1815
- [X] Merge #1813
- [X] Merge #1870
- [X] Fix #1869 done by disabling GAX for pubsub

### CODE REVIEW

**Comment by daspecster** [comment]
@tseaver, #1844 got merged and I'm inclined to leave #1813 out unless we can merge it today.  But I'm not sure about #1815?

**Comment by tseaver** [comment]
I just merged #1815.  I think we should merge #1813 today, and then make a release.

**Comment by tseaver** [comment]
```
$ git log -1 --pretty=%H
835d2dc97e03941bc2004b6e819220a21f613c99
$ git log 0.15.0..HEAD | grep 'Merge pull request ' |  awk -F ' ' '{print $4}' | sort
```

yields:

#1815
#1816
#1843
#1848
#1851
#1855

**Comment by tseaver** [comment]
## 0.16.0 Release Notes

### Core

- Install `grpcio` and related helpers by default on Python 2.7. (#1815)
- Recommend new `gcloud` ADC command for authentication. (#1851)

### Pubsub

- Select API helpers based on presence of gRPC libraries.  Allow disabling them via an environment variable. (#1816, #1855)

### Bigtable

- Wrap gRPC "already exists" error with a HappyBase exception. (#1843)

### Logging

- Optimize `Logger.list_entries` query, improve docs. (#1848)

**Comment by daspecster** [comment]
@tseaver also I made a release draft for 0.16.0 just fyi.

**Comment by daspecster** [comment]
@tseaver, when I rerun
```bash
$ git log 0.15.0..HEAD | grep 'Merge pull request ' |  awk -F ' ' '{print $4}' | sort
```
I don't see the new PRs in there...#1813, #1860, #1844...possibly others?

Any ideas?

**Comment by tseaver** [comment]
Have you merged your local `master` with `upstream/master`?

**Comment by daspecster** [comment]
I rebased it.

Do they show up for you?

**Comment by tseaver** [comment]
Also, "merge w/ squash commits" doesn't create a merge commit findable by that command line.  I manually ran `git log 0.15.0..HEAD` and looked at the commits to uncover #1844, for instance.

**Comment by daspecster** [comment]
Ah that's it! I did use the github squash merge and I didn't add "Merge pull request" to the commit message.

**Comment by daspecster** [comment]
I left out #1860 since you mentioned it's not user facing really.

@tseaver I think once we get the GRPCIO 0.14.0 issues on appveyor and the docs generation working we can cut this release right?

**Comment by tseaver** [comment]
> I think once we get the GRPCIO 0.14.0 issues on appveyor and the docs generation working we can cut this release right?

SGTM

**Comment by tseaver** [comment]
Is `grpcio` 0.14.0 expected to Just Work (TM) on Windows?  Given my last comments on #1863, I'd say we could go ahead with our release even though Appveyor is broken.

**Comment by daspecster** [comment]
@tseaver, is there any fallout we could be heading towards by releasing?

It looks like my credentials helper function errors if it doesn't have permissions. I can just catch that in an except so it fails more peacefully.

https://ci.appveyor.com/project/daspecster/gcloud-python/build/1.0.1.master/job/433qv2dtg3uq4a4t#L513

**Comment by tseaver** [comment]
I'd say we can go ahead and release, unless @jgeewax thinks that the `grpico`-on-Windows bit from #1815 is a blocker.

**Comment by daspecster** [comment]
@tseaver we could merge in #1868 to fix some of the appveyor issues but not all obviously.

**Comment by tseaver** [comment]
Sounds good.  The remaining failures will then be blocked on a fix for https://github.com/grpc/grpc/issues/6939.

**Comment by daspecster** [comment]
Ok, sounds like a plan. Is there anything we can do to help resolve that?

**Comment by tseaver** [comment]
@daspecster I just updated the checklist to pull in #1870 and the need to fix #1869.

**Comment by tseaver** [comment]
@daspecster #1874 reverts pubsub defaults to the safe JSON-over-HTTP.  AFAIK, it would be the last change needed before merging here.

**Comment by daspecster** [comment]
We should probably note this in the release notes.

**Comment by tseaver** [comment]
@daspecster I just updated the release note above for pubsub.

**Comment by daspecster** [comment]
Good to go then right?

**Comment by tseaver** [comment]
Yup!

**Pull request merged**
