### PR TITLE
Implementing HappyBase methods that aren't functional in Bigtable.

### PR DESCRIPTION
**Pull request by dhermes**
Providing the methods for interface compatibility.

### CODE REVIEW

**Comment by tseaver** [comment]
Given the choice to have these stubs, LGTM.

**Comment by dhermes** [comment]
I'm not sure I understand. If the goal is swapping `from happybase import foo` for `from gcloud.bigtable.happybase import foo`, is there a better solution? (Honestly it's like pick your error, `NotImplementedError` or `AttributeError` or ...)

**Comment by tseaver** [comment]
I just meant that being able to import `foo` but not use it doesn't seem like much of a win:  the user is going to need to change code (beyond the imports) either way.

**Comment by dhermes** [comment]
Yeah I agree. @jgeewax How do you think we should handle the methods in this PR?

**Comment by jgeewax** [comment]
(Commenting from mobile, so forgive if this is answered elsewhere.)

How much other code needs to change ? Any short example before and after snippets ?

**Comment by jgeewax** [comment]
For context, if the method is just missing, people may go off the assumption that this just want implemented yet. Having this exception raised makes it clear that it wasn't as didn't do the work, it's that the concept doesn't make sense for Bigtable.

**Comment by dhermes** [comment]
For this particular PR it is essentially the choice between class `A` (@tseaver suggestion) or class `B` (current implementation of this PR):

```python
>>> class A(object):
...     pass
... 
>>> a = A()
>>> a.foo(1, 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'A' object has no attribute 'foo'
>>> class B(object):
...     def foo(self, x, y):
...         raise NotImplementedError('We cannot do', x, 'or', y)
... 
>>> b = B()
>>> b.foo(1, 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in foo
NotImplementedError: ('We cannot do', 1, 'or', 2)
```

**Comment by dhermes** [comment]
OK going to leave it as-is.

**Pull request merged**
