### PR TITLE
Remove old docsite app files so it doesn't overwrite on deploy

### PR DESCRIPTION
**Pull request by daspecster**
We're accepting docsite updates from gcloud-common now.
Anytime there is an update for the site committed to gcloud-common, their `deploy-docs.sh` file is run and updates the [listed repos](https://github.com/GoogleCloudPlatform/gcloud-common/blob/9464a305d402f71436bfaca1d790630b3228ef15/deploy-docs.sh#L80).

These files were being copied and overwriting the latest app files that were getting pushed by gcloud-common.

### CODE REVIEW

**Comment by daspecster** [comment]
@callmehiphop can we force run deploy-docs.sh after this is merged to get the latest again from gcloud-common/site?

**Comment by callmehiphop** [comment]
Not sure, would restarting an older Travis job do the trick?

**Comment by daspecster** [comment]
That's what I was going to do, but I thought I'd ask just to make sure.

**Comment by dhermes** [comment]
1. LGTM
1. Why not just run the script locally?
1. Can any of the other files go? e.g. the JSON files

**Comment by daspecster** [comment]
1. 🎉 
2. Good idea!
3. I'm updating to remove extra html files. I think the rest is required?

@callmehiphop can you confirm that all we need is `home.html` in the json [dir](https://github.com/GoogleCloudPlatform/google-cloud-node/tree/34bddee2c82c93711de7f9235ad8fe3795a083bb/json)?

**Comment by callmehiphop** [comment]
@daspecster Yep!

**Comment by daspecster** [comment]
Looks like it all worked! The top nav is working and the side nav collapsed appropriately.

**Pull request merged**
