### PR TITLE
Improve autodocs for top-level package names.

### LINKED ISSUE #845: Sphinx needs to document methods from _implicit_environ
See https://github.com/GoogleCloudPlatform/gcloud-python/issues/841#issuecomment-94521450 for context.

### PR DESCRIPTION
**Pull request by tseaver**
- Drop the `__init__` from them.
- Include the ones imported from `_implicit_environ'`

Fixes #845.

### CODE REVIEW

**Comment by dhermes** [comment]
I've checked out this branch and built the docs. All looks good, can you fix the docstring for `datastore.set_defaults` so the bullets render correctly? Use `*` instead of `-` for Sphinx.

**Comment by dhermes** [comment]
Also a concern, this is very manual. How will we make sure new methods in `__init__` get added to the docs?

**Comment by tseaver** [comment]
fbba1c4 fixes the bullet rendering (not `*`, but a leading blank line, was required).

WRT manual config: We can't have best of all worlds for members imported into the base package:

- Adding `:imported-members:` would pick up *all* the imports.
- Adding just the ones we want to `__all__` would make using the others look unsupported.

The real fix would be to move those implementations into the base package, and have them just tweak the defaults object in `_implicit_environ`.

**Comment by dhermes** [comment]
I don't think the circular import gymnastics is worth it for this somewhat minor nit. Proceed: LGTM.

**Pull request merged**
