### PR TITLE
Make storage upload have no chunk size by default.

### LINKED ISSUE #546: resumable uploads should try to send the file in one chunk by default
Sending data in one chunk is the recommended approach, documented in a not very clear way [here](https://cloud.google.com/storage/docs/json_api/v1/how-tos/upload#resumable) in the “Uploading the file in chunks” section.

We should allow the user to override the chunk size, making sure that the library ends up using a multiple of 256 KB, as expected from the API (except for the final chunk that completes the upload where the size can vary according to the total size of the file). [gsutil code][1] dealing with this.

[1]: https://github.com/GoogleCloudPlatform/gsutil/blob/ccca18e64f3f7d87c989675f8673af7bdecae0d1/gslib/util.py#L464

### PR DESCRIPTION
**Pull request by dhermes**
Fixes #546.

@tseaver @thobrla 

I took a stab at the issue but am still unsure of a few things:

- Does `apitools` actually attempt a full upload when `chunksize=None`? (/cc @craigcitro)
- Would we be better with a boolean like `use_chunked=False` and then just use the chunk size on the `Blob`?
- Is having a separate keyword unintuitive?

Also @thobrla I'm curious, RE: "We should allow the user to override the chunk size". Do we need a default chunk size for downloads? In the case that someone creates an object with a custom chunk size, should we use it in this method or still try the "all in one go" approach?

### CODE REVIEW

**Comment by thobrla** [comment]
It hasn't been merged into the mainline yet, but I implemented a chunksize=None approach for uploads in gsutil's fork of apitools: https://github.com/GoogleCloudPlatform/gsutil/blob/master/gslib/third_party/storage_apitools/transfer.py#L773

However, because you're using httplib2, there are a number of other issues that you'll need to solve to get this to work.  https://github.com/GoogleCloudPlatform/gsutil/blob/master/gslib/gcs_json_media.py has some examples.

**Comment by thobrla** [comment]
As for chunk size in general, the ideal thing is not to use chunks for uploads or downloads at all unless you have a specific reason to do so (for example, buffering a streaming transfer).

**Comment by tseaver** [comment]
Rather than passing in an `upload_chunk_size`, wouldn't it be more sensible to have `Blob.CHUNK_SIZE` be None as the appropriate default, but settable for cases where the application wanted to do [chunking](https://cloud.google.com/storage/docs/json_api/v1/how-tos/upload#chunking) (maybe via a subclass?).

**Comment by dhermes** [comment]
@tseaver That's why I asked "Do we need a default chunk size for downloads?".

From @thobrla answer above it seems that a default is not needed.

I'm still unclear if passing `chunksize=None` to our vendored in code is sufficient to fix #546.

**Comment by tseaver** [comment]
Are we leaving the blob's own CHUNK_SIZE around, but just using it for downloads?  Should we be making it an explicit parameter there, too?

**Comment by dhermes** [comment]
I plan on implementing the default `chunk_size=None` and then just using `blob.chunk_size` the way the class constant was used.

I just wanted to make sure passing `chunksize=None` to our vendored in code is sufficient before moving too much further.

**Comment by craigcitro** [comment]
so i've *finally* got myself an official repo for [apitools](https://github.com/google/apitools); i'm planning on finally doing a round-robin merge to get all the copies back in sync. in particular:

* if you're waiting on a fix that's only in the gsutil branch, let me know, and
* we can also hopefully get you out of the business of having to keep your own copy of apitools code.

**Comment by dhermes** [comment]
@craigcitro w00t! Thanks for the news.

The main question is

> Does `apitools` actually attempt a full upload when `chunksize=None`?

which @thobrla indicates is only in upstream (`gsutil`).

**Comment by dhermes** [comment]
Ping @craigcitro 

> Does `apitools` actually attempt a full upload when `chunksize=None`?

**Comment by craigcitro** [comment]
sorry, i missed this question earlier in the thread. i believe the code you're looking for is still upstream in gsutil, but i'm working on getting the various versions of apitools unified.

**Comment by dhermes** [comment]
@craigcitro Do you need help on the unification?

**Comment by dhermes** [comment]
UPDATE: Chatting with @craigcitro today (March 2, 2015) it seems the `gsutil` upstream changes have been merged into https://github.com/google/apitools

@tseaver Do you want to vendor in the latest updates from `apitools` and then I'll rebase? (I could vendor in too, but presume you could do it faster since you did it the first 2 times.)

**Comment by tseaver** [comment]
Yeah, I'll vendor it in.

**Comment by tseaver** [comment]
@craigcitro  [I've done the re-vendoring](https://github.com/tseaver/gcloud-python/tree/606-revendor-google_apitools-at-3c522a4), but now lack context to get the last set of tests passing:

```python
======================================================================
ERROR: test_upload_from_file_resumable (gcloud.storage.test_blob.Test_Blob)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/gcloud/storage/test_blob.py", line 418, in test_upload_from_file_resumable
    blob.upload_from_file(fh, rewind=True)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/gcloud/storage/blob.py", line 354, in upload_from_file
    finish_callback=lambda *args: None)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/_gcloud_vendor/apitools/base/py/transfer.py", line 804, in StreamInChunks
    additional_headers=additional_headers)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/_gcloud_vendor/apitools/base/py/transfer.py", line 764, in __StreamMedia
    '%d' % self.progress)
CommunicationError: Failed to transfer all bytes in chunk, upload paused at byte 4

======================================================================
FAIL: test_download_as_string (gcloud.storage.test_blob.Test_Blob)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/gcloud/storage/test_blob.py", line 328, in test_download_as_string
    self.assertEqual(fetched, b'abcdef')
AssertionError: 'abc' != 'abcdef'
- abc
+ abcdef


======================================================================
FAIL: test_download_to_file (gcloud.storage.test_blob.Test_Blob)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/gcloud/storage/test_blob.py", line 272, in test_download_to_file
    self.assertEqual(fh.getvalue(), b'abcdef')
AssertionError: 'abc' != 'abcdef'
- abc
+ abcdef


======================================================================
FAIL: test_download_to_filename (gcloud.storage.test_blob.Test_Blob)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/gcloud/storage/test_blob.py", line 307, in test_download_to_filename
    self.assertEqual(wrote, b'abcdef')
AssertionError: 'abc' != 'abcdef'
- abc
+ abcdef


----------------------------------------------------------------------
```

It looks as though code which deals with explicitly-chunked stuff from the server side is now broken.

**Comment by craigcitro** [comment]
is the easiest way for me to play with it just to clone your branch?

**Comment by tseaver** [comment]
Likely so:  I don't want to make it a PR here until things pass.  Just run `tox -e py27` to see it fail.

**Comment by dhermes** [comment]
@tseaver @craigcitro I'm happy to take up the vendor-ing in process of `HEAD` in `apitools`. What is required? @tseaver What stopped you before?

**Comment by craigcitro** [comment]
i think he was hitting test failures on upload/download; i'm intending to try it, but i've been believing that for 3+ weeks. :wink:

**Comment by dhermes** [comment]
I can babysit you if you like.

**Comment by craigcitro** [comment]
my issue is that it hasn't hit the top of my todo list -- currently heads-down on something else completely.

gsutil is currently using the version of apitools at master, so i'm reasonably confident in that code. i just need to drop the new version in and see why it's failing for veneer.

**Comment by dhermes** [comment]
Cool

**Comment by tseaver** [comment]
#755 will lead to de-vendoring `apitools`, which will then require us to get our tests compatible with the new semantics (causing the failures above).

Once that lands, we can re-visit this one.

**Comment by dhermes** [comment]
I agree. After hacking on #754 and a late night chat with Craig, it seems that is the best way forward.

**Comment by tseaver** [comment]
@dhermes seems like merge of #811 requires revisiting / rebasing this PR?

**Comment by dhermes** [comment]
Yes this PR is the one that made us realize #811 was "necessary" (more like was an option).

**Comment by dhermes** [comment]
Closing this PR and going to take the new approach of just making `CHUNK_SIZE` optional.

**Pull request closed without merging**
