### PR TITLE
Make table snippets testable

### PR DESCRIPTION
**Pull request by tseaver**
~~Uses #1832 as a base.~~

Toward a real fix for #1786 and related issues (usage docs out-of-sync with API surface).

### CODE REVIEW

**Comment by tseaver** [comment]
Rebased after merging #1832 to `master`.

**Comment by daspecster** [comment]
@tseaver I guess it needs to be rebased again :(

**Comment by tseaver** [comment]
@daspecster Funny, that -- this PR already fixed that example (by making it testable).

**Comment by daspecster** [comment]
LGTM

We should close https://github.com/GoogleCloudPlatform/gcloud-python/issues/1980 when this merges.

**Pull request merged**
