### PR TITLE
Removing old docs template.

### PR DESCRIPTION
**Pull request by dhermes**
Replacing it with the RTD template so we can still verify that the docs are valid Sphinx.

@daspecster LMK if any of the deleted files are still needed. AFAIK the old build is completely separate from the stuff you introduced, so these files were essentially "dead".

### CODE REVIEW

**Comment by tseaver** [comment]
LGTM pending Travis.

**Comment by dhermes** [comment]
Just deleted four more and folded into the original PR

```
        deleted:    scripts/get_version.py
        deleted:    scripts/update_docs.sh
        deleted:    scripts/update_versions.py
        deleted:    scripts/versions.html.template
```

**Comment by tseaver** [comment]
"You may fire when you are ready, Gridley"

**Comment by daspecster** [comment]
@dhermes, this looks ok to me. I thought other things used `get_version.py` but in searching, I only found `update_docs.sh` using it. LGTM.

**Pull request merged**
