### PR TITLE
Implement basic connection and client for Natural Language API

### PR DESCRIPTION
**Pull request by dhermes**
~~**NOTE**: Has #2062 as base.~~

### CODE REVIEW

**Comment by dhermes** [comment]
@daspecster Can you help me with the JSON docs failure? I know I need to update some hard-coded document somewhere, but figured we should discuss first.

**Comment by tseaver** [comment]
@dhermes Once #2062 merges:

- 033e29c9e990a7898b2e4bb93e55b15e4a8a9497 SGTM.
- 770b66bf93d76b6e22e4f6a2aa635a2e744a50d1 SGTM.

**Comment by tseaver** [comment]
@dhermes To fix the json-docs error, add language to the mapping in scripts/generate_json_docs.py:main.

**Comment by dhermes** [comment]
@tseaver Thanks. Got the insight from #2167 for that fix.

LGTY to merge once Travis goes green?

**Comment by tseaver** [comment]
> LGTY to merge once Travis goes green?

Yup.

**Pull request merged**
