### PR TITLE
Moving gcloud.bigtable.happybase into third_party/

### PR DESCRIPTION
**Pull request by jonparrott**
Towards #1762

This technically works, but some things to note:

* `python setup.py develop` and by extension `pip install -e` do not respect the `package_dir` argument to `setup`, as such, `gcloud.bigtable.happybase` will not be available if it's installed that way.
* Not sure how the tests/docs will react to this, @dhermes, let me know your thoughts.

Don't merge until we get confirmation from OSPO that this is the correct thing to do.

### CODE REVIEW

**Comment by jonparrott** [comment]
The only alternative I can think of is symlinking, and I'm not sure how I feel about that.

**Comment by jonparrott** [comment]
Another alternative is just making this a separate, optional package `gcloud-happybase`, which might be cleaner.

**Comment by dhermes** [comment]
Thanks for taking this on. Both test failures seem to indicate that the imports fail. I'm also curious about the contents of the `zip` created for the distribution.

**Comment by jonparrott** [comment]
> Both test failures seem to indicate that the imports fail.

Yeah this is weird. I `pip install`ed this locally and I can import, but as I meanted `setup.py develop` doesn't work so it may be how tox handles installing the package.

I'm starting to think that moving this into a separate library is the best way to go.

**Comment by dhermes** [comment]
I'm fine with `gcloud-happybase`. @jgeewax WDYT?

**Comment by tseaver** [comment]
FWIW, the code this PR moves into `third_party/happybase` is not really "third-party" code (i.e., as if we had vendored in `happybase`):  it is (or is claimed to be) a derived work from third-party code, and hence we need to mention that code's license.

I'm not sure that moving it does anything to help the legalities, compared to just having the header comments mention the separate license (which could just be tacked onto the current `LICENSE` file with a note).

**Comment by dhermes** [comment]
@jonparrott Why the close?

**Comment by jonparrott** [comment]
Because this approach won't work.

**Comment by dhermes** [comment]
OK

**Pull request closed without merging**
