### PR TITLE
Accomodate JSON services which do not return JSON payloads for errors.

### PR DESCRIPTION
**Pull request by tseaver**
I'm lookin' at you, pubsub.

### CODE REVIEW

**Comment by dhermes** [comment]
WAT? @tmatsuo Can we file a formal bug about not using JSON errors from a discovery-based API?

**Comment by tmatsuo** [comment]
This is presumably because Pub/Sub is on the newer infrastructure.

I assume other APIs return JSON errors. Is that behavior defined somewhere? or are you just expecting the same behavior as other APIs?

**Comment by tseaver** [comment]
@tmatsuo storage returns JSON: https://cloud.google.com/storage/docs/json_api/v1/status-codes#errorformat

**Comment by dhermes** [comment]
@tseaver this LGTM but can you capture the raw `content` in an `api_request` and post it, just so I can see?

**Comment by dhermes** [comment]
@tmatsuo JSON half the time is crazy, no matter the infrastructure. Please send my feedback into the black hole of feedback.

**Comment by tseaver** [comment]
Hmm, I was working with a bad `API_BASE_URL` earlier, which means the `No Content` was not generated by the pubsub API.  It actually returns:

```
{
  "error": {
    "code": 404,
    "message": "Resource not found (resource=a-new-topic).",
    "status": "NOT_FOUND"
  }
}
```

**Comment by dhermes** [comment]
Yay!

**Comment by dhermes** [comment]
@tmatsuo My feedback turns out to be irrelevant! w00t!

**Comment by tmatsuo** [comment]
Good to know!

**Pull request closed without merging**
