### PR TITLE
Removing merge.sh.

### PR DESCRIPTION
**Pull request by dhermes**
No longer needed since `update_wheels_project.sh` is gone.

Towards #1123

### CODE REVIEW

**Comment by dhermes** [comment]
@tseaver At what point do we feel comfortable deleting https://github.com/GoogleCloudPlatform/gcloud-python-wheels

**Comment by tseaver** [comment]
LGTM

**Comment by dhermes** [comment]
Thanks for LGTM. What about my question about deleting the wheels repo?

**Comment by tseaver** [comment]
I don't see any reason to keep it:  there is no way to go "back in time" for failed Travis builds, or any other such debugging purpose, and I don't think we care about any outside users.

**Comment by dhermes** [comment]
OK. I'm going to set a reminder to do it next Monday (we can discuss at stand-up). The repo will self-destruct in 4 days.

**Pull request merged**
