### PR TITLE
Add py33 to tox.

### LINKED ISSUE #152: Add support for py33 and py34 in tox
See [`tox.ini`][1] and #146 for some context.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/1f2aaf3606802f4f02eeb30e22e1082ef7f4594e/tox.ini#L4

### PR DESCRIPTION
**Pull request by tseaver**
Fixes #152.

### CODE REVIEW

**Comment by dhermes** [comment]
No py33 rule exists.

**Comment by dhermes** [comment]
Also it looks like PEP8 1.6.0 (released February 6) decided `E402 module level import not at top of file` is important

**Comment by tseaver** [comment]
`tox33` is covered by the generic `[testenv]` section.

https://github.com/GoogleCloudPlatform/gcloud-python/pull/601 addresses the `pep8 1.6.1` failures.

**Comment by tseaver** [comment]
Rebased after merging #601.

**Comment by dhermes** [comment]
Ahh, I didn't know that. Cool! This means we could drop `[testenv:py26]` right?

LGTM pending Travis

**Comment by tseaver** [comment]
I think the `[testenv:py26]` bits might be a fossil from some point in time where we needed to pin a dependency to a 2.6-compatible version (#284 maybe?).  At any rate, it is now identical to `[testenv]`, and so can go:  (see a69c879).

**Pull request merged**
