### PR TITLE
Add intersphinx for docs linking.

### PR DESCRIPTION
**Pull request by dhermes**
~~**NOTE**: Has #1035 as base.~~

### CODE REVIEW

**Comment by dhermes** [comment]
@tseaver Rebased

**Comment by tseaver** [comment]
I still don't see a point to the `pythonlocal` mapping:  no Python programmer is going to need to look *any* of those values up.

**Comment by dhermes** [comment]
It's nice to add the links. Somehow it feels inconsistent to link to some objects and not to others.

I'm not sure who it hurts.

**Comment by dhermes** [comment]
@tseaver It turns out I just wasn't using the right refs (e.g. using `:class:` when I needed to be used `:data:`). There is no need for the `pythonlocal` rule. I rebased and got rid of it and also added an intersphinx rule for `httplib2` (I found it yesterday).

**Comment by tseaver** [comment]
Great!  LGTM

**Pull request merged**
