### PR TITLE
Upgrading version to 0.8.0.

### PR DESCRIPTION
**Pull request by dhermes**
@tseaver We should hold off on this until the DNS docs are in.

### CODE REVIEW

**Comment by dhermes** [comment]
Running

```bash
$ git log 0.7.1..cut-0.7.2 \
> | grep 'Merge pull request ' \
> | awk -F ' ' '{print $4}' \
> | sort
```

yields

#1041
#1043
#1055
#1056
#1060
#1063
#1064
#1068
#1070
#1072
#1074
#1075
#1078
#1079
#1080
#1083
#1084
#1086
#1087
#1088
#1090
#1092
#1096
#1097
#1098
#1106
#1107
#1110
#1112
#1113
#1114
#1117
#1118
#1119
#1120
#1121
#1122
#1128
#1129
#1131
#1135
#1137
#1138
#1139
#1140
#1144
#1145
#1148
#1149
#1152
#1153
#1155
#1157

**Comment by dhermes** [comment]
@tseaver I have to teach in 23 minutes, so the release notes may not be done for a few hours.

**Comment by dhermes** [comment]
@tseaver PTAL at the release notes. Can you write the release notes for BigQuery (commit numbers below, fancy links here):

- #1056
- #1064
- #1068
- #1072
- #1120
- #1128
- #1135

----

```
## General

- Added comprehensive [authentication document][1]
- Added Code of Conduct (#1086)
- Remove `from_service_account_json` and `from_service_account_p12`
  factory methods from `Connection` classes. These were redundant since
  the `Client` classes also have them and the `Client` classes
  are the user-facing classes. (#1113)
- Added the [Python tutorial][3] and [`getting-started-python`][4] repo to
  "examples". (#1155)

## Datastore

- Returned `None` when no cursor is returned from a query (#1054)
- Updating outdated (pre-`Client`) docs (#1098)

## BigQuery

- #1056
- #1064
- #1068
- #1072
- #1120
- #1128
- #1135

## Bigtable

- Began development of `gcloud.bigtable` package (#1122, #1148, #1152, #1153)
- Fully working source lives [elsewhere][2] and the plan
  **was** to slowly port it into `gcloud-python`, though
  we are now discussing (#1159) other options.

## Resource Manager API

- New API added (#1083)

## DNS API

- New API added (#1137, #1138, #1140, #1144, #1145, #1149, #1160)

[1]: http://googlecloudplatform.github.io/gcloud-python/stable/gcloud-auth.html
[2]: https://github.com/dhermes/gcloud-python-bigtable
[3]: https://cloud.google.com/python
[4]: https://github.com/GoogleCloudPlatform/getting-started-python
```

**Comment by dhermes** [comment]
@tseaver What are we waiting for here?

**Comment by tseaver** [comment]
@dhermes release notes updated

**Comment by tseaver** [comment]
This should probably be `0.8`, given support for new APIs.

**Comment by dhermes** [comment]
@tseaver I updated to `0.8.0`

If you are happy with this release notes, feel free to merge (after Travis passes)

Then I'll push the new tag and make the release.

**Comment by tseaver** [comment]
@dhermes merged.

**Comment by dhermes** [comment]
Tag pushed and release created on GH

**Pull request merged**
