### PR TITLE
Package docs files for simple deployment

### PR DESCRIPTION
**Pull request by daspecster**
- Working towards cleaner packaging for releases.
- Fixed a bug in the navigation.

### CODE REVIEW

**Comment by dhermes** [comment]
Does this break the standard Sphinx docs, e.g. `tox -e docs-rtd`?

**Comment by daspecster** [comment]
I don't think so, however it looks like it's broken anyway.

AFAICT there are no overlapping directories.
`tox -e docs-rtd`'s output directories are `sphinx-build -W -b html -d docs/_build_rtd/doctrees docs docs/_build_rtd/html`

However I do get this error when running `tox -e docs-rtd` 
```bash
- gcloud.error_reporting.client
ERROR: InvocationError: '/Users/daspecster/Documents/google/gcloud-py/.tox/docs-rtd/bin/python /Users/daspecster/Documents/google/gcloud-py/scripts/verify_included_modules.py'
```

I'll fix this real quick an make another PR.

**Comment by dhermes** [comment]
Does that mean `tox -e docs` is broken as well?

**Comment by daspecster** [comment]
Oddly, `tox -e docs` seems to work.

**Comment by dhermes** [comment]
That is odd

**Comment by daspecster** [comment]
Ok, so I uninstalled gcloud from my venv and reinstalled it via `python setup.py develop` and now `tox -e docs-rtd` and `tox -e docs` are both working again.

**Comment by dhermes** [comment]
`tox` should be isolated from your `venv`, that is the whole point of `tox`

**Comment by daspecster** [comment]
Yeah, I'm really not sure what was going on at this point.

Maybe I had something funky going on and somehow it was picking up an old version of gcloud?

> When your test commands execute they will execute with a PYTHONPATH setting that will lead Python to also import from the subdir below the directory where your tox.ini file resides.

- https://testrun.org/tox/latest/example/basic.html#setting-environment-variables

**Comment by dhermes** [comment]
This LGTM provided it doesn't break RTD. Can you check when the new build happens

https://readthedocs.org/projects/gcloud-python/builds/

and make sure

http://gcloud-python.readthedocs.io/en/latest/

looks fine?

**Comment by daspecster** [comment]
Will do!

**Comment by daspecster** [comment]
Looks like ReadTheDocs built successfully. Clicking around on the site works good.

https://readthedocs.org/projects/gcloud-python/builds/4249133/

**Pull request merged**
