### PR TITLE
Merge master into datastore-v1beta3.

### PR DESCRIPTION
**Pull request by pcostell**

### CODE REVIEW

**Comment by dhermes** [comment]
@pcostell, let me handle this?

**Comment by tseaver** [comment]
:+1:  for my commits.

**Comment by pcostell** [comment]
@dhermes Sure thing -- Just wanted lint to pass on my other PR and this seems like the right way to do that. Will close this out.

**Comment by dhermes** [comment]
Sorry, I didn't realize @tseaver change made it into `master`. I just merged and pushed to `datastore-v1beta3` so we should be all good.

**Pull request closed without merging**
