### PR TITLE
Adding subdirectories for versioned docs.

### LINKED ISSUE #472: Version the docs
The docs at http://googlecloudplatform.github.io/gcloud-python/datastore-api.html document the current API at git head - and include a version tag of 0.3.0

This matches the current released version on pypi (that does not have the recent change for implicit credentials)

Please consider using something like readthedocs and provide versioned docs - so that what users find actually matches what they are likely to install :)

Or at least mark the version in master as -dev with a warning in docs, and tag to stable version in a branch.

### PR DESCRIPTION
**Pull request by dhermes**
Fixes #472.

This accompanies #624 and that needs to be merged before this. (Though the merges should happen at essentially the same time.)

### CODE REVIEW

**Comment by dhermes** [comment]
In addition to this, we need to add a "version" page. We can probably borrow from `node`:

screen_shot_064

instead of

screen_shot_065

**Comment by dhermes** [comment]
Will also need to update the "back to home" link:
https://github.com/GoogleCloudPlatform/gcloud-python/blob/7c5ffd90d6719a9b61c60a608d39a8df7048e822/docs/_templates/layout.html#L61
when updating versions

**Comment by dhermes** [comment]
@tseaver I'm hoping to push this and #624 through today so we can cut `0.4.1`.

**Comment by tseaver** [comment]
LGTM

**Comment by dhermes** [comment]
w00t!

http://googlecloudplatform.github.io/gcloud-python/master/ now has c6718f3 (the current HEAD in master)

and

http://googlecloudplatform.github.io/gcloud-python/ redirects to 
http://googlecloudplatform.github.io/gcloud-python/latest/

(Though shortly we'll have a landing page there)

**Pull request merged**
