### PR TITLE
Add dotnet link to navigation

### PR DESCRIPTION
**Pull request by daspecster**
Closes https://github.com/GoogleCloudPlatform/gcloud-common/issues/151

### CODE REVIEW

**Comment by tseaver** [comment]
LGTM

**Comment by dhermes** [comment]
FYI this is in http://googlecloudplatform.github.io/gcloud-python/latest/ but not on http://googlecloudplatform.github.io/gcloud-python/. Sent #1991 to address

**Comment by daspecster** [comment]
?
screen shot 2016-07-18 at 1 43 44 pm

**Comment by daspecster** [comment]
Oh maybe it built fast before I checked.

**Comment by dhermes** [comment]
Indeed

**Pull request merged**
