### PR TITLE
Updating to version 0.4.0 for PyPI release.

### PR DESCRIPTION
**Pull request by dhermes**
@tseaver It [seems][1] I'll need to create the tag after this PR is accepted (can't bring in tags in PRs).

After that I'll create and document a [release][2].

[1]: http://stackoverflow.com/a/12279290/1068170
[2]: https://github.com/GoogleCloudPlatform/gcloud-python/releases

### CODE REVIEW

**Comment by tseaver** [comment]
LGTM

**Comment by dhermes** [comment]
Tag pushed and building in https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/49813885

**Comment by dhermes** [comment]
Starting to edit https://github.com/GoogleCloudPlatform/gcloud-python/releases/tag/v0.4.0 to describe the updates (massive).

**Comment by dhermes** [comment]
New version pushed https://pypi.python.org/pypi/gcloud/0.4.0

**Comment by dhermes** [comment]
@tseaver PTAL at https://github.com/GoogleCloudPlatform/gcloud-python/releases/tag/v0.4.0 and see if there are any changes I left out

**Pull request merged**
