### PR TITLE
Removing demo code.

### LINKED ISSUE #1443: gcloud.datastore.demo seems broken
Outside of the datastore demo throwing errors, it looks like we added a license header to it, which doesn't get ignored by our demo runner (and definitely confused me).

If we're going to keep these, can we fix them up?
If not, can we delete them?

### PR DESCRIPTION
**Pull request by dhermes**
Fixes #1443.

@jgeewax WDYT?

### CODE REVIEW

**Comment by dhermes** [comment]
@jgeewax PTAL

**Comment by tseaver** [comment]
Assuming @jgeewax says we're OK to drop the demos, the mechanics of this PR look fine to me.

**Comment by dhermes** [comment]
@jgeewax PTAL

**Comment by dhermes** [comment]
@jgeewax Bump.

**Comment by jgeewax** [comment]
Since we don't advertise this anywhere, let's kill it for now. We can always bring this back if there's good reason.

**Pull request merged**
