### PR TITLE
Adding BigQuery support for legacy SQL.

### LINKED ISSUE #1607: Call for comments: Python 2.6 support will be dropped August 1, 2016
Anyone who thinks they still need Python 2.6, please speak up here. (Sorry there isn't a better channel.)

Relates to #995 

/cc @tseaver @jgeewax

### PR DESCRIPTION
**Pull request by dhermes**
Fixes #1607.

### CODE REVIEW

**Comment by dhermes** [comment]
Not sure how long this has been around but there is a [branch miss][1] in `gcloud.stream.transfer`.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/df47b57e8ee2704411bbaf5cb4c494e9be349de8/gcloud/streaming/transfer.py#L1041-L1051

**Comment by tseaver** [comment]
@dhermes Coveralls makes me cry.

**Comment by dhermes** [comment]
OK. I'll try to clean that up soon-ish.

**Comment by tseaver** [comment]
I've got that one

**Comment by dhermes** [comment]
@tseaver Any issues with this PR?

**Comment by tseaver** [comment]
LGTM

**Comment by kelvinabrokwa** [comment]
@dhermes @tseaver thank you!

**Pull request merged**
