### PR TITLE
Fake commit.

### PR DESCRIPTION
**Pull request by dhermes**
@tseaver This is to make sure #940 works.

### CODE REVIEW

**Comment by tseaver** [comment]
LOL:  failed lint:

> ************* Module gcloud.datastore.query
> C: 83, 0: Unnecessary parens after 'print' keyword (superfluous-parens)

**Comment by dhermes** [comment]
@tseaver Yep and I also discovered `tox -e docs` failed. The nice thing is that pylint won't complain about that if `from __future__ import print_function` is in the module.

**Comment by dhermes** [comment]
@tseaver We can address that in #943. This commit is not intended to be merged.

----

More importantly, 99.99% did not result in a failure from coveralls.io

I'll dig in now and see what I can do.

**Comment by dhermes** [comment]
@tseaver I signed in to coveralls.io and changed the settings, let's hope this handles it

screen_shot_014

**Comment by dhermes** [comment]
I should mention that both the "COVERAGE THRESHOLD FOR FAILURE" and "COVERAGE DECREASE THRESHOLD FOR FAILURE" boxes were empty (which I take to mean unset) before I updated the values.

**Comment by dhermes** [comment]
@tseaver I'm closing out. It looks like tweaking the settings did the trick. Feel free to re-open if you don't think this resolves it.

**Pull request closed without merging**
