### PR TITLE
Rename 'dataset.Dataset' -> 'client.Client'.

### PR DESCRIPTION
**Pull request by tseaver**
See #944.

### CODE REVIEW

**Comment by dhermes** [comment]
LGTM with emphasis on m == ME

@jgeewax May have a preference here.

**Comment by jgeewax** [comment]
OK so sample code would read something like...

```python
client = datastore.Client(dataset_id='whatever')
client.get(<key here>)
```

?

If so, then huge +1.

**Comment by dhermes** [comment]
@jgeewax Yes

@tseaver Feel free to merge. Do you have most of #944 waiting to be sent out or still working on it?

**Comment by tseaver** [comment]
It is still in work (I have the ordering / break-up somewhat wrong in #944).

**Pull request merged**
