### PR TITLE
Modify gcloud-java logo to be white svg

### PR DESCRIPTION
**Pull request by ajkannan**
The previous logo was a png with some extra color.  This one is more in line with the style of the other language icons.

### CODE REVIEW

**Comment by dhermes** [comment]
LGTM. @jgeewax Do you also want a screenshot here (as in #1108)?

**Comment by jgeewax** [comment]
Yea -- w/o a screen shot I can't really say anything more than "hey nice XML!"

**Comment by dhermes** [comment]
@ajkannan Can you build the docs or do you need me to?

**Comment by ajkannan** [comment]
I can build the docs & post the screenshot.

**Comment by ajkannan** [comment]
Actually I'm getting some sphinx errors that have to do with how I setup and changed my environment.  If it's not too much trouble, do you mind building them @dhermes ?

**Comment by dhermes** [comment]
I don't mind at all. I'd love to see the errors too (in case it's something we can fix / make easier)

**Comment by dhermes** [comment]
For future me and other people, here is how I am recreating this PR:

```bash
$ # Visit: https://api.github.com/repos/GoogleCloudPlatform/gcloud-python/pulls/1107/commits
$ # parent in MASTER: 0dfe5ebc936c141e8f3ca13733b69f68155fe76f
$ git branch pr-1107 0dfe5ebc936c141e8f3ca13733b69f68155fe76f
$ git checkout pr-1107
$ wget https://patch-diff.githubusercontent.com/raw/GoogleCloudPlatform/gcloud-python/pull/1107.patch
$ git am 1107.patch
$ rm 1107.patch
```

----

screen_shot_005

**Comment by dhermes** [comment]
@jgeewax I'm going to merge. LMK if I missed something that needs to be reverted.

**Pull request merged**
