### PR TITLE
Remove '_implicit_environ'

### PR DESCRIPTION
**Pull request by tseaver**
Uses #978 as a base.

Final cleanup for #944.

### CODE REVIEW

**Comment by dhermes** [comment]
Ping me here when #978 is in.

**Comment by tseaver** [comment]
@dhermes I've rebased against the latest in #978.  I will rebase again and ping you after it lands on master.

**Comment by tseaver** [comment]
@dhermes now rebased against master, after merging #978.

**Comment by tseaver** [comment]
@dhermes Rebased after merge of #978 and #982. PTAL

**Comment by tseaver** [comment]
I'm not as fussy as you about the commit history -- if you'd like, I can just squash the whole PR into a single commit.

**Comment by dhermes** [comment]
I'm not **that** fussy.

I think re-committing the "Update batch/transaction/query to hold client." commit only to remove those changes later is a bit silly, but not worth arguing over. (Just re-read my comment yesterday, noticed "moral" instead of "normal", unintentionally a bit dramatic by me! Reviews from phone will do that to you.) Your "`git` style" can lead to issues like that since you always add review changes as new commits. In this case (this PR and #978) you're better off using `git cherry-pick` on the upstream commits than `git rebase`.

Code LGTM. Feel free to merge.

**Pull request merged**
