### PR TITLE
Remove gcloud vendor and just use `apitools` code

### LINKED ISSUE #755: DISCUSSION: Switch to `apitools` as a dependency
This was an issue before `apitools` was on PyPI and before it's dependencies were Py3 compatible. Now neither of these are blockers.

See #754 for context.

### PR DESCRIPTION
**Pull request by dhermes**
See #808 for previous discussion.

Fixes #755.

Labeled dont-merge for now because it depends on an un-released fix in `apitools`.

/cc @craigcitro

### CODE REVIEW

**Comment by craigcitro** [comment]
and since the other PR is closed -- apitools release is done, so no more worry there.

**Comment by dhermes** [comment]
Thanks for the release Craig! @tseaver PTAL, dont-merge label removed.

**Comment by tseaver** [comment]
LGTM

**Comment by dhermes** [comment]
@tseaver I'm gonna cut a release today or tomorrow

Stay in the `0.4` series or go to `0.5.0`? (I vote the latter.)

**Comment by tseaver** [comment]
I'd go with 0.5.0:  we're including a new API, for instance.

**Pull request merged**
