### PR TITLE
Factor out datastore API surface.

### PR DESCRIPTION
**Pull request by dhermes**
This is in preparation for a gRPC equivalent of that API.

### CODE REVIEW

**Comment by tseaver** [comment]
The API helper indirection SGTM.  One question:  should the tests for the `Client` methods change to use a mocked helper?  Seems like it would make swapping in the gRPC version later more straightforward to test.

**Comment by dhermes** [comment]
Does #2099 make it clear how the gRPC test swapping is done?

LGTY?

**Comment by tseaver** [comment]
Hmmm, it looks as though we don't have explicit tests for the `Connection` API methods at all:  we must be getting coverage via the higher-level objects?

**Comment by dhermes** [comment]
It's unclear to me. Can we handle outside this PR? (Working on fixing the merge conflict right now.)

**Comment by tseaver** [comment]
#2113 tracks the indirect coverage issue.  LGTM pending Travis.

**Pull request merged**
