### PR TITLE
#1071: fix BQ system tests under Py3k

### PR DESCRIPTION
**Pull request by tseaver**
See #1071.

### CODE REVIEW

**Comment by tseaver** [comment]
@dhermes PTAL.

**Comment by dhermes** [comment]
Makes me think we should also have `tearDown` keep going if a delete fails. (Better yet would be just to leave blobs out of it and call `bucket.delete(force=True)`, though then it can't inter-mix with the delete-able BigQuery objects.)

**Comment by dhermes** [comment]
@tseaver Running system tests now on local machine. Should be done soon.

**Comment by tseaver** [comment]
We could make `to_delete` a list of callables, and use `functools.partial` to curry in the `force=True` bit for buckets.

**Comment by tseaver** [comment]
BTW, do you have access to clean up the stranded buckets on the Travis project's console?

**Comment by dhermes** [comment]
Yes I do. Just deleted the 2 most recent from test failures

**Comment by dhermes** [comment]
LGTM. System tests all passing.

**Pull request merged**
