### PR TITLE
Add link from python docs page to gcloud-java

### PR DESCRIPTION
**Pull request by ajkannan**
The python docs page needs to link back to gcloud-java docs.  There's a wrinkle though; gcloud-java uses javadoc, which is a completely different template compared to other languages' docs pages (see http://googlecloudplatform.github.io/gcloud-java/site/0.0.7/apidocs/index.html).  The javadocs page also doesn't have a link back to other languages' docs, and there isn't a stable link to redirect to the latest version's javadocs page (though could be added if needed).  

This PR proposes linking back to the gcloud-java landing page instead of the javadoc.  Thoughts? cc/ @jgeewax

### CODE REVIEW

**Comment by dhermes** [comment]
LGTM

**Comment by dhermes** [comment]
@ajkannan Does https://github.com/GoogleCloudPlatform/gcloud-python/pull/1095#issuecomment-135181691 change the link? If so, please submit a new PR.

**Comment by ajkannan** [comment]
It doesn't change the link (I went with the landing page link in this PR).

**Comment by dhermes** [comment]
Great!

**Pull request merged**
