### PR TITLE
Adding LICENSE headers to gcloud.streaming.

### PR DESCRIPTION
**Pull request by dhermes**

### CODE REVIEW

**Comment by dhermes** [comment]
@tseaver The failure is lint:

```
C:  1, 0: Too many lines in module (1213/1200) (too-many-lines)
```

I can temporarily disable for the file or temporarily raise the limit and deal with after this PR? I'm expecting to lean out this code a bit as I pass through to factor out `httplib2` dependencies.

**Comment by daspecster** [comment]
I think that's fine. It's barely 1% over.
If you're worried about remembering this later, you could make an issue.

**Comment by dhermes** [comment]
@daspecster I was asking @tseaver because he dislikes the churn (as do I) in the settings

**Comment by daspecster** [comment]
Gotcha,
Couldn't you just add something like this to this particular module?
`# pylint: disable=C0321`
until the refactoring happens?

**Comment by dhermes** [comment]
Yup that was

> I can temporarily disable for the file

but I wouldn't use the obfuscated `C0321` I'd use `too-many-lines` to make it clear

**Comment by dhermes** [comment]
@tseaver PTAL

**Comment by tseaver** [comment]
Grrr, arbirtray limits bite us again.  Go ahead with a per-file override, I think.

**Comment by tseaver** [comment]
LGTM once pylint is appeased.

**Pull request merged**
