### PR TITLE
WAG:  try to preinstall 'grpcio' on appveyor.

### PR DESCRIPTION
**Pull request by tseaver**
See #1863.

### CODE REVIEW

**Comment by dhermes** [comment]
Sorry for n00b question, what is WAG?

**Comment by dhermes** [comment]
LGTM

**Comment by tseaver** [comment]
@dhermes "WAG" -> "wild-assed guess".

**Comment by tseaver** [comment]
Now we cross our fingers and think Good Thoughts(tm).

**Comment by tseaver** [comment]
[Horsefeathers](https://ci.appveyor.com/project/dhermes/gcloud-python/build/job/8swv02oi6s42qbgd).  My `cmd.exe` fu has withered away like the Marxist state.

**Comment by dhermes** [comment]
@tseaver It failed https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.432.master

**Comment by dhermes** [comment]
```
%CMD_IN_ENV% if "%INSTALL_GRPC%"=="1" (pip install grpcio)
Using default MSVC build environment for 64 bit architecture
Executing: if ""=="1" (pip install grpcio)
'if' is not recognized as an internal or external command,
operable program or batch file.
Command exited with code 1
```

**Comment by tseaver** [comment]
If we drop testing Python 2.6 on Appveyor, I think we can get away with installing `grpcio` and the `gax-*` packages unconditionally.

**Comment by dhermes** [comment]
👍  Dropping Windows Python 2.6 testing is A-OK with me.

**Pull request merged**
