### PR TITLE
Address second part of 477: Remove query(), entity(), and transaction() methods from Dataset.

### PR DESCRIPTION
**Pull request by dhermes**
**NOTE**: Has #478 as diffbase.

### CODE REVIEW

**Comment by elibixby** [comment]
I'm not sure about removing transaction from dataset (and dataset/transactions in general). Is it not valuable to support working on multiple transactions simultaneously? Transactions are not unique to a dataset much less a connection.

**Comment by dhermes** [comment]
RE: "Tracking string literals". Carrying around `dataset_id = 'foo'` is no easier or harder than carrying around `dataset = Dataset('foo')`. Maybe I'm missing something?

RE: "Multiple datasets". This support is not being removed.

RE: "Splitting methods across `Key` and `Entity`". I had hoped to put them all on `Key` but `.save()` depends on the actual data as does `.reload()`. (I am not sure `reload()` is needed.) The datastore team asked us to take `get` off the `Entity` but maybe putting them all in `datastore.__init__` is the right way to go.

All this notwithstanding, the `Dataset` class is just a wrapper around a single string and a `Connection` which does all the work.

**Comment by elibixby** [comment]
Other than the fact that `dataset.save(stuff)` feels more natural to me than `connection.save(stuff, dataset_id)` (which I have no rational argument for):

Eliminating dataset prevents us from allowing users to associate persistent settings on a per dataset basis, for example, eventually consistent reads, or forced mutations. Instead they have to specify these options each time they call the method in connection. 

In my mind a dataset was an immutable wrapper for all the optional arguments to mutations and fetches. So the interface for `save`, `delete`, etc can be much cleaner, while the API still has full functionality. In my api mock up, dataset needed to do a lot of work, not just keeping track of an id:

*keep track of read_options
*automatically attach partition_ids to keys (to support namespacing)
*keep track of mutation options
*super-class for transaction (which behaving similarly, in addition to keeping track of a transaction_id and sanity checking read/write options)
*factory for transactions and bulk mutators (clones over option fields to the new objects)

None of this functionality should be merged into connection, as it all depends on options which could reasonably be different depending on the dataset. 

All of this could be done with optional arguments to `connection` methods but it feels much cleaner to have them wrapped in an object.

**Comment by dhermes** [comment]
These seem like great ideas, can we track elsewhere?

RE: Methods on `connections`, the idea is for people to execute something like
```python
from gcloud import datastore
datastore.set_defaults()
```
and then from then forward
```
datastore.get_entities(keys)
datastore.allocate_ids(incomplete_key, num_keys)
...
```
etc.

**Comment by tseaver** [comment]
@dhermes, you you want to rebase, or should we just merge it manually.

**Comment by tseaver** [comment]
LGTM, by the way.

**Comment by elibixby** [comment]
@dhermes 

with that `datastore` syntax how do users interact with multiple datasets/namespaces?

**Comment by dhermes** [comment]
@elibixby Please file an issue. Let's discuss please before any implementation.

**Pull request merged**
