### PR TITLE
Fix handling of timestamps in BigQuery insert data method

### LINKED ISSUE #1247: [BigQuery] Can't insert correct TIMESTAMP.
In my environment, I can't insert correct data to the `TIMESTAMP` column.

- gcloud 0.8.0
- Python 2.7.10
- MacOS X 10.10.5

The following snippet is the smallest reproducible example.
Please let me know that it's a bug or my mistake.

```python
import os
from datetime import datetime
from gcloud import bigquery

GCP_KEY_PATH = os.path.join(os.path.dirname(__file__), './gcpkey.json')
project_id = 'my_project'
dataset = 'tmp'
table_name = 'test'

bq = bigquery.Client.from_service_account_json(GCP_KEY_PATH, project=project_id)
table = bq.dataset(dataset).table(name=table_name)

if not table.exists():
    table.schema = [bigquery.SchemaField('time', 'TIMESTAMP')]
    table.create()

table.reload()
rows = [[datetime.now()]]
table.insert_data(rows)

```

### PR DESCRIPTION
**Pull request by dhermes**
Fixes #1247.

### CODE REVIEW

**Comment by dhermes** [comment]
I just realized Bigtable has me trained too much. Wrote Bigquery instead of BigQuery in the commit messages.

**Comment by dhermes** [comment]
FWIW I cherry-picked the second commit onto head and ran the system test with the error reported by @kamatama41 and got the following:

```python
======================================================================
ERROR: test_load_table_then_dump_table (bigquery.TestBigQuery)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../gcloud-python/system_tests/bigquery.py", line 232, in test_load_table_then_dump_table
    rows, _, _ = table.fetch_data()
  File ".../gcloud-python/.tox/system-tests/local/lib/python2.7/site-packages/gcloud/bigquery/table.py", line 611, in fetch_data
    rows_data = _rows_from_json(response.get('rows', ()), self._schema)
  File ".../gcloud-python/.tox/system-tests/local/lib/python2.7/site-packages/gcloud/bigquery/_helpers.py", line 81, in _rows_from_json
    row_data.append(converter(cell['v'], field))
  File ".../gcloud-python/.tox/system-tests/local/lib/python2.7/site-packages/gcloud/bigquery/_helpers.py", line 42, in _datetime_from_json
    return _datetime_from_microseconds(1e6 * float(value))
  File ".../gcloud-python/.tox/system-tests/local/lib/python2.7/site-packages/gcloud/_helpers.py", line 235, in _datetime_from_microseconds
    return _EPOCH + datetime.timedelta(microseconds=value)
OverflowError: date value out of range

----------------------------------------------------------------------
Ran 11 tests in 69.796s
```

**Comment by tseaver** [comment]
LGTM.  OK to merge w/ pylint failing on Travis, pending #1248.

**Comment by dhermes** [comment]
I'll just wait for #1248

**Comment by dhermes** [comment]
@tseaver Assuming your LGTM still holds after rebasing.

**Comment by kamatama41** [comment]
Great job! Thank you for fixing quickly :smile:

**Comment by dhermes** [comment]
Sure thing. Thanks for reporting and finding the bug.

**Pull request merged**
