### PR TITLE
Attempt to fix windows path crash

### PR DESCRIPTION
**Pull request by daspecster**
@tseaver not sure how I feel about the `NO COVER`'s.  The only other option I could think of was skipping tests on windows.

Appveyor: https://ci.appveyor.com/project/daspecster/gcloud-python-utjkc

LMKWYT

### CODE REVIEW

**Comment by daspecster** [comment]
gahhh...lint 'ungrouped-imports'? I set it to ignore those?

**Comment by tseaver** [comment]
@daspecster I just merged #1974 to `master`, which should resolve the pylint problems for you.

**Comment by tseaver** [comment]
LGTM

**Comment by tseaver** [comment]
Ugh, still [blows up trying to install `grpcio` on Python 3.4/3.5](https://ci.appveyor.com/project/daspecster/gcloud-python-utjkc/build/1.0.40.master/job/0wkdos8gt0oj9vr1#L147).  Looks like there are [no Py3k-compatible wheels on PyPI](https://pypi.python.org/pypi/grpcio), which means it falls back to building from source, and hence needs `protoc`.

**Comment by daspecster** [comment]
yeah I noticed that...
Doesn't look like they have the py3 stuff yet.
https://github.com/grpc/grpc/issues/7135

**Pull request merged**
