### PR TITLE
Fixes #937 - Adds HTTP method and URL to exceptions.

### LINKED ISSUE #937: GCloudErrors (like NotFound) should show the URL that was referenced
Saying "the requested entity was not found" is useful if you're working with one entity only... otherwise it's just sort of like saying "something went wrong".

If we're able to figure out the URL that raised the error, we should include it in the exception (and the `__str__` version of the exception.

### PR DESCRIPTION
**Pull request by dhermes**
@jgeewax Taking #938 over since it lingered.

@tseaver I rebased and will shortly send another commit addressing review feedback.

### CODE REVIEW

**Comment by dhermes** [comment]
@tseaver PTAL

The things left unaddressed from the last PR were as follows:

----

From @tseaver: Wasn't sure about a couple things, so wanted to ask...

1. Name of the variable (`request_string`). Seems expressive, but would rather pass a request object or something similar. Should I rename? Or pass two (`method` and `url`) on to `make_exception`?
1. Assembling the request string in the `make_exception` call (seemed like it might be better done on a separate line?)

From @dhermes: Should we have a newline somewhere in the error message if it gets too long? (I lean towards no because of line wrapping.)

**Comment by tseaver** [comment]
`request_string` seems wrong -- how about `description` or `info`?

I'm -0 on injecting a newline (thinking e.g. about logfiles:  human readability vs. parsing by machine).

**Comment by dhermes** [comment]
WDYT of `error_info` or `extra_error_info`?

**Comment by tseaver** [comment]
`error_info` SGTM.

I've closed #938

**Comment by dhermes** [comment]
@tseaver Are we all good then?

**Comment by tseaver** [comment]
LGTM

**Comment by jgeewax** [comment]
LGTM - sorry for letting this linger. Thanks for cleaning it up for me :(

**Comment by dhermes** [comment]
No worries @jgeewax

**Pull request merged**
