### PR TITLE
Merging logging-stdlib-handler-feature branch back into master

### LINKED ISSUE #2102: Merging logging-stdlib-handling-feature into master
@tseaver @dhermes @jgeewax tell me what needs to be done.

The feature branch approach is not really working either.

### PR DESCRIPTION
**Pull request by dhermes**
Fixes #2102

Will likely fail the CLA check (since it contains someone else's commits) but we can just merge with a failed check.

/cc @waprin

### CODE REVIEW

**Comment by dhermes** [comment]
@waprin There are two commits with subject "Add Logging Handler", and this one seems to not make sense:
https://github.com/GoogleCloudPlatform/gcloud-python/pull/2151/commits/9af9800932f053dc597492895c581cb5756d3fe5

Can you vet?

**Comment by waprin** [comment]
Doesn't make sense but let me quickly review

**Comment by waprin** [comment]
Yeah bad commit that should be nuked

**Comment by dhermes** [comment]
@waprin Where was it from? Stray commit from bad rebase? Also why did CLA bot not yell at me?

**Comment by dhermes** [comment]
When you say nuke do mean folded into the original or just deleted?

**Comment by waprin** [comment]
deleted

**Comment by dhermes** [comment]
@waprin I deleted and in the process decided to fold in the rebase changes needed to avoid the weird extra commit.

I made some other changes, but want them to be clear so it doesn't seem to nanny-ish: https://gist.github.com/dhermes/02bf516901721cb3d2a3c48cd93958b0

As you can see the changes are the following:

- Removing trailing empty lines in files
- Changing double spaces for single spaces
- Rewording / rewriting some docstrings (mostly to keep the first line below 80 chars, but also just adding more attention to detail a la #2071)
- For "ugly indent" reasons constructing some dictionaries outside of function calls.
- raised `NotImplementedError` instead of `NotImplementedError()` (does the same)

----

We can address outside this PR but I'm also pretty uncomfortable with

- a module named `gcloud.logging.handlers.handlers`
- the ad-hoc copy of a `Client` in `BackgroundThreadTransport.__init__`

**Comment by waprin** [comment]
@dhermes changes look good. 

> a module named gcloud.logging.handlers.handlers

Why do you consider this a problem? I'm fine to change it, we could roll that code into `__init__` or maybe `gcloud.logging.handler.core`? `gcloud.logging.handlers.logging` but that might also be confusing. 

> the ad-hoc copy of a Client in BackgroundThreadTransport.__init__

Just not sure what to do with this, if you want I can help with https://github.com/google/oauth2client/issues/549 if that will expedite anything.

**Comment by dhermes** [comment]
@waprin It's the repeated name, just feels wrong / like the base-package isn't named correctly.

As for the copy, why is it there?

**Comment by waprin** [comment]
The repeated name, I agree just struggling to think of better name.  The whole thing is "add Python logging handler functionality", `handler.py` contains the actual logging handler class, the rest is support like transports etc. 

The copy is there because since it uses the client on a background thread to write the logs, there's no guarantee the main thread isn't using the client at the same time. There's no way to lock the client and the system tests were occasionally failing due to this, copying seems the most sane approach.

**Comment by waprin** [comment]
`gcloud.logging.handlers.logging` is another option since its for Python `logging` but still repeats a name. `logging_handler` is a bit verbose but might be best way to disambiguate.

**Pull request merged**
