### PR TITLE
Update to gh-pages towards fixing 472

### PR DESCRIPTION
**Pull request by dhermes**
There will be an accompanying PR for master to build with these new rules.

This makes a hierarchy

- `/master/`
- `/latest/` (alias for latest)
- `/0.4.0/`
- `/0.3.0/`

and adds `index.html` to do a redirect to `/latest`.

Also (as the update in the `master` branch will show), for the `master` subdirectory, the version is replaced by the commit hash (first 7 hex digits, via `--pretty=%h`).

Finally, by using a fresh build, I removed some old files which correspond to deleted code:
```
 delete mode 100644 master/_modules/gcloud/datastore/dataset.html 
 delete mode 100644 master/_modules/gcloud/storage/exceptions.html
 delete mode 100644 master/_modules/gcloud/storage/key.html
 delete mode 100644 master/_sources/datastore-dataset.txt
 delete mode 100644 master/_sources/storage-keys.txt
 delete mode 100644 master/datastore-dataset.html
```

### CODE REVIEW

**Comment by dhermes** [comment]
@tseaver GitHub is not happy about the size of this commit so I will just push from the command line.

For review purposes, to give an idea of how the commits were made:

1.  Moving all pages into master subdirectory (b4b226c15b20e7ba48cca57df96717ad153abe78)

    ```
    git checkout gh-pages
    git mv * master/
    git commit ...
    ```

1. Updating "master" docs with a clean build. (2323c881fd276e280ed99a8e24a68b85129788bd)

    ```
    git checkout master
    # Make change to docs/conf.py as in PR #625
    SPHINX_RELEASE=$(git log -1 --pretty=%h) tox -e docs
    mv docs/_build/html master_DOCs/
    git checkout gh-pages
    git rm -fr master/
    mv master_DOCs/ master/
    git add master/
    git commit ...
    ```

1.  Adding 0.4.0 docs in own folder and in latest. (02c903b77c10bb5f40f8c616b4e12f10c8dbe50a)

    ```
    git checkout v0.4.0
    # Change to docs/conf.py from PR #625 not needed
    tox -e docs
    mv docs/_build/html v0.4.0_DOCs/
    git checkout gh-pages
    mv v0.4.0_DOCs/ latest/
    cp -r latest/ 0.4.0/
    git add latest/ 0.4.0/
    git commit ...
    ```

1.  Adding root redirect to the latest docs. (d0713e71470b9aad4c3a8454122effe7df325440)

    This one is human reviewable.

**Comment by tseaver** [comment]
I'd say go ahead and merge -- review isn't that feasible.  We can tweak later as needed.

**Comment by dhermes** [comment]
Agreed, I wasn't expecting you to be able to review anything other than my [methods][1].

I need to hold off on pushing this until right before #625 gets merged or it will break the build process for merges.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/pull/624#issuecomment-74172335

**Comment by dhermes** [comment]
Also, instead of a rebase I'm going to wipe away (`git push -f`) all the commits since a8df46b886c518d9ee29afcb9c6184a93d0db326.

Merging #625 right after will restore the `master` docs to the tip of master.

**Comment by tseaver** [comment]
LGTM

**Pull request merged**
