### PR TITLE
DISCUSSION PR: Uses Blob's current content type (in an upload) when present.

### LINKED ISSUE #536: storage: cannot set object properties
Or at least I haven't figured out how. This is how the documentation suggests it may work.

```Python
>>> from gcloud import storage
>>> bucket = storage.get_bucket('bucket', 'id')
>>> key = storage.key.Key(bucket=bucket, name='dir/file.webp', 
...                       properties={'contentType': 'image/webp'})
>>> key.upload_from_filename('dir/file.webp')
```
Success?
```Python
>>> key.properties['contentType']
'image/webp'
>>> key.content_type
'image/webp'
```
It's a lie unfortunately. (Also verified with ```gsutil```).
```Python
>>> webp = bucket.get_key('dir/file.webp')
>>> webp.properties['contentType']
u'application/unknown'
>>> webp.content_type
u'application/unknown'
```

### PR DESCRIPTION
**Pull request by dhermes**
This is instead of using the mimetype for all files (the Python
mimetypes.guess_type method is a bit limited).

Fixes #536.

### CODE REVIEW

**Comment by dhermes** [comment]
@tseaver WDYT of allowing an explicit argument or the current object's property to override the content type (the new code doesn't even try `mimetypes.guess_type` in these cases).

**Comment by dhermes** [comment]
I am beginning to be able to articulate @thobrla concerns from #545 now after trying to implement this.

Instead of `self._properties.get('contentType')` I made two failed attempts:

- `self.content_type`: Fails because `_reload_properties()` was called (gave a 404 when the object didn't exist or failed for more spectacular reasons when I used a fake connection)
- `self.properties.get('contentType')`: Again fails because `properties` itself calls `_reload_properties` when `self._properties` is False-y.

I think we have to ditch the majority of uses of `_reload_properties`

Here are the two culprits (as of f73ad7e8fc877e14e2f9c0b4ec42430f2396f770) I mentioned:

```python
def _scalar_property(fieldname):
    def _getter(self):
        return self.properties[fieldname]

class _PropertyMixin(object):
    @property
    def properties(self):
        if not self._properties:
            self._reload_properties()
        return self._properties.copy()
```

**Comment by tseaver** [comment]
This PR LGTM.  For newly-created objects (not yet saved), we could make `properties` fall back to something sensible.

**Comment by dhermes** [comment]
@tseaver See #632 for my thoughts on the `properties` / etc. issue.

**Pull request merged**
