### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by thesandlord**
Fixed broken link

### CODE REVIEW

**Comment by thesandlord** [comment]
I signed it!

**Comment by thesandlord** [comment]
I have a corporate CLA via Google

**Comment by dhermes** [comment]
1. @jgeewax What does he need to do so that `googlebot` recognizes him?
1. The real fix to this is re-implementing / re-creating the broken link. This was filed as #1037

**Comment by jgeewax** [comment]
Hi @thesandlord : Check your GitHub username at (Google internal link) go/cla-signers -- it says we can't accept contributions until you click the right button... Can you give that a go? (https://cla.developers.google.com/)

**Comment by jgeewax** [comment]
@thesandlord : The other option is to check in the code using your @google.com e-mail address (I think).

**Comment by thesandlord** [comment]
Interesting, I've contributed to Kubernetes using this account before, and they have CLA checks as well... Is this CLA bot checking email or github user? I can sign the Google CLA with my gmail if that helps.

**Comment by thesandlord** [comment]
Ok, I had my gmail as the primary email on this account. I edited this file in the web UI, so it must have used my gmail. I have signed the individual CLA and switched my primary email to my @google so this should not happen again.

**Pull request merged**
