### PR TITLE
Workaround tox 2.3.0 regression.

### PR DESCRIPTION
**Pull request by tseaver**
See:
https://bitbucket.org/hpk42/tox/issues/294/tox-23-regression.

### CODE REVIEW

**Comment by tseaver** [comment]
@dhermes @jgeewax This one is pretty urgent:  all our tests break with tox 2.3.0.  I intend to merge as soon as Travis is green.

**Comment by dhermes** [comment]
I have a better fix.

**Comment by dhermes** [comment]
ISTM the issue is the [use of][1] `{[testenv]setenv}`. This is very similar to the issue you linked to.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/d6820b91788adcb11aee119349b1489123c12e9f/tox.ini#L56-L58

**Comment by dhermes** [comment]
```diff
diff --git a/tox.ini b/tox.ini
index e92ace7..0b3b727 100644
--- a/tox.ini
+++ b/tox.ini
@@ -54,7 +54,7 @@ passenv = {[testenv:system-tests]passenv} SPHINX_RELEASE READTHEDOCS LOCAL_RTD
 
 [testenv:docs-rtd]
 setenv =
-    {[testenv]setenv}
+    PYTHONPATH = {toxinidir}/_testing
     LOCAL_RTD = True
 basepython = {[testenv:docs]basepython}
 commands =
```

**Comment by dhermes** [comment]
Just ran `tox -e py27` with this change and it passed with no issues.

**Comment by dhermes** [comment]
Ditto on `py26,py33,py34,cover` and `lint`.

**Comment by tseaver** [comment]
@dhermes I'm not sure what you mean:  do you want to push a different PR?  Or do you think I should update this one?

**Comment by dhermes** [comment]
Just update this one and feel free to merge if you can get Travis to pass

**Pull request merged**
