### PR TITLE
Use 'grpc-google-longrunning-v2'

### PR DESCRIPTION
**Pull request by tseaver**
See: https://pypi.python.org/pypi/grpc-google-longrunning-v2/

DO NOT MERGE:  see the discussion at: https://github.com/GoogleCloudPlatform/gcloud-python/issues/2117#issuecomment-242547394

### CODE REVIEW

**Comment by tseaver** [comment]
@bjwatson  [said](https://github.com/GoogleCloudPlatform/gcloud-python/issues/2117#issuecomment-242575910):

> Sorry for the confusion. If you were already rolling your own solution for the Operations service, please continue to use that -- I think we're going to abandon grpc-google-longrunning-v2 for now. We'll keep thinking about how longrunning integrates with Veneer Toolkit and update when we know more.

**Comment by bjwatson** [comment]
Actually it was @geigerj who said that, but I concur. :)

**Comment by tseaver** [comment]
Oops, apologies for the confusion.  We would still love to have a story which let us ditch *all* the hackishly-generated code in our repo.

**Comment by bjwatson** [comment]
@tseaver Agreed. IIUC, the generated code in your repo is LRO, Bigtable, and Datastore, correct? Is there anything else?

**Comment by tseaver** [comment]
@bjwatson That is correct.

**Pull request closed without merging**
