### PR TITLE
Add basic discussion of clients to auth doc.

### PR DESCRIPTION
**Pull request by dhermes**
@jgeewax Here is a little more auth (towards #805 and #830)

To view my and your original PRs (as we go), here are some hosted files:
www.googledrive.com/host/0B8el7dRo8mVOUVlkSEJKN3pQdkk (dhermes)
www.googledrive.com/host/0B8el7dRo8mVOOHE4NzFXSmhHUWs (jgeewax)

### CODE REVIEW

**Comment by dhermes** [comment]
@jgeewax If you're lurking around GitHub, this PR is super tiny.

**Comment by jgeewax** [comment]
:+1:

**Comment by dhermes** [comment]
I assume that meant LGTM. If not, I'm happy to revert.

**Comment by jgeewax** [comment]
Yes LGTM.

**Pull request merged**
