### PR TITLE
Adding Travis build ID to resource names in system tests.

### LINKED ISSUE #1542: Incorpate Travis BUILD ID into bucket names and other resources (when available)

### PR DESCRIPTION
**Pull request by dhermes**
Fixes #1542.

### CODE REVIEW

**Comment by tseaver** [comment]
Barfing on Travis:

```python
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/system_tests/logging_.py", line 27, in <module>

    DEFAULT_METRIC_NAME = 'system-tests-metric-%d' % (_RESOURCE_ID,)

TypeError: %d format: a number is required, not str
```

**Comment by dhermes** [comment]
Gah! I added that one in a flash after initially sending the PR. Serves me right.

**Comment by dhermes** [comment]
Updated them and folded into original commit.

**Comment by tseaver** [comment]
The only change I would make is to use the delimiter at the beginning of the string returned by `unique_resource_id`:  it won't make any difference at runtime, but it will make the combined IDs more readable.

**Comment by dhermes** [comment]
@tseaver PTAL

**Comment by tseaver** [comment]
LGTM

**Comment by dhermes** [comment]
Folded into original commit. Will merge when Travis passes.

**Pull request merged**
