### PR TITLE
Implementing Bigtable Operation.finished().

### PR DESCRIPTION
**Pull request by dhermes**
This method is intended to be used to check if a create, update or undelete operation has completed.

### CODE REVIEW

**Comment by dhermes** [comment]
@tseaver I'll still use this PR but will revamp to move the method onto the `Operation` class in #1273.

**Comment by tseaver** [comment]
786720153618285b1fc132e4179df2921eb43a7f LGTM.

**Comment by dhermes** [comment]
@tseaver I rebased after #1273 and then added `cluster=object()` to `_makeOne()` in some of the `__eq__` and `__ne__` tests for `Operation`. (I realized I had forgotten to do that after extending the constructor.)

I can rollback if that is problematic.

**Comment by tseaver** [comment]
No worries.

**Pull request merged**
