### PR TITLE
Upgrading version to 0.12.0

### PR DESCRIPTION
**Pull request by dhermes**
@tseaver I'm going to start on the release notes. Can you draft the release notes for logging?

### CODE REVIEW

**Comment by dhermes** [comment]
```
$ git log -1 --pretty=%H
e91d92e6ec5db4b58c251c2d50b86f3d35839390
$ git log 0.11.0..HEAD \
> | grep 'Merge pull request ' \
> | awk -F ' ' '{print $4}' \
> | sort
```

yields

#1557
#1562
#1567
#1568
#1569
#1574
#1578
#1579
#1580
#1581
#1582
#1583
#1584
#1585
#1586
#1587
#1588
#1589
#1590
#1592
#1594
#1595
#1596
#1597
#1598
#1599
#1600
#1601
#1602
#1604
#1605
#1606
#1608
#1609
#1610
#1611
#1612
#1613
#1616
#1622
#1626
#1627
#1628
#1630
#1631
#1632
#1633
#1634
#1635
#1638
#1640
#1641
#1642
#1644
#1645
#1646
#1652
#1654
#1658
#1661
#1663
#1664
#1665
#1666
#1667
#1668
#1669
#1674
#1675
#1677
#1678
#1680
#1681
#1682
#1683
#1685
#1686
#1688

**Comment by dhermes** [comment]
Changes not noted in release notes:

- Bigtable: #1557, #1594, #1595, #1602, #1604, #1605, #1606, #1608, #1631, #1635
- Logging: #1567, #1568, #1569, #1574, #1578, #1581, #1584, #1585, #1586, #1587, #1588, #1589, #1590, #1596, #1597, #1598, #1599, #1600, #1601, #1609, #1610, #1611, #1612, #1613, #1616, #1628, #1658, #1661, #1665, #1666, #1668, #1669, #1677, #1678, #1680
- Admin: #1582, #1583, #1626, #1630, #1633, #1634, #1654, #1667, #1686

Release notes:

----


This release contains three large API additions or changes:

-   Official support of the [Google Cloud Bigtable][1] API
-   Official support of the [Google Cloud Logging][2] API
-   Upgrading [Google Cloud Datastore][3] from `v1beta2` to `v1beta3`

## BigQuery

-   Add a `template_suffix` parameter to BigQuery `Table.insert_data` (#1562).
-   Expand/clarify synchronous query usage docs (#1674).
-   Cache job constructed for a synchronous query (#1675).

## Storage

-   Pass mutated properties through to `Bucket.create` API call (#1579).
-   Allow predefined ACL names from either XML or JSON APIs (#1664).

## Pub/Sub

-   Add `Topic.list_subscriptions` (#1580).
-   Fix topic subscription path patterns (#1592).
-   Add `Message.service_timestamp` property (#1627).
-   Add support for IAM permissions on topics (#1640, #1641, #1642, #1652)
  and subscriptions (#1644, #1645, #1646)

## Datastore

-   Upgrading from `v1beta2` to `v1beta3` (see #1288). In particular
    -   the `Query.group_by` property was renamed to `Query.distinct_on`
    -   explicit support for null values in entities was added (#1464)
    -   explicit support for Geo Point values in entities was added (#1464)
    -   removing custom `GCLOUD_DATASET_ID` environment variable and
        just relying on `GCLOUD_PROJECT` (#1465)
-   Fix broken docs for `Query.add_filter` (#1622).
-   Documentation: Filtering Query by key is also possible (#1632).
-   Allow bytes or string as project value in datastore clients (#1638).

## DNS

-   Renaming `type->record_type` in DNS doc (#1663).

[1]: https://cloud.google.com/bigtable/docs/
[2]: https://cloud.google.com/logging/docs/
[3]: https://cloud.google.com/datastore/docs/concepts/overview

**Comment by dhermes** [comment]
My `git log 0.11.0..HEAD` command leaves out the merge commits from datastore, but I think #1288 is comprehensive enough that I don't need to increase my `git`-fu to find them.

**Comment by pcostell** [comment]
Release notes for Datastore available if you need to link to them: https://cloud.google.com/datastore/release-notes

**Comment by dhermes** [comment]
Added to the sample above

**Comment by tseaver** [comment]
@dhermes Since this is the first-ever release, the notes are pretty simple. :)

**Comment by dhermes** [comment]
Notes look good. LGTY to merge @tseaver?

**Comment by tseaver** [comment]
LGTM

**Comment by dhermes** [comment]
@pcostell Tag build started:
https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/120188247

That will update `gcloud` on PyPI and we are officially "launched" at that point.

**Comment by pcostell** [comment]
Hooray! Thanks @dhermes and @tseaver

**Pull request merged**
