### PR TITLE
Prepare 0.18.0 release

### PR DESCRIPTION
**Pull request by tseaver**
```
$ git log -1 --pretty=%H
27248053f1b26cf784a0ca650a64d7c10249d8d1
[/home/tseaver/projects/agendaless/Google/src/gcloud-python] 
$ git log 0.17.0..HEAD | grep 'Merge pull request ' |  awk -F ' ' '{print $4}' | sort
```

#1636
#1775
#1832
#1833
#1836
#1876
#1914
#1943
#1945
#1946
#1948
#1950
#1952
#1954
#1956
#1958
#1962
#1965
#1966
#1967
#1971
#1973
#1974
#1976
#1977
#1985
#1990
#1992
#1994
#1996
#1997
#1999
#2000
#2002
#2003
#2004
#2005
#2006
#2008
#2016
#2019
#2021
#2025
#2026
#2029
#2033
#2036
#2040
#2041
~~#3~~  stray comment from #1914

### CODE REVIEW

**Comment by tseaver** [comment]
## (DRAFT) 0.18.0 Release Notes

**Note**  This is the last release which supports Python 2.6.

### Core/testing/hygeine

- Generate JSON documentation for consumption by `gcloud-common` application. (#1775)

### Storage

- Add support for streaming upload via file-like objects. (#1914)

- Improve error message when platform does not support generating a signed blob URL. (#1966)

### Pubsub

- Add support for auto-acknowledging pulled messages. (#1636)

- Fix use of `Batch` for `pull` requests returning empty result sets. (#1956)

### BigQuery

- Make dataset, table, and synchronous query doc snippets testable (#1832, #1833, #1836)

- Fix 'Table.upload_from_file` docs example. (#1971)

- Add support for `use_legacy_sql` query property. (#1992)

- Add support for 'udf_resources' query property. (#2029)

### Bigtable

- Fix V2 docstrings (#1945, #1948).

- Make HappyBase `Table.enable_table`, `Table.disable_table`, `Table.is_table_enabled`, and `Table.compact_table` no-ops, rather than raising `NotImplementedError`. (#1997)

- Make HappyBase `Table.counter_set` conform to HBase semantics. (#2000)

- Make HappyBase `Table.create_table` atomic. (#2002)

### Logging

- Fix system tests when GAX / gRPC is enabled (#1952).

- Update branding from "Cloud Logging" to "Stackdriver Logging." (#1962)

### DNS

- Fix `Zone.resource_record_set` usage example. (#1977)

### Error Reporting

- Initial client implementation (#1946).

**Comment by tseaver** [comment]
@daspecster, @dhermes PTAL

**Comment by daspecster** [comment]
LGTM,
0.17.1 goes out first though right?

**Comment by dhermes** [comment]
@tseaver LGTM. Can you squash the commits?

What is `dependency-ci` and does it show up on other PRs?

**Comment by tseaver** [comment]
@daspecster We won't make a 0.17.1 release:  we have merged feature changes (including the new ErrorReporting client) to master.

@dhermes `dependency-ci` is a hook @jgeewax suggested we try:  it doesn't actually have working Python support for anything except `requirements.txt`.  It got triggered because I created this branch by editing `setup.py` directly in the Github UI, which makes it look like a "push".

**Comment by tseaver** [comment]
In favor of #2048

**Pull request closed without merging**
