### PR TITLE
Interleave doctest examples w/ API ref docs.

### LINKED ISSUE #1141: Interleave doctest examples w/ API ref docs.
Related to #1102

I just tried to walk a group of people through gcloud.pubsub, and of the few who found the docs under "Pubsub usage", almost everyone was frustrated by the examples being there rather than next to the method they were interested in. They couldn't find the specific thing they wanted quickly, whereas finding the right methods was pretty straight forward -- but then example code was hidden in a big long (and separate) page.

Ideally we would:

1. Move all the usage examples to live next to the methods they describe
1. Remove the pubsub-usage.rst file
1. Have test coverage of those docstring examples

(ie, https://googlecloudplatform.github.io/gcloud-python/stable/pubsub-topic.html has no example code snippets)

### PR DESCRIPTION
**Pull request by tseaver**
Closes #1141

See [my rationale for this implementation](https://github.com/GoogleCloudPlatform/gcloud-python/issues/1141#issuecomment-142661927)

### CODE REVIEW

**Comment by dhermes** [comment]
How to review this? Why ditch `:members:` and `:undoc-members:`?

**Comment by tseaver** [comment]
The PR trades off removing some DRY (the `:members:` and particularly `:undoc-members:`, which should arguable be excluded in any case) in exchange for getting control over the generation of the API docs (ordering, plus the ability to interleave the doctest examples in the Sphinx docs, with the promise of future testability).

It also makes the API docs more suitable for addition of exposition by non-programmer techwriters.

**Comment by dhermes** [comment]
But how do we make sure we haven't left anything out (the time-honored "check yourself (programatically) before you wreck yourself")?

**Comment by dhermes** [comment]
@tseaver Why do we consider this closed?

**Pull request closed without merging**
