### PR TITLE
#825:  Allow passing explicit connection to 'Blob.make_public'

### PR DESCRIPTION
**Pull request by tseaver**
Requires #853 as a base.

See #825.

### CODE REVIEW

**Comment by dhermes** [comment]
Ping me on this when we resolve #853

**Comment by tseaver** [comment]
Rebased against updated branch for #853.  Adjusted `Blob.make_public` to forward connection w/o subsitution to `ACL.save`.

**Comment by tseaver** [comment]
Rebased again against updated branch for #853.

**Comment by tseaver** [comment]
@dhermes any remaining issues?

**Comment by dhermes** [comment]
Have yet to review this, was waiting on the diffbase to go through. Can you rebase and ping me?

**Comment by tseaver** [comment]
@dhermes I rebased it this morning on the latest from #853.

**Comment by tseaver** [comment]
OIC, you'd like a rebase against master.

**Comment by dhermes** [comment]
LGTM

**Pull request merged**
