### PR TITLE
Select API helper based on presence of grpcio + optional environment marker

### PR DESCRIPTION
**Pull request by tseaver**
Not yet ready to merge, as the system tests will break until new versions of `grpcio` and `google-gax-pubusb-v1` are released (see #1814).

@dhermes PTAL at the overall approach to choosing gRPC vs. JSON-over-HTTP.

### CODE REVIEW

**Comment by dhermes** [comment]
I'm fine with the overall approach. As usual, I'm anti-"lazy loading approach". I'd also like to see us try to unify the APIs that use gRPC a little bit (doesn't need to happen here, just want to keep an eye on it).

**Comment by tseaver** [comment]
Issue #1857 tracks the question of lazy-loading the API helpers.

**Comment by tseaver** [comment]
@daspecster PTAL

**Comment by daspecster** [comment]
@tseaver LGTM!

**Pull request merged**
