### PR TITLE
Pin protorpc==0.10.0.

### PR DESCRIPTION
**Pull request by tseaver**
Works around https://github.com/google/protorpc/issues/12.

Fixes: #1133.

### CODE REVIEW

**Comment by tseaver** [comment]
@dhermes PTAL:  https://github.com/google/protorpc/issues/12 blocks Travis for us.

**Comment by tseaver** [comment]
Obsoleted by @craigcitro's quick release of 0.11.1 with a backward-compatibility alias.

**Comment by dhermes** [comment]
Thanks @craigcitro! 

Is `protorpc` becoming compatible with `proto3`?

**Comment by craigcitro** [comment]
no one's actively working on it, though i'm happy to review patches if you're interested.

TBH, though, i'm not quite sure what you mean by "proto3-compatible" -- the main way to use protorpc doesn't read `.proto` files, and the wire protocol is still the same. and, all the proto3 constructs have proto2 equivalents. was there something you wanted to do with it?

**Comment by dhermes** [comment]
Nope was just curious. Thanks. (FWIW I didn't think my question all the way and your answer makes a lot of sense)

**Pull request closed without merging**
