### PR TITLE
Fix scope used for Cloud Search.

### PR DESCRIPTION
**Pull request by tseaver**

### CODE REVIEW

**Comment by dhermes** [comment]
Docs?

**Comment by tseaver** [comment]
Hmmm?  The updated scope is listed on each of the API pages under "Authentication", e.g.:

- https://cloud.google.com/search/reference/rest/v1/projects/indexes/list
- https://cloud.google.com/search/reference/rest/v1/projects/indexes/search
- https://cloud.google.com/search/reference/rest/v1/projects/indexes/documents/create
- https://cloud.google.com/search/reference/rest/v1/projects/indexes/documents/delete
- https://cloud.google.com/search/reference/rest/v1/projects/indexes/documents/get
- https://cloud.google.com/search/reference/rest/v1/projects/indexes/documents/list

**Comment by dhermes** [comment]
OK. How and why and when did it change? (If you know.)

**Comment by tseaver** [comment]
I think I copied it in from the PR by @jgeewax (but don't recall).  I found the issue today while beginning work on system tests for the API.

**Comment by dhermes** [comment]
Ahhh I see. DERP

LGTM

**Pull request merged**
