### PR TITLE
Small tweaks to Connection in storage; towards a cleaner API.

### PR DESCRIPTION
**Pull request by dhermes**
- Making Connection.make_request non-public
- Making Connection.build_api_url a class method

### CODE REVIEW

**Comment by tseaver** [comment]
I don't understand the motivation for making `build_api_url` a class method:  all the callers call it via the connection instance, and then have to pass in that instance's project.

**Comment by dhermes** [comment]
The motivation doesn't precisely fit the problem. I noticed that we had an instance method here (storage) and a class method in datastore.

But the true motivation was making it to that each `Connection` instance only had public methods for making a single API request. Any other features would be moved elsewhere (like #583).

I'm still trying to figure out if / how `build_api_url` fits into that idea.

**Comment by dhermes** [comment]
@tseaver Rebased on top of #580. PTAL (my new comment above).

**Comment by tseaver** [comment]
Given that it needs instance state (the `project`), I can't see any benefit to making it a class method.  I can even imagine that having it stay an instance method would be useful for https://github.com/GoogleCloudPlatform/gcloud-meta/issues/4

**Comment by dhermes** [comment]
Cool. Closing this out.

**Comment by tseaver** [comment]
FWIW, I can certainly see making both `build_api_url` and `make_request` private.

**Comment by dhermes** [comment]
@tseaver OK I'll put that in motion and send a PR.

This means `build_api_url` should be private in `datastore` as well.

How do you feel about making them private functions in the `connection` modules? The only reason they are attached to the `Connection` objects are because of the class constants which could just as easily be module constants. (Though without looking at the code it may be a PITA to import the `connection` module in places where a `Connection` object was used freely.)

**Pull request closed without merging**
