### PR TITLE
Upgrading version to 0.7

### PR DESCRIPTION
**Pull request by dhermes**
Using last release PR (#907) as a template.

### CODE REVIEW

**Comment by dhermes** [comment]
Running

```bash
$ git log 0.6.0..cut-0.6.1 \
> | grep 'Merge pull request ' \
> | awk -F ' ' '{print $4}' \
> | sort
```

yields

#910
#914
#915
#918
#921
#923
#930
#932
#934
#940
#941
#943
#946
#948
#950
#951
#953
#954
#956
#959
#960
#961
#963
#964
#965
#967
#971
#973
#975
#976
#977

**Comment by dhermes** [comment]
@tseaver this is the current set of release notes

```
-   Implementing client in Pub/Sub, deprecating old
    implicit environment detection.
-   Fixing bug in `Blob.upload_from_file` where `os.fstat` is
    only called if the buffer object is a file.
-   Removing restriction of equality only filtering for
    `__key__` queries in datastore; also cleaning up filter
    checking in `Query` constructor.
-   Adding ability to sign URL from GAE.
-   Making `_BlobIterator` accumulate prefixes so that a
    storage list call that makes multiple requests can
    aggregate all the prefixes encountered.
-   Adding `namespace` to `datastore.Dataset` class (now
    called `datastore.Client`).
-   Adding HTTP method and URL to messages printed for
    exceptions caused by failed requests.
-   Renaming `datastore.Dataset` class as `datastore.Client`.
-   Removing `datastore.api` module and moving functionality
    into `datastore.Client`.
-   Implementing `storage.Client` class.
-   Removing `storage.api` module and moving functionality
    into `storage.Client`.
```

I'd like to wrap up #944 and #952 before cutting a release.

**Comment by tseaver** [comment]
Given the new features (clients, etc.) and the backward-incompatibilities, we should be bumping the version to something like `0.7`.

**Comment by dhermes** [comment]
Good call. I'm going to try to wrap up client in storage first, then will bump it.

**Comment by dhermes** [comment]
Commits since the last check:

#978
#979
#980
#982
#984
#985
#986
#987
#988
#989
#990
#991
#992
#993
#994
#996
#998

**Comment by dhermes** [comment]
@tseaver Newly proposed release notes:

```
## Core

-   Adding ability to sign URL from GAE.
-   Adding documentation about using `generate_signed_url`
    with Compute Engine assertion credentials.
-   Adding HTTP method and URL to messages printed for
    exceptions caused by failed requests.

## Pub/Sub

-   Implementing client in Pub/Sub, deprecating old
    implicit environment detection. (#978, #979)
-   Upgrading Pub/Sub API to v1 (from v1beta).

## Storage

-   Implementing client in Storage, deprecating old
    implicit environment detection. (#984, #987, #988,
    #989, #990, #991)
-   Removing `storage.api` module and moving functionality
    into `storage.Client`.
-   Fixing bug in `Blob.upload_from_file` where `os.fstat` is
    only called if the buffer object is a file.
-   Making `_BlobIterator` accumulate prefixes so that a
    storage.list_blobs call that makes multiple requests can
    aggregate all the prefixes encountered.

## Datastore

-   Implementing client in Datastore, deprecating old
    implicit environment detection.
-   Removing `datastore.api` module and moving functionality
    into `datastore.Client`.
-   Renaming `datastore.Dataset` class as `datastore.Client`.
-   Adding `namespace` to `datastore.Dataset` class (now
    called `datastore.Client`).
-   Removing restriction of equality only filtering for
    `__key__` queries in datastore; also cleaning up filter
    checking in `Query` constructor.

## BigQuery

-   Beginning developer experience docs for BigQuery
    API (code to follow after design stage).
```

**Comment by jgeewax** [comment]
:+1:

**Comment by tseaver** [comment]
@dhermes I updated the notes:

- Use imperative voice for verbs.
- Add PR #s.
- Place bullets on single lines for markdown compatibility.

**Comment by tseaver** [comment]
Also, I dropped any mention of the ongoing BigQuery design activity.  I think we could even create a release branch for 0.7 and delete the BQ docs entirely for it.

**Comment by dhermes** [comment]
@tseaver I don't like the idea of a release branch. If we want a custom branch, it should be for the BQ docs.

**Comment by tseaver** [comment]
We can ditch the release branch notion, but shouldn't mention BQ in the release notes (there is nothing of interest for a non-committer there).

**Comment by dhermes** [comment]
OK Cool

**Comment by dhermes** [comment]
https://pypi.python.org/pypi/gcloud/0.7.0 has been published

**Pull request merged**
