### PR TITLE
Turn on Mac OS X testing in Travis.

### PR DESCRIPTION
**Pull request by dhermes**
NOTE: This feature is still in beta according to
https://docs.travis-ci.com/user/multi-os/

See #2136

### CODE REVIEW

**Comment by tseaver** [comment]
In my experience with the `zope.*` packages, the Mac OS/X builds are hideously slow -- they need more hamsters!

**Comment by dhermes** [comment]
The `osx` build failed with a failure to untar a directory holding Python. Talk about beta! I restarted it before I could capture the error, hopefully it will improve.

**Comment by dhermes** [comment]
Failed again

```
The command "sudo tar xjf python-2.7.tar.bz2 --directory /" failed and exited with 1 during .
```

screen_shot_003

**Comment by dhermes** [comment]
Found https://github.com/travis-ci/travis-ci/issues/5975

**Comment by dhermes** [comment]
https://github.com/serverdensity/sd-agent/pull/126/files seems to have a working approach

**Comment by dhermes** [comment]
OK it turns out `osx` support is so beta we need to tell Travis that the `osx` env. is not Python but it is `language: generic` and then we need to manually install a version of Python ourselves.

**Comment by tseaver** [comment]
See [OSX infra instability. All OSX builds are stopped](https://www.traviscistatus.com/incidents/4mvp857qx8bw).

**Comment by tseaver** [comment]
@dhermes Given the poor state of the OSX support, I'm inclined to hold off and let the pioneers collect the back-arrows:  we've got enough on our plate with Travis.

**Comment by dhermes** [comment]
I somewhat agree, though it seems like `brew install python` would work on the pre-installed image. Or we could install via `conda`

**Comment by daspecster** [comment]
There's always http://hacbook.com... ;)

**Comment by dhermes** [comment]
How does that help? That's a physical piece of hardware, not a CI. Maybe I'm misreading the website?

**Comment by daspecster** [comment]
Well you get OSX for cheap so someone could put one of those in a corner someplace and then just open up the IP. Sorry @dhermes, it was more of a joke than a serious suggestion.

Well partially I guess, if I setup a Jenkins server, I may be able to find an OSX host to set it up on for the private repo. Just trying to brainstorm a little.

**Comment by daspecster** [comment]
Looks like a lot of the OSX hosted CI has been shutdown? There are some references to services supporting it and now you can't find anything on their sites.

I found...
http://devcenter.bitrise.io/docs/available-stacks

It looks like even CircleCI may only support iOS builds and not give you direct CLI access to an OSX vm.
https://circleci.com/docs/ios-builds-on-os-x/#supported-build-and-test-tools

HostedCI looks like it's been kind of dead. Last blog post was about xcode in 2014 and I don't see any documentation on OSX.
https://hosted-ci.com/blog/


Buildbot.net is a python based build system but we would have to self host :(.
https://github.com/buildbot/buildbot

**Comment by tseaver** [comment]
Do we have any reason to expect a `homebrew`-driven bulid to fail?  I mean, if we were trying to test with Apple's b0rken system python, that would be one thing....

**Comment by dhermes** [comment]
I agree @tseaver

**Comment by tseaver** [comment]
We can re-open or rework later if we decide testing on Mac is worth the pain.

**Pull request closed without merging**
