### PR TITLE
Repeating pylint after failures.

### PR DESCRIPTION
**Pull request by dhermes**
This surfaced as a false negative in #611.

### CODE REVIEW

**Comment by tseaver** [comment]
The only issue I see here is that "real" lint failures will take twice as long, even if the envvars aren't set to try to speed the test up.

**Comment by dhermes** [comment]
But the user can always "Ctrl-C" and just go fix (if the watched pot is still boiling). If they aren't watching / waiting on the run, then the time isn't as crucial?

**Comment by tseaver** [comment]
Could we only retry on failure if we were doing a limited set to begin with?

**Comment by dhermes** [comment]
Yes, I'm happy to do that. I considered it but decided to go with the solution that involved less code.

**Comment by dhermes** [comment]
@tseaver I added a boolean indicating if a restricted fileset was used. PTAL.

**Comment by tseaver** [comment]
LGTM

**Pull request merged**
