### PR TITLE
Using correct format of exceptions from JSON based APIs.

### PR DESCRIPTION
**Pull request by dhermes**
**NOTE**: Has #756 as diffbase. I'm happy to roll this into that PR if desired.

### CODE REVIEW

**Comment by tseaver** [comment]
I'm fine with the change.  Is there an API doc which specifies the errors?

**Comment by dhermes** [comment]
Reference: https://cloud.google.com/storage/docs/json_api/v1/status-codes#errorformat

**Comment by tseaver** [comment]
Ugh -- pubsub does not return JSON bodies for errors.

**Comment by dhermes** [comment]
Yeah it's strange. Hopefully Takashi has en explanation. Anyhow this change won't touch that since `use_json` will be `False`.

**Comment by dhermes** [comment]
Wishing GitHub had a web rebase method.

@tseaver feel free to peel off the last commit and send a new PR. You can even cherry pick my commit if you want me to feel good but it's not necessary.

**Comment by tseaver** [comment]
After merging and fixing conflicts, `tox -e lint` was failing with "too many branches" in `_unpack_batch_response`.  I split out a helper function, `_generate_faux_mime_message` from the first half, and called it from `_unpack_batch_response`.

**Comment by dhermes** [comment]
@tseaver FYI doing a non-rebase merge created duplicate commits.

For example:
https://github.com/GoogleCloudPlatform/gcloud-python/commit/fdb1d237ad30d4c0775ede1da04efc0ce4a81b95
https://github.com/GoogleCloudPlatform/gcloud-python/commit/1b94f9fa5a89fa0a1b72512c14dd908b90fa4891

**Comment by dhermes** [comment]
@tseaver If you don't mind I'd like to reset to 4785201d9b4368f705376e1ccd0547c991abf33b and then just re-send this PR. It's unclear which of the above-mentioned commits is actually in play, but rather than worry about it, I just want to get the duplicates out of history.

To check the commits from here and #756 I ran:

```
git log | grep 6cec5de
git log | grep 11904c3
git log | grep 1b94f9f
git log | grep fdb1d23
git log | grep 73bb5bb
git log | grep 4431588
```

**Comment by tseaver** [comment]
Go ahead.

**Comment by dhermes** [comment]
Thanks! Just `git push -f``ed, will merge #766 and then re-send a new PR for the changes in this one (plus your merge changes).

**Pull request merged**
