### PR TITLE
Returning ints from BigQuery Table.num_rows/num_bytes.

### PR DESCRIPTION
**Pull request by dhermes**
Also fixing `Table.expires` docstring typo.

### CODE REVIEW

**Comment by tseaver** [comment]
Do we need to add / update tests exercising the `int` conversion?

**Comment by dhermes** [comment]
Good call. I was peeling off my notes robotically and it didn't occur to me.

**Comment by dhermes** [comment]
@tseaver Rebased and added two tests. They are a bit over-loaded: in reality they each contain 4 itty bitty tests.

**Comment by tseaver** [comment]
LGTM

**Pull request merged**
