### PR TITLE
Adding versions page to docs.

### PR DESCRIPTION
**Pull request by dhermes**
Staging at http://dhermes.github.io/gcloud-python/versions

I wanted to make the left-hand `<nav>` be 100vh (view height) but can't seem to figure out how. Maybe this doesn't matter?

I will be following this up with a string template and `update_docs.sh` build step to regenerate the `versions.html` file when a new release is pushed.

### CODE REVIEW

**Comment by tseaver** [comment]
What is the expected ordering?  '0.4.1' < '0.4.0' < 'master' seems wrong.

**Comment by tseaver** [comment]
Other than that, LGTM

**Comment by dhermes** [comment]
The ordering is based on building (as in #662) top to bottom from left to right:

```python
    versions_list = '\n'.join([LI_TEMPLATE % (version, version)
                               for version in versions])
```

We want the latest to be at the top and want master to be "last". Did you have something else in mind?

This mirrors:
http://googlecloudplatform.github.io/gcloud-node/#/docs/history

**Comment by dhermes** [comment]
@tseaver Can I merge or shall we address your comment?

**Comment by tseaver** [comment]
I don't understand the ordering you spelled out (in my mind, `master` should sort "before" `0.4.1` if the versions are in descending order), but if it is deliberate (i.e., matches how other gcloud projects do it) then go ahead and merge.

**Comment by dhermes** [comment]
I think the logic is that the most relevant (latest) should be at the top and descending in order of relevance. `master` is not a relevant docset for most people since they will be using from actual releases, hence least relevant.

I'm open to different interpretation, but that seemed straightforward to me.

**Comment by dhermes** [comment]
@tseaver Thoughts?

**Comment by tseaver** [comment]
I don't feel strongly enough about it to block the merge, as long as the order is intentional.

**Pull request merged**
