### PR TITLE
Upgrading version to 0.11.0

### PR DESCRIPTION
**Pull request by jonparrott**
We need to cut this release ASAP because of #1570.

### CODE REVIEW

**Comment by dhermes** [comment]
LGTM

**Comment by jonparrott** [comment]
PRs in this release:

#1486
#1502
#1510
#1511
#1512
#1513
#1514
#1515
#1516
#1517
#1518
#1519
#1521
#1523
#1525
#1527
#1528
#1529
#1530
#1531
#1532
#1533
#1534
#1536
#1537
#1538
#1539
#1540
#1541
#1543
#1545
#1547
#1553
#1559
#1571

**Comment by tseaver** [comment]
Probably needs to be `0.11`, since we've updated our dependency pins.  I guess we won't be advertising any of the `Bigtable`/`Happybase` WIP, which would *definitely* require a version bump.

**Comment by jonparrott** [comment]
Fair enough, I'll bump to 0.11. @dhermes can decide how the bigtable changes should expressed in the release notes.

**Comment by jonparrott** [comment]
Release notes, PTAL

# Core
* Avoiding `protobuf` `3.0.0.b2.post1` #1571
* Allowing credentials that don't implement `create_scoped()`. #1510
* Removed `get_for_service_account_*` helpers. #1513
* Removing crypto code and relying on `oauth2client`. #1518
* Adding grpcio to setup.py as an extra #1553

# Datastore
* Updated datastore docstrings to use client pattern. #1517
* Removing demo code #1486

# Storage
* Reload missing blob properties before blob download #1559

# Bigtable

**Note**: The bigtable client implementation is not yet complete.

* HappyBase client implementation #1502 #1511 #1514 #1515 #1516 #1523 #1527 #1529 #1530 #1533 #1536 #1537 #1538 #1540 #1541 #1543
* Documenation #1521 #1545 #1547
* Upgrading gRPC to `0.13.0` #1532
* System tests #1512 #1519 #1525 #1528 #1531 #1534 #1539

**Comment by jonparrott** [comment]
Version changed to `0.11`. Waiting on Travis.

**Comment by tseaver** [comment]
I put the changelog entries all in the same (imperative) voice.

**Comment by jonparrott** [comment]
@tseaver I just copied the PR titles. Feel free to edit my comment and update as you see fit.

**Comment by tseaver** [comment]
We seem to be on the "slow bus" for Travis today.

**Comment by jonparrott** [comment]
`GoogleCloudPlaform` stays on it, and it'll only get worse as the DPE team finishes adding tests to our samples.

**Comment by jonparrott** [comment]
Actually this time it's the DataflowJavaSDK's fault for running a 30+ minute build. :(

**Comment by gtaylor** [comment]
As someone who enjoys both gcloud, Python, and Drone CI, I'll just leave this here: http://try.drone.io/

**Comment by jonparrott** [comment]
Travis is green. Merging.

**Comment by dhermes** [comment]
Thanks @gtaylor!

**Pull request merged**
