### PR TITLE
Move generate_signed_url to standalone function in credentials.

### PR DESCRIPTION
**Pull request by dhermes**
This was **very** out of place as a method on Connection in storage.

### CODE REVIEW

**Comment by tseaver** [comment]
I can hardly object:  this is basically the same as my #356, which was aimed at #57.

**Comment by dhermes** [comment]
Ha I vaguely remembered being a [party pooper][1] on that one.

I should have trusted your "this feels out of place" instincts.

This also brings up the question: How do GAE / GCE service accounts hope to sign a URL?

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/pull/356#issuecomment-62208000

**Comment by dhermes** [comment]
Also @tseaver is your endorsement above a LGTM or are you still reviewing?

**Comment by tseaver** [comment]
LGTM

**Pull request merged**
