### PR TITLE
Upgrading version to 0.9.0.

### PR DESCRIPTION
**Pull request by dhermes**

### CODE REVIEW

**Comment by dhermes** [comment]
Running

```
$ git log -1 --pretty=%H
2323e1a110d240545bf2950e18e5ccefb75d01f1
$ git log 0.8.0..HEAD \
> | grep 'Merge pull request ' \
> | awk -F ' ' '{print $4}' \
> | sort
```

yields

#1154
#1173
#1174
#1175
#1176
#1177
#1178
#1179
#1180
#1182
#1183
#1184
#1189
#1190
#1191
#1192
#1193
#1196
#1197
#1205
#1207
#1208
#1209
#1210
#1213
#1215
#1217
#1219
#1222
#1224
#1225
#1226
#1229
#1231
#1232
#1233
#1235
#1236
#1237
#1238
#1241
#1243
#1244
#1245
#1246
#1248
#1249
#1250
#1251
#1252
#1253
#1255
#1257
#1263
#1264
#1265
#1266
#1269
#1270
#1271
#1272
#1273
#1275
#1276
#1277
#1279
#1280
#1281
#1282
#1283
#1284
#1285
#1290
#1291
#1292
#1293
#1294
#1296
#1297
#1298
#1299
#1300
#1301
#1302
#1303
#1305
#1306
#1307
#1308
#1309
#1310
#1311
#1312
#1314
#1315
#1316
#1317
#1319
#1320
#1321
#1322
#1323
#1324
#1325
#1326
#1327
#1328
#1329
#1330
#1331
#1334
#1335
#1336
#1337
#1338
#1340
#1341
#1342
#1344
#1345
#1347
#1348
#1349
#1350
#1352
#1353
#1354
#1361
#1364
#1367
#1368
#1369
#1370
#1371
#1372
#1376
#1377
#1383
#1385
#1386
#1387
#1388
#1389
#1390
#1393
#1394
#1396
#1401
#1415

**Comment by dhermes** [comment]
Proposed release notes

----

## Datastore
-   Cursors use URL-safe base64 encoding instead of
    standard base64 encoding (#1180)
-   Bugfix: Allow `s~foo` to match `foo` in GET requests for keys (#1226)
-   Bugfix: Retain `meaning` for retrieved entities (#1241)
-   Prepare for `v1beta3`: #1205, #1293, #1294, #1296, #1297, #1299, #1301,
                           #1306, #1314, #1319, #1328, #1330, #1340, #1341
-   Breaking change: `Transaction.add_auto_id_entity` folded into
    `Transaction.put` (#1296)
-   Breaking change: Rename `Batch.mutation` to `mutations` (#1306)
-   Breaking change: Drop usage of `dataset_id` and instead refer to
    `project` (#1330, #1383)
-   Adding `exclude_from_indexes` and `meanings` to `Entity` equality
    check (#1347)
-   Making it impossible to use `Batch` more than once (once `begin` is
    called). This behavior was already present in `Transaction`, which
    inherits from `Batch`. (#1367)
-   Retro-fitting system tests to run against the datastore
    emulator (#1369, #1386, #1393, #1401)
-   Updating system tests to be isolated and avoid problems
    with concurrent runs of the same test (#1370, #1372)
-   Docs fixes (#1352)

## Pub/Sub
-   Bugfix: Send `ackDeadlineSeconds` instead of `ackDeadline`
    in API requests (#1182)
-   Docs fixes (#1197, #1215, #1292, #1334)
-   Add support for running local test against the emulator (#1344, #1371)
-   Updating system tests to be isolated and avoid problems
    with concurrent runs of the same test (#1376)
-   Retro-fitting system tests to run against the pubsub
    emulator (#1396)

## Storage
-   Allow setting `Bucket.storage_class` (#1213)
-   Adding `ACL.save_predefined` method (#1217)

## BigQuery
-   Bugfix: Allow for missing `mode` in retrieved tables (#1219)
-   Docs fixes (#1243, #1263, #1280, #1281, #1394)
-   Bugfix: Sending BigQuery timestamps as seconds rather than
    milliseconds (#1250)
-   Converting `Table.num_bytes|num_rows` properties to integers (#1252)
-   Large PR (#1279)
-   Large PR (#1282)
-   `Client.list_jobs` uses `projection=full` (#1311)
-   Allow for `sourceUris` to be missing in load job config. (#1312)
-   Update parsing of access grant to explicitly check for a single
    role. Also adding support for `domain` and `view` roles (#1377)

## DNS
-   Bugfix: DNS zone `creationTime` is RFC 3339 formatted rather
    than milliseconds since the epoch (#1368)

## Search API
-   #1173
-   #1177
-   #1178
-   #1179
-   #1183
-   #1184

## Core
-   Default project (used by all services except `datastore`) now also
    checks for GAE and GCE projects (#1331)
-   Dropping `PyCrypto` dependency and switching to `pyOpenSSL` (#1338)
-   Dropping use of bash shell in testing utilities so testing is
    better on other platforms (e.g. Windows) (#1222, #1231, #1348, #1349)
-   Dropping Py33 support, adding Py35. (#1415)
-   Docs fixes (#1345)

----

PRs left out of the notes:

- gRPC/Bigtable - #1154, #1224, #1225, #1229, #1233, #1235, #1238, #1244, #1245, #1246, #1253, #1257, #1264, #1265, #1266, #1269, #1270, #1271, #1272, #1273, #1275, #1276, #1277, #1283, #1284, #1290, #1291, #1298, #1300, #1302, #1303, #1305, #1307, #1308, #1309, #1310, #1316, #1317, #1320, #1321, #1322, #1323, #1324, #1325, #1326, #1327, #1329, #1335, #1342, #1354, #1361, #1387, #1388, #1389, #1390
- Project Admin Stuff - #1174, #1175, #1176, #1236, #1237, #1248, #1251, #1255, #1285, #1315, #1336, #1337, #1350, #1353, #1364, #1385
- `apitools` move - #1189, #1190, #1191, #1192, #1193, #1196, #1207, #1208, #1209, #1210, #1232, #1249

**Comment by dhermes** [comment]
We should #1421 in before merging this (and maybe some of the other pending PRs)?

**Comment by tseaver** [comment]
@dhermes I updated the release notes with my own OCD (imperative voice).

**Comment by dhermes** [comment]
@tseaver Thanks. Can you expound on the Search API section and double check that none of the left out PRs should be in the release notes?

**Comment by tseaver** [comment]
> Can you expound on the Search API section

We didn't have (or at least advertise) any support at all for the Search API previously:  do we need to detail how it was built?

> and double check that none of the left out PRs should be in the release notes?

Done.

**Comment by dhermes** [comment]
It's your call. The PR descriptions weren't easy to turn into bullets, so I figured as the author you'd have an easier time doing that / deciding what needed to be said.

**Comment by tseaver** [comment]
Given that the change vs. 0.8 is the entire `gcloud.search` subpackage, I don't see any point in spelling it out furhter than "Initial release of Search API support." w/ the PR numbers.

**Comment by dhermes** [comment]
Works for me.

**Comment by dhermes** [comment]
Since the original list, some newly merged PRs.

#1400
#1403
#1404
#1409
#1417
#1421
#1425

Will update the description as well.

**Comment by tseaver** [comment]
I added #1421 and #1425 yesterday.

**Comment by dhermes** [comment]
Just noticed, sorry.

**Comment by dhermes** [comment]
Also added #1413

**Comment by dhermes** [comment]
@tseaver Any issues cutting this release? Did you want to get #1318 in before we cut a release?

**Comment by dhermes** [comment]
Also added #1427

**Comment by tseaver** [comment]
> Did you want to get #1318 in before we cut a release?

Would be nice, but I'm not gonna get the refactoring done (the commonality between `Blob.load_from_file` and `Table.load_from_file`) this afternoon.  I guess we could merge as is with an issue to clean it up.

**Comment by dhermes** [comment]
:+1:

**Comment by dhermes** [comment]
Let me do a final pass before merging, will you file the issue to follow up?

**Comment by tseaver** [comment]
#1318 merged, #1431 filed (I updated the release notes).

**Comment by dhermes** [comment]
All right let's cut a release!

**Comment by tseaver** [comment]
You just merged #1422:  it needs changelog?

**Comment by dhermes** [comment]
Naw, merged into `grpc-logging-feature` branch (though it should've been noted in this PR, so thanks for doing it)

**Pull request merged**
