### PR TITLE
Adding landing page to look like gcloud-node.

### LINKED ISSUE #614: Update gh-pages landing page to look like gcloud-node
Landing page (for reference) is here: http://googlecloudplatform.github.io/gcloud-node/#/

### PR DESCRIPTION
**Pull request by dhermes**
Fixes #614.

@jgeewax PTAL

http://dhermes.github.io/gcloud-python/ (will redirect to blog.bossylobster.com because of the CNAME on dhermes.github.io)

Some things I had to do:
- Convert the SVG logo from white (#FFFFFF) to dark gray (#5D6061). This color is [used][2] in node
- Port the partial HTML for [home][1] and then hack around until it worked
- Ditched the code snippet (highlighting was done via AngularJS)
- Put main page resources in their own static folder

I worry that this will continue to be out of sync with `gcloud-node` (our CSS is already pretty far behind) and I don't know who can step up and take that mantle. (It was %100 @silvolu before.)

[1]: https://github.com/GoogleCloudPlatform/gcloud-node/blob/fd8067377294cb648cda7fdbf75e4d852572252e/home.html
[2]: https://raw.githubusercontent.com/GoogleCloudPlatform/gcloud-node/fd8067377294cb648cda7fdbf75e4d852572252e/site/img/icon-lang-nodejs.svg

### CODE REVIEW

**Comment by jgeewax** [comment]
:+1: on how it looks :)

And we can eventually bring in a designer to clean things up when they get out of sync....

**Comment by dhermes** [comment]
I like that approach. Is that an LGTM? Shall I merge? (If this HTML / CSS / JS dependency mess were Python, I would have an opinion. But the web is more freeform and I am not opinionated about what is "right" here.)

**Comment by jgeewax** [comment]
It LGTM, maybe we should ask one of the gcloud-node guys to take a ... quick look? @ryanseys @stephenplusplus ?

**Comment by ryanseys** [comment]
LGTM.

**Comment by dhermes** [comment]
w00t http://googlecloudplatform.github.io/gcloud-python/

Now on to implementing
http://googlecloudplatform.github.io/gcloud-python/versions

**Comment by tseaver** [comment]
Belated LGTM, too. :)

**Comment by dhermes** [comment]
Thanks @tseaver

**Pull request merged**
