### PR TITLE
Harden pubsub client against keys omitted in back-end responses

### PR DESCRIPTION
**Pull request by tseaver**
See #1439.

### CODE REVIEW

**Comment by dhermes** [comment]
LGTM.

Worth adding to system tests?

**Comment by tseaver** [comment]
> Worth adding to system tests?

I'm not sure how to provoke it, given that an account might have an existing topic / subscription.

**Comment by dhermes** [comment]
Well we could do this for checking subscriptions on the topics we create, right?

**Comment by tseaver** [comment]
@dhermes PTAL at e6616ca.

**Comment by dhermes** [comment]
LGTM (feel free to merge before AppVeyor finishes)

**Pull request merged**
