### PR TITLE
Updated padding of code snippet on landing page.

### PR DESCRIPTION
**Pull request by jgeewax**
Adds more padding around the code snippet on the landing page.

### CODE REVIEW

**Comment by tseaver** [comment]
LGTM.  Verified by toggling the styles w/ "Inspect this element" on the live docs.

**Comment by dhermes** [comment]
@jgeewax FYI typically the person filing the PR does the merge (I'm not sure if this is typical on all of GitHub, but it is in our project). I figured I'd merge as this has been sitting for a few days.

**Comment by jgeewax** [comment]
Gotcha -- so even external contributors would do their own merging ?

**Comment by dhermes** [comment]
It hasn't come up yet, but GitHub only allows project members to merge (as I've seen with `oauth2client`) so in those cases it'd have to be one of us.

I don't know if there is a typical approach on GitHub?

**Comment by jgeewax** [comment]
OK that makes sense -- outsiders would need you guys to merge. Any objection to treating my PR as you would an outsider ?

**Comment by dhermes** [comment]
Fine with me (assuming you send more PRs in the future)

**Pull request merged**
