### PR TITLE
Implementing `topic.subscription` factory.

### LINKED ISSUE #912: Get a subscription from a topic
In pubsub-usage.rst we have:

```python
client = pubsub.Client()
topic = client.topic('topic-name')
sub = pubsub.Subscription('sub-name', topic)
```

I think we should consider changing this to

```python
client = pubsub.Client()
topic = client.topic('topic-name')
sub = topic.subscription('sub-name')
```

### LINKED ISSUE #929: Implement Topic.subscription factory
See #910

I tried to implement in 1f80e368d45da5036e4f753d25f48a47fd758160 but was not able to make the `pylint` god happy about the cyclic import.

### PR DESCRIPTION
**Pull request by dhermes**
Also using `topic.subscription` factory in docs and regression
tests instead of instantiating a `Subscription`.

Fixes #912.

### CODE REVIEW

**Comment by dhermes** [comment]
@jgeewax @tseaver We should discuss the cyclic import and how to address.

**Comment by dhermes** [comment]
@tseaver WDYT of the import cycle issue?

**Comment by tseaver** [comment]
It is kind of intractable.  One notion would be to indirect through `self.topic.client.topic()` (assuming that works, of course).

**Comment by dhermes** [comment]
Fun. A Pylint [bug][1] for this has been open since August 2013.

[1]: https://bitbucket.org/logilab/pylint/issue/61/impossible-to-disable-r0401-with-comments

**Comment by dhermes** [comment]
@tseaver RE: Your suggestion, the issue is that there is no `self`; the dependency is needed in a `classmethod`.

**Comment by dhermes** [comment]
Ahhh but `client` is available! w00t. @tseaver saves the day (I hope)

**Comment by dhermes** [comment]
@tseaver All better now, PTAL.

**Comment by tseaver** [comment]
LGTM

**Pull request merged**
