### PR TITLE
Add Sphinx as a dependency for linting

### PR DESCRIPTION
**Pull request by daspecster**
First seen https://github.com/GoogleCloudPlatform/gcloud-python/pull/1946#issuecomment-234667091

screen shot 2016-07-22 at 6 10 03 pm

Not sure how this got through?

### CODE REVIEW

**Comment by waprin** [comment]
lgtm

**Comment by dhermes** [comment]
I am :-1: on the quick merge without a more in-depth investigation. I'm pretty sure this snuck in because our `[pep8]` settings aren't getting picked up after the switch to `pycodestyle`

**Comment by daspecster** [comment]
Sorry, I can revert. I looked and the offending line is https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/scripts/verify_included_modules.py#L119

**Comment by waprin** [comment]
Also sorry if you think it was too hasty but it did fix my PR.

**Comment by daspecster** [comment]
Also, by `[pep8]` settings you're referring to in the tox.ini (https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/tox.ini#L144). Switching it to `[pycodestyle]` produces a bunch of errors like it's not picking it up for some reason.

Might be a pycodestyle bug? I tried it before when I did the pep8->pycodestyle conversion and it broke then too.

**Comment by daspecster** [comment]
We can talk more here https://github.com/GoogleCloudPlatform/gcloud-python/pull/2020

**Comment by tseaver** [comment]
That is a failure in pylint, not pycodestyle:  it is trying to check `docs/conf.py`.  Lets just exclude that file from pylint.

**Comment by daspecster** [comment]
@tseaver thanks! Here we go https://github.com/GoogleCloudPlatform/gcloud-python/pull/2021.

**Pull request merged**
