### PR TITLE
Document URI format for loading/extracting Cloud Storage objects.

### LINKED ISSUE #1267: Document format for Cloud Storage URIs used in BigQuery
BigQuery APIs which load table data from (or extract it to) Cloud Storage blobs take URIs of the format, `gs://<bucket-name>/<object-name-or-glob>`.  Ensure that the docstrings for those methods document the expected URI format.

### PR DESCRIPTION
**Pull request by tseaver**
Closes #1267.

### CODE REVIEW

**Comment by dhermes** [comment]
LGTM

**Comment by tseaver** [comment]
Rebased to fix conflicts.  I will merge once Travis passes.

**Comment by dhermes** [comment]
@tseaver Merged for you :grinning:

**Comment by tseaver** [comment]
Thanks!

**Pull request merged**
