### PR TITLE
Removing cover-min-percentage=100 from coveralls.

### LINKED ISSUE #939: Failed coverage doesn't get sent to coveralls.io
It seems` --cover-min-percentage=100` causes` tox -e coveralls` to fail before uploading to coveralls.io

H/T to #933

### PR DESCRIPTION
**Pull request by dhermes**
Fixes #939.

### CODE REVIEW

**Comment by tseaver** [comment]
We dropped running `tox -e cover` in the "main" tests in Travis, which would block the `tox -e coveralls` bit (in `after_success`).  Is a drop in coverage still going to show up as a failed check?

**Comment by dhermes** [comment]
@tseaver The `coverage/coveralls` check will fail but the `continuous-integration/travis-ci/pr` check will not. Is that sufficient?

**Comment by dhermes** [comment]
I can add a fake PR after this for us to test. Something silly like

```
if False:
    print 'I will never happen'  # Maybe though because False is just a variable
```

**Comment by tseaver** [comment]
If we're sure that PRs will show up with failed checks, then go ahead. I don't really see the value-add of coveralls is over just running `tox -e cover` within Travis, but if we're going to use it, we should definitely let it work as expected.

**Comment by dhermes** [comment]
We use `coveralls` for the fancy badge on the front page. `cover` is in the default list, so running `tox` locally will run `tox -e cover`.

I'm taking your "go ahead" as an LGTM. Happy to rollback if I misunderstood.

**Pull request merged**
