### PR TITLE
Wait even longer for orphan's topic to be None.

### PR DESCRIPTION
**Pull request by tseaver**
Toward #2080.

### CODE REVIEW

**Comment by tseaver** [comment]
@daspecster, @dhermes I plan to merge this one-digit diff as soon as Travis is green, trying to get the build passing w/ both system test runs.

**Comment by daspecster** [comment]
Instead of 8 tries would it work better to increase the wait time/delay?  I'm just thinking of quotas but we probably have a really high quota for this.

**Comment by daspecster** [comment]
Either way LGTM if it works for master! 🎉

**Comment by tseaver** [comment]
@daspecster We aren't seeing quota-based failures:  it just takes longer than expected for the deletion of the topic to show up when reloading the orphaned subscription.

**Comment by dhermes** [comment]
LGTM as well

**Pull request merged**
