### PR TITLE
Begin pubsub regression suite

### PR DESCRIPTION
**Pull request by tseaver**
Uses #764 as a base.

### CODE REVIEW

**Comment by dhermes** [comment]
Got a lot of unused variables (I assume build failed). Also the do nothing setup and `teardownModule` aren't needed.

Other questions
- Why the URI changes?
- Do you plan on implementing more in this PR?

(Sorry for hacky review. On phone.)

**Comment by tseaver** [comment]
I rebased to remove #764 and adjust the tests to accommodate the changed URIs.

Per the [API docs](https://cloud.google.com/pubsub/reference/rest/), the URIs are all based at https://pubsub.googleapis.com/v1beta2, rather than https://www.googleapis.com/pubsub/v1beta1.  I know they are right because the regression tests were all 404ing with non-JSON errors before. :)

**Comment by tseaver** [comment]
I plan to add more tests in later PRs (e.g., once we decide about returning `Topic` instances from `pubsub.api.list_topics()`).

**Comment by dhermes** [comment]
Still have unused vars `HTTP` and `SHARED_BUCKETS` and an unused import `httplib2`.

Just call me the human linter :)

Other than LGTM (if you don't don't can you squash these fixed into the original commit, 4 commits for tint change is sadness)

**Comment by tseaver** [comment]
@dhermes I removed those variables and the import, and squashed it down to two commits.

**Comment by dhermes** [comment]
Looks great thanks

**Pull request merged**
