### PR TITLE
Adding link to gcloud-java from landing page

### PR DESCRIPTION
**Pull request by ajkannan**
This pull request adds a link to gcloud-java in the landing page dropdown menu in the upper left hand corner.

### CODE REVIEW

**Comment by dhermes** [comment]
LGTM. Can you also submit one against https://github.com/GoogleCloudPlatform/gcloud-python/blob/b3ee1491d0e55a41087c53f5f1d41e0bd7785a3c/docs/_templates/layout.html in `master`? (I can do it if you'd like as well.)

**Comment by ajkannan** [comment]
Sure, I can do that

**Comment by dhermes** [comment]
Thanks. It's my / our bad for not having one true place for that HTML.

**Comment by ajkannan** [comment]
Oh, before I make that change, gcloud-java doesn't use the same template for the docs pages.  Instead we use the javadoc template (see http://googlecloudplatform.github.io/gcloud-java/site/0.0.7/apidocs/index.html).  Would it be alright if the link in docs/_templates/layout.html linked that?

**Comment by dhermes** [comment]
Use whichever link you think is appropriate. @jgeewax Can sign off if you think it needs a second set of eyes.

**Comment by jgeewax** [comment]
For now, I'd rather link to the landing page if that's OK...

Quite a few people wanted to see "what each language offers", and if we send people into the Javadocs, they lose their language switcher drop-down. Is that cool?

**Pull request merged**
