### PR TITLE
Upgrading Makefile to generate datastore v1beta3.

### PR DESCRIPTION
**Pull request by dhermes**
Also
- Removing `v1beta2` generated code and `.proto` file
- Adding new `.proto` files and generated code
- Adding `make_datastore_grpc.py` script to tear out the `protoc` inserted lines by the gRPC plugin
- Updating `rewrite_imports.py` to rewrite the datastore imports

----

Was #1355 but has been re-purposed to merge against the `datastore-v1beta3` branch

### CODE REVIEW

**Comment by dhermes** [comment]
@tseaver PTAL

**Comment by jonparrott** [comment]
This LGTM with small nits.

**Comment by dhermes** [comment]
@jonparrott PTAL.

**Comment by jonparrott** [comment]
LGTM.

**Pull request merged**
