### PR TITLE
Updating Bigtable generated files.

### PR DESCRIPTION
**Pull request by dhermes**

### CODE REVIEW

**Comment by tseaver** [comment]
Are the `.proto` files generated?  Or are we just copying them into the `_generated` package for clarity?

Also, do we have the process for re-generating these files documented?

**Comment by dhermes** [comment]
1. The `.proto` files are copied from https://github.com/GoogleCloudPlatform/cloud-bigtable-client
1. Coping the `.proto` files is there for clarity / as a reference for the relevant concepts. IIRC it was your original encouragement (for `datastore`) that led us to start including them.
1. They are generated via `make generate`

**Comment by tseaver** [comment]
> They are generated via make generate

At one point, I wanted to work on the `Makefile`, but couldn't figure out how to reproduce the environment it expected.

**Comment by dhermes** [comment]
Yeah it relies on gRPC being easy to install, which is not quite there yet. And AFAIK there is no good way to get the `grpc_python_plugin` without building from source.

**Comment by tseaver** [comment]
I opened #1482 to track the build-from-protos issue.  LGTM.

**Pull request merged**
