### PR TITLE
Moving Bigtable Row.commit_modifications() into commit().

### LINKED ISSUE #1548: Find a better name for Row.commit_modifications() or fold the behavior into
See discussion in #1547 for context.

The name `modifications` is intended to map to the RPC method name `ReadModifyWriteRow` but the word modification is a synonym of mutation, so this method is poorly named. The method actually sends changes that

- increment an int (stored in BT as 8 bytes)
- append bytes to a cell value

so we should either

- Fold it into `Row.commit()` as `commit(append_only=True)`
- Rename it to something like `Row.commit_cell_updates` (or a better name than that)

### PR DESCRIPTION
**Pull request by dhermes**
Fixes #1548.

### CODE REVIEW

**Comment by dhermes** [comment]
@jgeewax @jonparrott LMK what you guys think of this

**Comment by jonparrott** [comment]
This seems pretty reasonable in terms of the API surface/usage.

**Comment by dhermes** [comment]
:+1:

**Comment by dhermes** [comment]
I think I should update `bigtable-data-api.rst` as well

**Comment by tseaver** [comment]
Now that I see the change, it feels like there should really be two different row classes in play, rather than having methods which are present, but only available based on the value of `append`.

**Comment by jonparrott** [comment]
> Now that I see the change, it feels like there should really be two different row classes in play, rather than having methods which are present, but only available based on the value of append.

I'm somewhat leaning towards this as well. Row seems to have significant variadic behavior based on one argument.

**Comment by dhermes** [comment]
Two classes or three? There are three distinct cases here. Also, do users **want** three?

The worst / grossest "variadic"-ness to me is in the output of `commit()`.

**Comment by dhermes** [comment]
@tseaver @jonparrott Bump (want to get a release out ASAP so this PR can't block too long).

Two questions:

- Two or three row classes? (3 implicit types, "direct", "conditional" and "append")
- Would users blanch at having to use 3 separate classes? Could we sufficiently ease this pain with the `Table.row()` factory?

Also @jgeewax Please weigh in.

**Comment by tseaver** [comment]
Three classes, I think:  the `Table.row()` factory could figure out which one to instantiate, based on the params passed?

**Comment by jonparrott** [comment]
>  the Table.row() factory could figure out which one to instantiate, based on the params passed?

Agreed.

**Comment by dhermes** [comment]
Working on it now.

**Comment by dhermes** [comment]
This can definitely be dropped since #1557 and others covered it.

**Pull request closed without merging**
