### PR TITLE
Handling datastore renames on Query and QueryResultBatch.

### PR DESCRIPTION
**Pull request by dhermes**
Was #1357

### CODE REVIEW

**Comment by jonparrott** [comment]
LGTM

**Comment by dhermes** [comment]
@jonparrott You're going through these faster than I can cook 'em!

**Comment by jonparrott** [comment]
These are just renames. I'm mostly just checking for typos. We'll have a nice, big review to do when we merge this branch into master.

**Comment by dhermes** [comment]
Haha yup. I am doing `git merge master` periodically to make sure the branch is up to date.

**Pull request merged**
