### PR TITLE
Prepare 0.17.0 release.

### PR DESCRIPTION
**Pull request by tseaver**
After merging #1932.  Other PRs on `master`:

```bash
$ git log -1 --pretty=%H
1a2fa6cb61e3eb3079af19879d7403baa899e6ca
$ git log 0.16.0..HEAD | grep 'Merge pull request ' |  awk -F ' ' '{print $4}' | sort
```

yields

#1877
#1878
#1880
#1882
#1884
#1887
#1888
#1892
#1894
#1900
#1901
#1902
#1903
#1905
#1907
#1908
#1910
#1912
#1913
#1915
#1916
#1919
#1923
#1924
#1925
#1926
#1930
#1931
#1932
#1938
#1941

### CODE REVIEW

**Comment by tseaver** [comment]
Draft release notes.

## 0.17.0

### Core

- Disable building wheels on Travis. (#1938)

### Docs

- Adjust anchor scroll in docs to show actual line. (#1900)
- Add logging example to `README.md`. (#1901)
- Add BigQuery example to `README.md`. (#1902)
- Expand loggging usage docs to show exports via sinks. (#1905)
-  Fix `LICENSE` to match [canonical example](http://www.apache.org/licenses/LICENSE-2.0.txt). (#1916) 

### Storage

- Fix `ImportError` when attempting to read user's `gcloud` configuration on GAE. (#1924)

### Logging

- Add optional gRPC support, enabled via the `GCLOUD_ENABLE_GAX` environment variable (#1880, #1884, #1887, #1888, #1892, #1894).

### Bigtable

- Add support for V2 protos, API endpoints. (#1903, #1907, #1908, #1912, #1913, #1915, #1919, #1923, #1925, #1926, #1930, #1931, #1932)

**Comment by dhermes** [comment]
Mentioning wheels doesn't seem necessary in release (or at least mentioning Travis not necessary, but maybe adding that we won't have wheels on PyPI)

**Comment by tseaver** [comment]
@dhermes I updated the note for wheels.

**Comment by daspecster** [comment]
```bash
git log -1 --pretty=%H
7f6540275d7d241f4bf11f9c63d9777e05868561
```
for me after #1941.

**Comment by tswast** [comment]
Is this 0.16.1 on PyPi or will 0.17.0 sync soon? https://pypi.python.org/pypi/gcloud

**Comment by daspecster** [comment]
Once the merged build is done it should show up on pypi.

On Wednesday, June 29, 2016, Tim Swast <notifications@github.com> wrote:

> Is this 0.16.1 on PyPi or will 0.17.0 sync soon?
> https://pypi.python.org/pypi/gcloud
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/GoogleCloudPlatform/gcloud-python/pull/1940#issuecomment-229510762>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AALvyHsrlhOy_BoiGEKhkZlwKGbfDVigks5qQvRQgaJpZM4JBgZk>
> .
>


-- 
Tom Schultz

**Comment by tseaver** [comment]
We have burned a lot of cycles at Travis today:  likely they've QoS'ed us into the slow lane. :(

**Comment by tseaver** [comment]
@tswast 0.16.1 was a "brown bag" release, to fix people affected by our broken wheel uploaded with 0.16.0.

**Pull request merged**
