### PR TITLE
Add system test for 'Metric.update'.

### PR DESCRIPTION
**Pull request by tseaver**
~~Uses #1612 as a base.~~

### CODE REVIEW

**Comment by dhermes** [comment]
LGTM pending a rebase.

**Comment by tseaver** [comment]
@dhermes Rebased after merging #1612.  Unless you object, I will merge as soon as Travis passes.

**Comment by dhermes** [comment]
LGTM still valid

**Comment by tseaver** [comment]
Dunno why Travis is not re-running after the rebase.

**Pull request merged**
