### PR TITLE
Upgrading version to 0.7.1.

### PR DESCRIPTION
**Pull request by dhermes**
@tseaver Are we close enough on BQ to release this?

### CODE REVIEW

**Comment by dhermes** [comment]
Running

```
$ git log 0.7.0..cut-0.7.1 \
> | grep 'Merge pull request ' \
> | awk -F ' ' '{print $4}' \
> | sort
```

yields

#1000
#1001
#1002
#1003
#1004
#1005
#1006
#1008
#1010
#1014
#1015
#1016
#1017
#1018
#1019
#1020
#1021
#1022
#1023
#1025
#1026
#1029
#1032
#1033
#1035
#1036
#1038
#1039
#1040
#1042
#1044
#1045
#1046
#1051
#1052
#1053

**Comment by dhermes** [comment]
@tseaver Can you write the BQ part?

```
## Storage

-   Removing `Bucket.upload*` methods (#1002). Uploads should now
    happen exclusively on `Blob`s.
-   Adding factories: `Client.bucket`, `Client.batch` and
    `Bucket.blob` (#1005)
-   Moving `Blob.rename()` to `Bucket.rename_blob()` (#1052).

## Datastore

-   Making `Iterator` docstring more useful (#1006).
-   Fixing the broken demo (#1053).

## BigQuery

-   Newly added! (#1017, #1018, #1021, #1022, #1023, #1038, #1045, #1046)

## General

-   Moving all environment variables used in `gcloud.environment_vars`
    module. (#1010)
-   Updating docs (#1025) to [work][1] on readthedocs.org.
-   Renamed `lastest --> stable` and `master --> latest` docsets to match the
    readthedocs.org naming conventions and to use names that actually
    indicate what each docset is (#1026).
-   Adding optional UTC class to avoid requiring `pytz` (#1044).

[1]: http://gcloud-python.readthedocs.org/
```

**Comment by tseaver** [comment]
@dhermes I uppdated the description:

- Convert to Github-compatible markdown (no line breaks in bullets).
- Use imperative voice (a bugaboo of mine).
- Add description of partial BQ support.

**Comment by tseaver** [comment]
LGTM

**Comment by dhermes** [comment]
@tseaver Should I merge this now? If I merge anything else, then we'll need to update the description further.

**Comment by dhermes** [comment]
I'll just merge it and we can deal with clean-up (e.g. more BQ stuff) if need be.

**Comment by tseaver** [comment]
No worries.

**Comment by dhermes** [comment]
Yay!

https://github.com/GoogleCloudPlatform/gcloud-python/releases/tag/0.7.1
http://gcloud-python.readthedocs.org/en/stable/ (finally rendered correctly)
http://gcloud-python.readthedocs.org/en/0.7.1/

It seems the deploy to PyPI may have failed:
https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/75333223

**Comment by dhermes** [comment]
There is an error `sh: 1: twine: not found` where [before][1] we've seen

```
Submitting dist/gcloud-0.7.0.tar.gz to http://pypi.python.org/pypi
Server response (200): OK
```

[1]: https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/71984311

**Comment by dhermes** [comment]
Issue exists: travis-ci/dpl#299

**Comment by dhermes** [comment]
I manually uploaded via:

```bash
python setup.py sdist bdist upload
```

However I shouldn't have included `bdist` so went and deleted the file after the fact.

Now at:  https://pypi.python.org/pypi/gcloud/0.7.1

**Pull request merged**
