### PR TITLE
Adding Bigtable Cell class.

### PR DESCRIPTION
**Pull request by dhermes**
Used to hold data in rows retrieved.

@tseaver This module could definitely use some design review (none of the content here yet, but worth discussing now or at least thinking about).

Right now, the implementation is as follows:
- Rows are read from a `Table` (and a `Cell` is like a "column" in a row, so there can be many), so the helpers needed to parse a row that was read are in `row_data.py`
- Mutations (in rows) are created directly on a `Row`, and this is all done in `row.py` (all code submitted or merged)

### CODE REVIEW

**Comment by tseaver** [comment]
Travis failed on the docs build:

```
Found undocumented public modules:

- gcloud.bigtable.row_data

ERROR: InvocationError: '/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/docs/bin/python /home/travis/build/GoogleCloudPlatform/gcloud-python/scripts/verify_included_modules.py'
```

**Comment by tseaver** [comment]
No explicit tests for the `Cell` class' methods?

**Comment by dhermes** [comment]
Double fail. Sorry, forgot to stage it. Must've been in a hurry.

**Comment by dhermes** [comment]
@tseaver PTAL.

Still would like to know what you think about having `row.py` and `row_data.py` separately.

**Comment by tseaver** [comment]
> Still would like to know what you think about having row.py and row_data.py separately.

My only quibble is with the filename:  given that the module just contains the `Cell` class, ISTM that it would most logically be named `gcloud.bigtable.cell`.

**Comment by dhermes** [comment]
`Cell` is just the beginning:
https://github.com/dhermes/gcloud-python-bigtable/blob/master/gcloud_bigtable/row_data.py

**Comment by tseaver** [comment]
> Cell is just the beginning:

SGTM

**Comment by dhermes** [comment]
And the content of this commit?

**Comment by tseaver** [comment]
Fine to merge.

**Pull request merged**
