### PR TITLE
Removing cover.sh and folding into tox config.

### PR DESCRIPTION
**Pull request by dhermes**
This is to make the tox config friendlier to Windows and other non-bash shells.

Towards #1123.

### CODE REVIEW

**Comment by tseaver** [comment]
Stray `bigtable` changes unrelated to the commit message.

**Comment by dhermes** [comment]
That's scary. I wonder how that happened? Thanks. I'll ping once removed.

**Comment by tseaver** [comment]
The two other changes (removing `cover.sh` and updating `tox.ini`) LGTM.

**Comment by dhermes** [comment]
Stripped out the stray changes. (I'm hoping I just did `git checkout -b remove-bash-cover` from the wrong branch by mistake, though it's strange it was folded into one commit.)

Will merge on Travis.

**Pull request merged**
