### PR TITLE
Disable broken wheel building

### PR DESCRIPTION
**Pull request by tseaver**
See: https://github.com/GoogleCloudPlatform/gcloud-python/issues/1879#issuecomment-229444782

### CODE REVIEW

**Comment by dhermes** [comment]
LGTM (didn't this already get merged?)

**Comment by tseaver** [comment]
@dhermes I merged it to the `release-0.16.1` branch:  this PR is for `master`.

**Comment by dhermes** [comment]
@tseaver We want this back ASAP (once the `if` statement is out of `setup.py`, le sigh). What will force our hand to revert this PR?

**Comment by daspecster** [comment]
We could make an issue/reminder kind of like @tseaver did for #1873.

**Comment by tseaver** [comment]
@daspecster done:  #1939.

**Pull request merged**
