### PR TITLE
Adding Pub/Sub docs and JS to dedent for the section header.

### PR DESCRIPTION
**Pull request by dhermes**
Also removing tabs from `docs/_static/js/main.js`

@tseaver Do we want to leave the doc you wrote in place? Certain things in there like `# API request` need to be cleaned up if it's going to be permanent.

### CODE REVIEW

**Comment by tseaver** [comment]
Maybe the document should be renamed to `docs/pubsub-surface.rst` (following your lead in 

I think highlighting exactly where an API request occurs is useful, in the spirit of #545 / #632.

**Comment by dhermes** [comment]
@tseaver I rebased over the original with the `docs/pubsub-usage.rst` -> `docs/pubsub-surface.rst` rename.

As for the `docs/pubsub-surface.rst` doc itself, I haven't done a full pass. I seem to remember during #691 or #742 that we discussed the doc wasn't necessarily intended to be published, just for discussion. (I can't find those comments just now, but only quickly scanned the PRs.)

Anyhow, we can punt on that outside of this PR, but I need to do a second pass of `docs/pubsub-surface.rst` and I think you should too.

**Comment by dhermes** [comment]
@tseaver Any remaining issues?

**Comment by tseaver** [comment]
LGTM

**Pull request merged**
