### PR TITLE
Removing hacks that avoid using project ID in key protos.

### LINKED ISSUE #821: Remove datastore.key._dataset_ids_equal and just use string equality check
See #528 for some history here.

The issue is that requests made using `foo` instead of `s~foo` fail in [strange ways](https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/59).

So as a result we have to use `datastore.helpers._prepare_key_for_request` to strip dataset IDs from keys that get sent to the server. This has accidental caused bugs in the past (e.g. allowing keys from a different dataset `bar` to be inserted into dataset `foo`)

### PR DESCRIPTION
**Pull request by dhermes**
This was because returned dataset IDs in `v1beta2` turned `foo` into `s~foo` and sometimes this caused mismatches.

@pcostell Do we still need `foo` and `s~foo` to be considered "equal" in `v1beta3`?

I held off on removing the custom `_projects_equal`, which is used in `Key.__eq__`, `Batch.put`, `Batch.delete` and `Client.get_multi`. However, by making `_projects_equal` just check `project1 == project2` the system tests pass just fine. (This would fix #821)

### CODE REVIEW

**Comment by jonparrott** [comment]
LGTM pending @pcostell, unless you want to remove `_projects_equal` in another PR.

**Comment by pcostell** [comment]
Correct, the project_id will never contain cluster info. From our [release notes](cloud.google.com/datastore/v1beta3/release-notes) (current hidden behind a whitelist):

> Field dataset_id is now project_id. project_id never includes the app/project ID "prefix" (e.g. "s~"). This fixes https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/59.

**Comment by dhermes** [comment]
Thanks @pcostell! I confirmed by trying to send `s~` and just watching it fail (which is good).

I noticed some extra bytes in the error

```
'\x08\x05\x121The project s~omega-moonlight-697 does not exist.'
```

It seems the error is type `DebugInfo` (available in `google/rpc/error_details`). Is there some documentation somewhere which describes the errors? AFAIK the error message bodies in `v1beta2` are all plain text.

**Comment by dhermes** [comment]
@jonparrott PTAL. I added another commit to remove the prefix checking. I **love** deleting code.

**Comment by jonparrott** [comment]
LGTM. I love watching you delete code.

(There is a surprisingly large amount of code for handling Datastore)

**Comment by pcostell** [comment]
The error is documented [here][https://cloud.google.com/datastore/v1beta3/errors]. Are you sure it's a DebugInfo? It should be a google.rpc.Status message.

**Comment by dhermes** [comment]
Thanks @pcostell. Verified

```python
>>> from google.rpc import status_pb2
>>> status_pb2.Status.FromString('\x08\x05\x121The project s~omega-moonlight-697 does not exist.')
code: 5
message: "The project s~omega-moonlight-697 does not exist."
```

**Pull request merged**
