### PR TITLE
Cut 0.14.0 release.

### PR DESCRIPTION
**Pull request by tseaver**
```bash
$ git log -1 --pretty=%H
e38b28e2972aeaf32e788850fd4b930c1f5f4a42
$ git log 0.13.0..HEAD | grep 'Merge pull request ' |  awk -F ' ' '{print $4}' | sort
```
#1690
#1741
#1745
#1746
#1747
#1748
#1750
#1751
#1752
#1753
#1757
#1758
#1759
#1764
#1765
#1769
#1773
#1776
#1779
#1780
#1782
#1785
#1794
#1795
#1798

### CODE REVIEW

**Comment by dhermes** [comment]
LGTM. Release notes to review?

**Comment by tseaver** [comment]
Excluded from release notes:
#1748
#1751
#1752
#1753
#1757
#1758
#1759
#1764
#1769
#1773
#1776
#1779
#1780
#1782
#1785
#1794
#1795
#1798


## Draft Release Notes
-----------------------------

### Core

- Add Travis Build ID to resource names created by system tests. (#1745)

### Search API

- Drop support for the API, as it has never moved from whitelist-only / alpha status, and its future is questionable. (#1741, #1750)

### Monitoring API

- Include `gcloud.monitoring` system tests in the set run by default on Travis. (#1746)
-  Define `__all__` in `gcloud/monitoring/__init__.py`. (#1747)

### Logging API

- Include `gcloud.logging` system tests in the set run by default on Travis. (#1746)

### Pubsub API

- Ensure that example snippets are testable, and fix those which broke. (#1690, #1765)

**Comment by dhermes** [comment]
Release notes LG but I don't think "Add Travis Build ID to resource names created by system tests" is necessary

**Comment by dhermes** [comment]
@tseaver Just noticed #1758 was left out. That's actually a "bug" fix worth noting.

**Comment by dhermes** [comment]
Ditto on #1751, #1752, #1776, #1779, #1785 being user facing

**Comment by tseaver** [comment]
@dhermes I was in the midst of editing them.

I don't know how you normally handle the post-merge release process.  I would probably create a tag, push it to this repo, and then copy the release notes onto the "Releases" tab entry.

**Comment by dhermes** [comment]
Post merge I create a tag via:

```bash
$ git tag 0.14.0
$ git push official 0.14.0  # I believe you call the remote "upstream"
```

and then visit https://github.com/GoogleCloudPlatform/gcloud-python/releases/edit/0.14.0 and manually paste the release notes

**Comment by tseaver** [comment]
I rebased to pick up #1797, and will merge, tag and edit the release once Travis passes.

**Pull request merged**
