### PR TITLE
Adding annotate_text() method in language and helper classes needed for it

### PR DESCRIPTION
**Pull request by dhermes**
This essentially finishes the Cloud Natural Language implementation. System test forthcoming (subsequent PR) and then a few TODO issues need to be resolved.

### CODE REVIEW

**Comment by tseaver** [comment]
ISTM that `token.py` should be called something more general:  `syntax.py`, maybe, or `analysis`?

**Comment by dhermes** [comment]
@tseaver Happy to change it to `syntax.py`. Any other issues with this PR?

**Comment by daspecster** [comment]
I think `token` is actually a natural language [term](http://nlp.stanford.edu/IR-book/html/htmledition/tokenization-1.html), possibly specific to what this is doing?

**Comment by tseaver** [comment]
@dhermes I had no other issues than the module name.

**Comment by dhermes** [comment]
OK. Added a new commit at the end with the rename to `syntax`. Will merge when Travis goes green.

**Pull request merged**
