### PR TITLE
Making iterators accept client instead of connection.

### PR DESCRIPTION
**Pull request by dhermes**
Has #988 as diffbase

### CODE REVIEW

**Comment by tseaver** [comment]
@dhermes ping me after #988 lands (a rebase would help review).

**Comment by dhermes** [comment]
Looks like I've got some work to make it merge, will hold off until #988 is in before re-basing.

**Comment by dhermes** [comment]
@tseaver I rebased.

**Comment by tseaver** [comment]
LGTM

**Pull request merged**
