### PR TITLE
Making custom_pip_install.sh Windows friendly.

### PR DESCRIPTION
**Pull request by dhermes**
Towards #1123.

### CODE REVIEW

**Comment by tseaver** [comment]
Now that pip uses a wheel cache by default, could we find a way to drop the use of `custom_pip_install.sh` altogether, a la https://github.com/travis-ci/travis-ci/issues/1531?

The [Travis caching docs](https://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies/) suggest that the following might work:

```yaml
cache:
  directories:
    - wheel_house
```

**Comment by dhermes** [comment]
I've thought about that a lot :grinning: However, I wanted to vet that this does what our current setup does and don't want to use the cycles and I wrap up some of these other pending things.

I'm not sure what's causing the error, it doesn't fail on my Ubuntu or Windows machines. I think it's the use of `$*` in `./custom_pip_install.sh $*`

**Comment by dhermes** [comment]
@tseaver Bump

**Comment by dhermes** [comment]
Though this black magic is neat, it's much better to just remove the file: #1350

**Pull request closed without merging**
