### PR TITLE
Upgrading version to 0.4.2.

### PR DESCRIPTION
**Pull request by dhermes**
This is for a minor release cycle.

### CODE REVIEW

**Comment by dhermes** [comment]
Running

```bash
$ git log 0.4.1..91167a2bf8c1364e2942127f1a75a2b86bef6704 \
> | grep 'Merge pull request ' \
> | awk -F ' ' '{print $4}' \
> | sort
``

Yields:

#641
#645
#655
#656
#660
#662
#663
#664
#665
#666
#667
#668
#670
#673
#674
#676
#677

**Comment by dhermes** [comment]
This is my plan for the release notes on the tag:

```
-   Adding get_for_service_account_json function to allow JSON
    service accounts without `GOOGLE_APPLICATION_CREDENTIALS`.
-   Adding [support][2] for GCD datastore [dev server][1].
-   Adding `Dataset` class to act as a factory containing a
    preset connection and dataset ID. (Existed several releases
    ago in a different form.)
-   Adding lazy loading support for default dataset ID and
    connection in `datastore` package. This allows auth to be done
    without needing to call `datastore.set_defaults()` provided
    the correct environment variables are set.

[1]: https://cloud.google.com/datastore/docs/tools/devserver
[2]: https://github.com/GoogleCloudPlatform/gcloud-python/pull/656
```

The only other changes are small bugfix (#677), test related (#676) and many for docs spread around.

**Comment by tseaver** [comment]
LGTM

**Comment by dhermes** [comment]
Canceled https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/52167151 so it doesn't conflict with this docs build. (Was for #680). Due to current Travis outage: https://twitter.com/traviscistatus/status/570637064019914752

**Comment by dhermes** [comment]
Tag pushed, release [created][1] and waiting on [Travis][2]

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/releases/tag/0.4.2
[2]: https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/52194492

**Pull request merged**
