### PR TITLE
Removing unused CSS and normalizing indents in docs/conf.py.

### PR DESCRIPTION
**Pull request by dhermes**
@stephenplusplus Can you (or another from `node` side) confirm what `github.min.css` was used for?

### CODE REVIEW

**Comment by dhermes** [comment]
@stephenplusplus or @ryanseys Can you confirm what `github.min.css` was used for? (Our template was forked from yours by @silvolu)

**Comment by ryanseys** [comment]
Looks to me like it was used for syntax highlighting in our docs. I'm assuming it followed the color scheme of GitHub syntax highlighting, hence the name `github.min.css`.  I didn't actually add the file so I'm not sure whether it was ever used / to what extent it was used.

**Comment by ryanseys** [comment]
More context: https://github.com/pc035860/angular-highlightjs/blame/master/README.md#L23

**Comment by stephenplusplus** [comment]
Sorry for letting this one slip off my radar @dhermes. Ryan's right, it sets the theme of the [highlight.js](https://highlightjs.org/) code blocks to match GitHub's color scheme. If you're not using highlightjs in your docs, then it's safe to remove.

**Comment by dhermes** [comment]
No worries. Thanks for the info!

@tseaver WDYT?

**Comment by tseaver** [comment]
LGTM

**Pull request merged**
