### PR TITLE
#1186: Revendor apitools as 'gcloud._apitools'

### PR DESCRIPTION
**Pull request by tseaver**
Towards #1186.

Subsequent work to include:

- From-scratch unit test coverage -> 100%.
- Renamings to match coding standards.
- Full lint compliance.
- Folding in the current `gcloud.storage.batch` implementation.

### CODE REVIEW

**Comment by dhermes** [comment]
I'll try to get to these tonight if I can spare a few minutes. I'm 100% occupied during the day (9am-6pm).

**Comment by tseaver** [comment]
No worries.  This is slog-work, and I've got at least four more hours of it today (coverage for the `gcloud._apitools.transfer` module).  Then cleanups, etc. are likely to keep me busy all week.

**Comment by dhermes** [comment]
"Scrape in six used modules from apitools." brought them in with no changes?

**Comment by dhermes** [comment]
LGTM assuming the answer to my question above is yes

**Comment by tseaver** [comment]
d60a679 really did just copy them in.  The remaining commits are the minimum to get the code usable / used within `gcloud.storage`:

- e4ab851 rewrites imports from `apitools.base.py` -> `gcloud._apitools`.
- d2e4f99 updates `gcloud.storage` to use the forked code.
-  b8b2766 and ad1ab44 turn off coverage / lint on the forked code until we get done with cleanups.

**Pull request merged**
