### PR TITLE
Fix #799: Don't pass 'fields' query param to possibly non-existing subscription.

### LINKED ISSUE #799: Error passing 'fields' to pubsub GET API for subscription
```
$ tox -e regression --notest
GLOB sdist-make: /home/tseaver/projects/agendaless/Google/src/gcloud-python/setup.py
regression inst-nodeps: /home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/dist/gcloud-0.4.3.zip
___________________________________ summary ____________________________________
  regression: skipped tests
  congratulations :)
$ .tox/regression/bin/python regression/run_regression.py --package=pubsub
test_create_subscription (pubsub.TestPubsub) ... ERROR
test_create_topic (pubsub.TestPubsub) ... ok
test_list_subscriptions (pubsub.TestPubsub) ... ok
test_list_topics (pubsub.TestPubsub) ... ok
test_message_pull_mode_e2e (pubsub.TestPubsub) ... ERROR

ERROR: test_create_subscription (pubsub.TestPubsub)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/regression/pubsub.py", line 74, in test_create_subscription
    self.assertFalse(subscription.exists())
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/regression/lib/python2.7/site-packages/gcloud/pubsub/subscription.py", line 112, in exists
    query_params={'fields': 'name'})
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/regression/lib/python2.7/site-packages/gcloud/connection.py", line 293, in api_request
    raise make_exception(response, content)
gcloud.exceptions.BadRequest: 400 Invalid JSON payload received. Unknown name "fields": Cannot bind query parameter.
```

I omitted a similar failure in another test:  both are for a call to `subscription.exists()` where the expected value is False.

@dhermes this is the one I was working around in #794 

@jgeewax maybe tag w/ "google bug"?

### PR DESCRIPTION
**Pull request by tseaver**
Work around #799 (leaving open while @tmatsuo investigates).

(UPDATED by @dhermes when original commit was amended)

### CODE REVIEW

**Comment by dhermes** [comment]
LGTM.

You mind if we leave #799 open (or file a new one) until the issue gets resolved with the service?

**Comment by tseaver** [comment]
@dhermes I don't mind -- payload size is going to be < MTU even if we don't pass it, though.

**Comment by tseaver** [comment]
Amended the commit to avoid closing #799 at merge.

**Comment by dhermes** [comment]
@tseaver Thanks! I also updated the first message to match, as that would have closed it too.

**Pull request merged**
