### PR TITLE
Making sure to limit cluster IDs to 30 chars in system tests.

### PR DESCRIPTION
**Pull request by dhermes**
See, for example: https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/128927443

The ID string was made so that `gcloud-py-{TIME}-{BUILD_ID}` (e.g. `gcloud-py-1462819431-128927443`) was 30 chars. However, one of the test cases appended `-a` to test out creating a different cluster and 32 chars is not allowed for cluster names.

### CODE REVIEW

**Comment by tseaver** [comment]
Seems like we might be truncating the bits of the ID which would provide the most uniqueness (e.g., two Travis builds running simultaneously have the same `time.time()` seconds, and differ only in the last byte of the `TRAVIS_BUILD_ID`.  Perhaps we should have `unique_resource_id` take a `prefix` argument and an optional `max_length`, and work out which bits to trim?

**Comment by dhermes** [comment]
I don't think it's worth the effort. It's essentially impossible to end up with the same timestamp (it's YAGNI).

**Comment by tseaver** [comment]
The version with `TRAVIS_BUILD_ID` in it [truncates `time.time()` to an integer](https://github.com/GoogleCloudPlatform/gcloud-python/blob/f8ddb2a5fbb4a5d2441fca864fbf279df30a44c2/system_tests/system_test_utils.py#L72):  if it is always unique, why do we need the `TRAVIS_BUILD_ID` at all?

**Comment by dhermes** [comment]
> why do we need the `TRAVIS_BUILD_ID` at all?

So we can track down the guilty build if we see un-cleaned up resources in the cloud console.

**Comment by tseaver** [comment]
Won't that usecase be broken if we truncate off bytes from the build ID?

**Comment by dhermes** [comment]
Ha! Touche. Easiest fix: I'll swap the order of BUILD ID and time. Anyhow, as it is there, the ID will be

```python
>>>  len('gcloud-128927443-1462819431')
27
>>> len('new-128927443-1462819431')
24
```

so hopefully nothing will get truncated.

WDYT of just doing the swap?

**Comment by tseaver** [comment]
> WDYT of just doing the swap?

SGTM

**Comment by dhermes** [comment]
@tseaver PTAL

**Comment by tseaver** [comment]
LGTM

**Pull request merged**
