### PR TITLE
Removing factories from base Connection class.

### PR DESCRIPTION
**Pull request by dhermes**
These are no longer needed since the factories are on all clients.

----

Literally 100% red (0 additions). I love it!

### CODE REVIEW

**Comment by jgeewax** [comment]
Sorry, just not sure I follow. Wouldn't we prefer to put the single method on the base class and let the others inherit those methods?

**Comment by dhermes** [comment]
`Connection` used to need these factories because users directly created them. Now that we have `Client`s this is unnecessary and so both the base connection and client class have these factories

> These are no longer needed since the factories are on all clients

**Comment by tseaver** [comment]
Hmm, needs a rebase?

**Comment by dhermes** [comment]
On it.

**Comment by dhermes** [comment]
@tseaver PTAL. Rebased.

**Comment by tseaver** [comment]
LGTM

**Pull request merged**
