### PR TITLE
Removing use of isolation level in datastore.

### PR DESCRIPTION
**Pull request by dhermes**
In `v1beta3` all transactions are serializable.

### CODE REVIEW

**Comment by dhermes** [comment]
Was #1343

**Comment by dhermes** [comment]
@tseaver PTAL

**Comment by tseaver** [comment]
LGTM

**Comment by dhermes** [comment]
@tseaver Any ideas for a good way to manage the `datastore-v1beta3` branch / keep it up to date with `master`? Should I send PRs for the rebases?

**Comment by tseaver** [comment]
I'd say we could just merge master to it before merging it back:  since it is a long-lived integration branch, the extra merge(s) (might be more than one) actually document keeping it up to date.

**Comment by dhermes** [comment]
OK.

**Pull request merged**
