### PR TITLE
#741: hoist `get_scoped_connection` into `connection`

### PR DESCRIPTION
**Pull request by tseaver**
Uses #748 as a base.

Implement `datastore._implicit_environ.get_connection` and `storage.get_connection` in terms of new `connection.get_scoped_connection`.

### CODE REVIEW

**Comment by tseaver** [comment]
@dhermes rebased against master after the merge of #748.

**Comment by dhermes** [comment]
LGTM.

It seems the `[ci skip]` on the last commit is preventing Travis from re-running.

**Comment by tseaver** [comment]
I added a tox-only commit to allow Travis to run.

**Comment by dhermes** [comment]
You could've also `git commit --amend`ed the last commit and then just `git push --force`ed into the PR.

**Comment by tseaver** [comment]
I thought of that about fifteen seconds after pushing the other. ;)

**Pull request merged**
