### PR TITLE
Documentation: Filtering Query by key is also possible.

### PR DESCRIPTION
**Pull request by mgilson**
Update the documentation for `add_filter` to make it clear that filtering by key is also possible.

### CODE REVIEW

**Comment by dhermes** [comment]
LGTM

**Comment by dhermes** [comment]
Thanks @mgilson. In the future, if possible, can you squash your changes into a single commit? I'd be happy to help show you how if the need arises (e.g. here the `lint` error caused you to have to add a newline).

**Comment by mgilson** [comment]
@dhermes Sure.  Sorry about that.  I would have squashed it on this one, but I was doing all of my edits via the github editor and didn't realize the error until travis yelled at me.  I wanted to make sure travis was happy with the second commit before I rebased and force-pushed -- But by the time I got back, you had already merged.

**Comment by dhermes** [comment]
No worries. I didn't want to burden you with having a checkout. I appreciate the quick fix!

**Pull request merged**
