### PR TITLE
Upgrading version to 0.12.1

### PR DESCRIPTION
**Pull request by daspecster**
Starting release notes!

    $ git log -1 --pretty=%H
    355899fb16bbdbc83aea6281e7535e21c70e8319

    $ git log 0.12.0..HEAD \
    > | grep 'Merge pull request ' \
    > | awk -F ' ' '{print $4}' \
    > | sort

#1694
#1697
#1698
#1699
#1706
#1708
#1709
#1716
#1717
#1727
#1728
#1729
#1730

### CODE REVIEW

**Comment by daspecster** [comment]
Changes not noted in release notes:
- Core:  #1697,  #1706, #1708
- DNS:  #1698
- Pub/Sub: #1694
- BigQuery: #1716

Release notes:
---

### Core
- Create a generic iterator wrapping 'list_*' methods of client-side objects (#1699)

### Datastore
- Add /datastore/ in emulator URI path. (#1709)

**Comment by dhermes** [comment]
@daspecster Thanks for the start, here are some suggested changes.

#1699 isn't really user facing yet, so we can leave it out.

````

Datastore
---
- Fix `v1beta2` / `v1beta3` bug with datastore emulator. (#1709)

DNS
---
- Fix outdated usage doc. (#1698)

**Comment by dhermes** [comment]
@daspecster If you go to https://github.com/GoogleCloudPlatform/gcloud-python/releases/new what kind of error message do you see?

/cc @jgeewax May need your help adding him to a group to resolve.

**Comment by daspecster** [comment]
@dhermes actually that link takes me back to github.com.
Also, I updated the release notes with your doc.

**Comment by dhermes** [comment]
OK we can wait on @jgeewax before merging this.

**Comment by daspecster** [comment]
@dhermes Is this good to go now?

**Comment by dhermes** [comment]
There have been some merges since Friday so you should rebase against `master` and re-check the merged PRs. (Thanks for pinging me.)

**Comment by daspecster** [comment]
Ok will do!

**Comment by daspecster** [comment]
@dhermes, I updated the release copy. Let me know what you think!

**Comment by tseaver** [comment]
@daspecster I tweaked the release notes text a bit.

**Comment by daspecster** [comment]
Awesome! Thanks @tseaver!

**Comment by dhermes** [comment]
Go ahead and merge and then create the release.

**Pull request merged**
