### PR TITLE
Adding Bigtable system tests to tox environment (for Py2.7 only).

### PR DESCRIPTION
**Pull request by dhermes**
Second (and third) attempt at #1633

### CODE REVIEW

**Comment by dhermes** [comment]
@tseaver This will still be an issue for your UCS2 build but we need Travis to be running these system tests.

If you need to run the system tests I'd recommend just using service specific (as I [noted][1]).

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/pull/1633#issuecomment-198407244

**Comment by tseaver** [comment]
Travis failure for `system-tests`.

**Comment by dhermes** [comment]
"it'll be easy" are my famous last words.

I forgot that `attempt_system_tests.py` gracefully aborts when not in a merge build on Travis (PRs don't have access to the service account credentials, and for good reason)

Looks like I'll have to make `bigtable` and `bigtable-happybase` conditional inside of `attempt_system_tests.py`.

Fingers crossed that version 3 is a winner.

**Comment by dhermes** [comment]
@tseaver The n-th time is the charm! PTAL

**Comment by tseaver** [comment]
LGTM (I'll let you pull the trigger this time :)

**Comment by dhermes** [comment]
Bombs away!

**Comment by dhermes** [comment]
Woo hoo! It passed: https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/116995631

Bigtable is a go! (for Python 2.7 on non-UCS2 builds, on the list of supported platforms)

**Pull request merged**
