### PR TITLE
Making HappyBase enabled/disabled checks into no-ops.

### LINKED ISSUE #1989: Bigtable HappyBase enable/disable table should be a no-op
Currently methods which aren't available in Bigtable for HappyBase throw an NotImplementedError. https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/gcloud/bigtable/happybase/connection.py#L392

This will make it more difficult to port applications to and from HBase. These operations should be no-ops (possibly logging a warning when run).

### PR DESCRIPTION
**Pull request by dhermes**
Fixes #1989.

/cc @mbrukman @tswast

### CODE REVIEW

**Comment by tseaver** [comment]
LGTM pending Travis.

**Comment by dhermes** [comment]
Thanks @tseaver, assigned @tswast and @mbrukman before the merge

**Comment by mbrukman** [comment]
LGTM

Are there any concerns about non-actionable warning messages, since there's nothing a user can do to remove the warnings, short of not calling the functions? I guess since these actions are administrative rather than data-oriented, they should be called rather rarely, so it shouldn't clog up their logs too much, and they ought to know that they're no-ops, so I think this is fine.

Thanks for making the change!

**Comment by dhermes** [comment]
Fixed the lint breakage and added `compact_table()` as a no-op.

@mbrukman @tseaver PTAL?

**Comment by tseaver** [comment]
LGTM

**Comment by dhermes** [comment]
@mbrukman Implemented your updates to the language.

**Comment by mbrukman** [comment]
LGTM, thanks!

**Pull request merged**
