### PR TITLE
#744: return Topic instances from `pubsub.api.list_topics()`

### PR DESCRIPTION
**Pull request by tseaver**

### CODE REVIEW

**Comment by tseaver** [comment]
@dhermes I have no idea where those extra merge commits are coming from:  only the last two show up in my local checkout when I run `git rebase master`.

**Comment by dhermes** [comment]
@tseaver You have a dirty checkout of `master`. I nuked those commits after our [discussion][1] on #762.

Just destroy your current master branch and create a new tracking branch to track `upstream/master`.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/pull/762#issuecomment-87191044

**Comment by dhermes** [comment]
Mostly looks good, but ping me when the history looks correct.

Also, did you intend to include the `regression` commit here or elsewhere? (FWIW I'm fine with it in here, just wanted to make sure.)

**Comment by tseaver** [comment]
@dhermes history now cleaned.

I did mean to add the regression test here.

**Comment by dhermes** [comment]
LGTM pending Travis.

**Pull request merged**
