### PR TITLE
AppVeyor test commit.

### PR DESCRIPTION
**Pull request by dhermes**
This is not intended to be merged.

Relates to #1124

### CODE REVIEW

**Comment by dhermes** [comment]
An AppVeyor build was created:
https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.1.master

**Comment by dhermes** [comment]
https://bugs.python.org/issue14243

**Comment by dhermes** [comment]
@tseaver After running

```
python setup.py bdist_wheel
```

we [get][1] a `none-any` wheel:

```
ls dist

    Directory: C:\projects\gcloud-python\dist


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---        11/16/2015   5:39 PM     402514 gcloud-0.8.0-py2-none-any.whl
-a---        11/16/2015   5:39 PM     601288 gcloud-0.8.0.win32.exe
-a---        11/16/2015   5:39 PM     737280 gcloud-0.8.0.win32.msi
```

Any idea what needs to be done to have a Windows specific wheel?

----

As far as getting up and running on AppVeyor, I still need to

- [ ] get `tox` working
- [ ] figure out how to upload the MSI/EXE/wheel to an existing version

----

The [`python-appveyor-demo`][2] project was SOOOO helpful here.

[2]: https://github.com/ogrisel/python-appveyor-demo
[1]: https://ci.appveyor.com/project/dhermes/gcloud-python/build/job/tl2jsfg3adyq2jn5

**Comment by tseaver** [comment]
> Any idea what needs to be done to have a Windows specific wheel?

We don't have any C extensions, so a "universal" wheel should work fine on Windows.  See: http://wheel.readthedocs.org/en/latest/#defining-the-python-version .

**Comment by dhermes** [comment]
Ahhh I see. The downstream deps don't matter for making a wheel.

I'm curious if they're bundled in the exe/MSI (that was the purpose of #1009, that the crypto deps were a pain and it would be nice for us to bundle them).

Seems I'll end up tackling #1123 as well in tackling #1124 (funny how the numbering worked out that way).

**Comment by dhermes** [comment]
@tseaver A few notes here.

Getting `tox` to work is going to be difficult since every command in AppVeyor needs to be run in a [special environment][9]. This would mean over-riding `install_command` in `tox.ini`, but we wouldn't want to do that on all Windows machines, just the AppVeyor ones.

I just [took the easy way out][10] and used

```
%CMD_IN_ENV% python setup.py nosetests
```

to run the tests.

----

The script [builds][11] `bdist_wininst` and `bdist_msi` but they aren't clearly labeled by version (see below). I'm curious if we should upload one of these for all 8 possible environments (32- or 64-bit and then 4 Python versions 2.6, 2.7, 3.3 and 3.4) and if the actually files are different from version to version.

-   [Python 2.6.6 32 bit][2]

    ```
    gcloud-0.8.0.win32-py2.6.msi
    gcloud-0.8.0.win32.exe
    ```

-   [Python 2.6.6 64 bit][3]

    ```
    gcloud-0.8.0.win-amd64-py2.6.msi
    gcloud-0.8.0.win-amd64.exe
    ```

-   [Python 2.7.10 32 bit][4]

    ```
    gcloud-0.8.0.win32.exe
    gcloud-0.8.0.win32.msi
    ```

-   [Python 2.7.10 64 bit][5]

    ```
    gcloud-0.8.0.win-amd64.exe
    gcloud-0.8.0.win-amd64.msi
    ```

-   [Python 3.3.5 32 bit][6]

    ```
    gcloud-0.8.0.win32.exe
    gcloud-0.8.0.win32.msi
    ```

-   [Python 3.3.5 64 bit][1]

    ```
    gcloud-0.8.0.win-amd64.exe
    gcloud-0.8.0.win-amd64.msi
    ```
-   [Python 3.4.3 32 bit][7]

    ```
    gcloud-0.8.0.win32.exe
    gcloud-0.8.0.win32.msi
    ```

-   [Python 3.4.3 64 bit][8]

    ```
    gcloud-0.8.0.win-amd64.exe
    gcloud-0.8.0.win-amd64.msi
    ```


[1]: https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.37.master/job/marm3ld60egwe5kh
[2]: https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.37.master/job/bibvl2h2qd3f36xs
[3]: https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.37.master/job/wwoy18jtu6dcf4pg
[4]: https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.37.master/job/k1q0k2527f16d9fg
[5]: https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.37.master/job/76iv16pjvpslkjwt
[6]: https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.37.master/job/4fkcfab19acc474y
[7]: https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.37.master/job/f8h5avbwwdiej2ok
[8]: https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.37.master/job/xbm20dnd7y7wquai
[9]: https://github.com/ogrisel/python-appveyor-demo/blob/2ba010b6542883b0c0e463a9d50e16d4161cc6f9/appveyor.yml#L108
[10]: https://github.com/dhermes/gcloud-python/blob/aff1bf6e134baeebb776d2f38166d58e8e13aaea/appveyor.yml#L100
[11]: https://github.com/dhermes/gcloud-python/blob/aff1bf6e134baeebb776d2f38166d58e8e13aaea/appveyor.yml#L105-L106

**Comment by dhermes** [comment]
@tseaver We don't actually need to get uploads (e.g. via `twine`) working if we don't wish to.

AppVeyor gives direct access to the artifacts for a build:
https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.38.master/job/q3tgnrskftxxdi6d/artifacts
so we could just download them and upload by hand to PyPI (though it [appears][1] uploading to PyPI on AppVeyor may be a solved problem)

[1]: http://kirbyfan64.github.io/posts/using-appveyor-to-distribute-python-wheels.html

**Comment by tseaver** [comment]
Unless we figure out how to get those artifacts built correctly (with appropriate names), uploading them to PyPI is kind of moot.

**Comment by dhermes** [comment]
I was curious if you knew what a "correct" name was. They were produced directly by `setuptools`, so maybe that is what they are supposed to look like? Right now I'm scouring other projects to see if they have any MSIs (none on `numpy`, for example).

**Comment by tseaver** [comment]
https://pypi.python.org/pypi/zope.interface/4.1.3 has separate installer EXEs for each supported Python.

**Comment by dhermes** [comment]
Awesome resource, thanks! Do you know how they are created? Maybe someone manually changes the filename?

**Comment by dhermes** [comment]
From https://docs.python.org/2/distutils/builtdist.html

> If you have a pure module distribution (only containing pure Python modules and packages), the resulting installer will be version independent and have a name like `foo-1.0.win32.exe`. These installers can even be created on Unix platforms or Mac OS X.
>
> If you have a non-pure distribution, the extensions can only be created on a Windows platform, and will be Python version dependent. The installer filename will reflect this and now has the form `foo-1.0.win32-py2.0.exe`. You have to create a separate installer for every Python version you want to support.

-----

This worries me that the dependencies (e.g. `pycrypto`, the annoying one) aren't bundled up in the `msi` file. I was hoping for a magic pill.

**Comment by tseaver** [comment]
I'm positive that dependencies aren't bundled:  we'd have to vendor them in.

**Comment by dhermes** [comment]
RE:

> I'm positive that dependencies aren't bundled: we'd have to vendor them in.

I have (hopefully) addressed in #1338. Will close this PR and open a more polished version once #1338 is in.

**Pull request closed without merging**
