### PR TITLE
Sync mtime with updated time

### PR DESCRIPTION
**Pull request by grapefruit623**
For issue #311 
storage.key.get_contents_to_filename will sync file's mtime and metadata's updated time

### CODE REVIEW

**Comment by grapefruit623** [comment]
I changed my git commit to one commit so it look like clear.
By the way I have sign the CLA

**Comment by tseaver** [comment]
Thanks, LGTM.  @silvolu, can you please confirm the CLA?

**Comment by silvolu** [comment]
CLA signed.

**Comment by dhermes** [comment]
We are good to merge this?

**Pull request merged**
