### PR TITLE
Adding BigQuery and Pub/Sub to README.

### LINKED ISSUE #1076: README.rst page doesn't mention the pub/sub client or bq
The project home page provides examples of some of the API features like datastore, but doesn't list them all. This leads to an initial impression that the library doesn't support pub/sub or bq when it does. It's not obvious until you dive into the documentation.

### PR DESCRIPTION
**Pull request by dhermes**
Fixes #1076.

See it staged at https://github.com/dhermes/gcloud-python/blob/fix-1076/README.rst

### CODE REVIEW

**Comment by dhermes** [comment]
Notice I also changed the relative `#google-cloud-storage` links to absolute ones. This is because they don't get rendered on https://pypi.python.org/pypi/gcloud when they are relative (and having relative "CONTRIBUTING" actually complete broke the PyPI RST parser before).

Maybe we should add something to our CONTRIBUTING doc warning about using non-absolute links in the README?

**Comment by tseaver** [comment]
LGTM.

A note in `CONTRIBUTING.rst` might help, if only there were impetus to read it. :)

**Comment by dhermes** [comment]
You don't think the doc is worthwhile?

**Comment by tseaver** [comment]
I just meant that you and I are the ones most likely to forget, and least likely of all to look at `CONTRIBUTING.rst`.  Go ahead and add the note.

**Comment by dhermes** [comment]
Ah gotcher.

**Pull request merged**
