### PR TITLE
Drop ':undoc-members:' from Sphinx API docs

### LINKED ISSUE #1800: Stop using undoc-members
See https://github.com/GoogleCloudPlatform/gcloud-python/pull/1772/files#r63362850

### PR DESCRIPTION
**Pull request by tseaver**
Set explicit pylint pattern for `no-docstring-rgx`.  Leaving it unset disabled the `missing-docstring` check.

Add missing docstrings uncovered thereby.

Closes #1800.

### CODE REVIEW

**Comment by dhermes** [comment]
So instead of having `tox -e docs` fail this causes `tox -e lint` to fail?

**Comment by tseaver** [comment]
Yup.  `tox -e docs` doesn't do a member-by-member check.

**Comment by dhermes** [comment]
The other check I was having a hard time remembering is also from PyLint: https://github.com/GoogleCloudPlatform/gcloud-python/blob/763a90c2b435cf9242533c188053e9533046f4f3/scripts/pylintrc_default#L41

It is the `check_docs` extension (it checks args match and similar).

**Comment by dhermes** [comment]
LGTM

**Pull request merged**
