### PR TITLE
Making regression test put()'s transactional.

### PR DESCRIPTION
**Pull request by dhermes**
This is to address flaky test failures.

See #535 for more discussion.

### CODE REVIEW

**Comment by tseaver** [comment]
LGTM

**Comment by dhermes** [comment]
The second time regression tests were run after this PR, the flake still occurred:
https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/47970589

```
======================================================================
FAIL: test_save_key_self_reference (datastore.TestDatastoreSaveKeys)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/regression/datastore.py", line 158, in test_save_key_self_reference
    self.assertEqual(len(stored_persons), 1)
AssertionError: 0 != 1
```

The code at question is

```python
        with datastore.Transaction():
            datastore.put([entity])

        query = datastore.Query(kind='Person')
        query.add_filter('linkedTo', '=', key)

        stored_persons = list(query.fetch(limit=2))
        self.assertEqual(len(stored_persons), 1)
```

@pcostell does the query also need to occur transactionally to make sure this passes always?

**Comment by pcostell** [comment]
This doesn't actually do anything (a single put by itself is transactional). 

To make sure these tests always pass you need to make the entity have a parent then make the query do an ancestor query.

**Comment by dhermes** [comment]
Thanks. Sorry for the n00b question. I've been told that before, totally should not have forgotten.

**Comment by pcostell** [comment]
No worries, it's easy to mix up.

**Pull request merged**
