### PR TITLE
Remove old/unused Bigtable v1 generated code

### PR DESCRIPTION
**Pull request by dhermes**
@tseaver there are a lot of import aliases leftover like:

```python
from gcloud.bigtable._generated import (
    bigtable_instance_admin_pb2 as instance_admin_v2_pb2)
```

Is it worth me tracking them down?

### CODE REVIEW

**Comment by tseaver** [comment]
This PR would be a lot easier to read if broken up:  e.g., first remove all the `_generate/*.py` modules in one PR (so that we could see that there was no breakage / overlap), and then rename `_generated_v2` -> `_generated` in a subsequent PR:  at that point, maybe ditching the aliases would be worthwhile.

**Comment by dhermes** [comment]
@tseaver It's broken up into 3 commits to accomplish essentially the same thing (but a little differently):

1. Remove all v1 code
1. Remove all v2 references in text files
1. Rename all v2 files

**Comment by dhermes** [comment]
@tseaver PTAL

**Comment by tseaver** [comment]
@dhermes Your second commit couldn't possibly pass tests:  the rename of the files has to go hand-in-hand with the updated imports. Could you squash it with the third commit?

**Comment by dhermes** [comment]
The failure was due to a newly introduced (hence not renamed) import from #2002.

I made the commits as a group, not trying to get tests to pass in between. I avoided doing the import renames in the same commit as the file renames to make the diff easier to read. Having a "file rename only" commit makes the commit easier to grok.

**Comment by tseaver** [comment]
OK, LGTM.  Looking forward to the day that we can rip this junk out, and just use the `grpc-google-{datastore,bigtable}-v#` libraries instead.

**Pull request merged**
