### PR TITLE
Upgrading version to 0.6.0.

### PR DESCRIPTION
**Pull request by dhermes**
Using last release PR (#813) as a template.

### CODE REVIEW

**Comment by dhermes** [comment]
Running

```bash
$ git log -1 --pretty=%H
d8bd10bb045ec1d24b854bacf16bcee7a1135185
$ git log 0.5.0..HEAD \
> | grep 'Merge pull request ' \
> | awk -F ' ' '{print $4}' \
> | sort
```

yields

#809
#810
#812
#814
#816
#820
#822
#823
#824
#826
#834
#835
#840
#842
#843
#844
#849
#852
#853
#854
#855
#856
#857
#859
#862
#863
#864
#873
#875
#876
#877
#878
#879
#880
#881
#882
#888
#891
#894
#897
#898
#901
#904

**Comment by tseaver** [comment]
Given that there are a couple of new features, as well as some backward-incompatible changes, I think this release needs to be `0.6`, rather than `0.5.1`.

**Comment by dhermes** [comment]
This is my plan for the release notes on the tag:

```
### General
-   Adding `from_service_account_json`, `from_service_account_p12`
    and `from_environment` factories to `Connection` base class.
    This allows creating a connection without first creating a
    set of credentials.

### Datastore
-   Fixing serious bug where the transaction ID was not passed
    along to transactions, effectively making a transaction act as
    a batch.
-   Adding scope to un-scoped credentials passed to connection
    constructor.
-   Enabling connection as an optional argument to all methods
    and functions which use a connection.
-   Requiring `exclude_from_indexes` to be a tuple or list in
    `Entity` constructor.
-   Requiring `projection`, `order` and `group_by` to be a
    tuple or list in `Query` constructor.
-   Re-purposing `datastore.get` to take a single key and moving
    previous functionality to `datastore.get_multi`. Similar
    changes were made for

    ```
    datastore.put --> datastore.put_multi
    ```

    and

    ```
    datastore.delete --> datastore.delete_multi
    ```

### Storage
-   Adding futures in to allow GET/PATCH to
    work correctly in a batch.
-   Remove default chunk size in upload/download.
-   Adding lazy loaded default connection and project.
-   Decoupling connection property from `Blob`/`ACL`/`Bucket`
    classes.
-   Enabling connection as an optional argument to all methods
    and functions which use a connection.
-   Adding scope to un-scoped credentials passed to connection
    constructor.
-   Updating public blob URL to use `storage.googleapis.com`.
-   Remove `Bucket.__iter__` and `Bucket.__contains__`.
-   Limiting `Bucket.make_public(recursive=True)` to cowardly refuse
    if more than 256 objects are in the bucket. This is similar to
    what is done in `Bucket.delete(force=True)`.

### Pub/Sub
-   Auto-adding timestamp to messages.
-   Adding an optional message timestamp so that
    messages can be sorted.
-   Adding scope to un-scoped credentials passed to connection
    constructor.
-   Enabling connection as an optional argument to all methods
    and functions which use a connection.
-   Fixing bug in `Subscription.pull` for cases when `receivedMessages`
    is not returned.
```

----

@tseaver Please give this some extra scrutiny, I'm a bit unsure of some parts.

**Comment by dhermes** [comment]
@tseaver I upgraded to `0.6.0` but didn't change the branch name, so that we didn't have to open a new PR.

**Comment by tseaver** [comment]
I think I would normalize the changelog into imperative mode.  E.g.:

### General
- Update required version of `protobuf` to `3.0.0-alpha-1`.
- Add `from_service_account_json`, `from_service_account_p12` and `from_environment` factories to `Connection` base class, allowing creation of a connection without first creating a set of credentials.

### Datastore
-   Fix serious bug where the transaction ID was not passed along to transactions, effectively making a transaction act as a batch.
-   Add appropriate scope to un-scoped credentials passed to connection constructor.
-   Enable `connection` as an optional argument to all methods and functions which use a connection.
-   Require `exclude_from_indexes` to be a tuple or list in `Entity` constructor.
-   Require `projection`, `order` and `group_by` to be a tuple or list in `Query` constructor.
-   Re-purpose `datastore.get` to take a single key;  move previous functionality to `datastore.get_multi`. Similar
    changes were made for

    ```
    datastore.put --> datastore.put_multi
    ```

    and

    ```
    datastore.delete --> datastore.delete_multi
    ```

### Storage
-   Add support for "futures", to allow GET/PATCH to work correctly in a batch.
-   Remove default chunk size in upload/download.
-   Add lazily-loaded default connection and project.
-   Remove connection property from `Blob`/`ACL`/`Bucket` classes.
-   Enable `connection` as an optional argument to all methods and functions which use a connection.
-   Add appropriate scope to un-scoped credentials passed to connection constructor.
-   Update public blob URL to use `storage.googleapis.com`.
-   Remove `Bucket.__iter__` and `Bucket.__contains__`.
-   Limit `Bucket.make_public(recursive=True)` to abort if more than 256 objects are in the bucket. This is similar to what is done in `Bucket.delete(force=True)`.

### Pub/Sub
-   Add an option to auto-add a timestamp to published, messages, allowing them to be sorted / logged.
-   Add appropriate scope to un-scoped credentials passed to connection constructor.
-   Enable `connection` as an optional argument to all methods and functions which use a connection.
-   Fix a bug in `Subscription.pull` for cases when `receivedMessages` is not returned.

**Comment by dhermes** [comment]
Cool. Are we all good to merge then?

FWIW I didn't include "Update required version of protobuf to 3.0.0-alpha-1." because that isn't a feature to users. But am happy to include if you think it is important.

**Comment by tseaver** [comment]
LGTM.  I figured we should expose the dependency pin because it might affect how existing users upgrade (or even whether they could).

**Comment by dhermes** [comment]
Release created https://github.com/GoogleCloudPlatform/gcloud-python/releases/tag/0.6.0

**Comment by jgeewax** [comment]
Awesome!

**Pull request merged**
