### PR TITLE
Upgrading Bigtable to gRPC 0.13.0.

### PR DESCRIPTION
**Pull request by dhermes**

### CODE REVIEW

**Comment by vinays** [comment]
@dhermes  Awesome! This is going to make deployments so much easier. Thanks!

**Comment by dhermes** [comment]
Great to hear! I didn't realize people were using this already :grinning:

**Comment by vinays** [comment]
Not in production yet, but in a small cluster in GCP. :)

**Comment by jonparrott** [comment]
I love anything that can remove this much code.

This LGTM. Do you need to squash first?

**Comment by dhermes** [comment]
Nope I intentionally made 3 commits to show each change as distinct.

**Pull request merged**
