### PR TITLE
Modify gcloud-java logo to be white svg

### PR DESCRIPTION
**Pull request by ajkannan**

### CODE REVIEW

**Comment by jgeewax** [comment]
Screenshot?

**Comment by dhermes** [comment]
LGTM. I'll wait for JJ to sign off on the screenshot.

**Comment by ajkannan** [comment]
Here's a demo: http://ajkannan.github.io/gcloud-python/

**Comment by dhermes** [comment]
screen_shot_004

**Comment by jgeewax** [comment]
LGTM

**Pull request merged**
