### PR TITLE
added optional content_type to bucket.upload_file

### PR DESCRIPTION
**Pull request by justicesuh**

### CODE REVIEW

**Comment by justicesuh** [comment]
I signed it!

**Comment by dhermes** [comment]
Looks fine. Any reason why you don't just use the `Blob.upload_*` methods?

**Comment by justicesuh** [comment]
not particularly, either works

**Comment by dhermes** [comment]
I think we've even debated making `Bucket.upload_file` a protected method to just encourage people to use the `Blob` directly.

----

Can you address the test failure:

```
TypeError: upload_from_filename() got an unexpected keyword argument 'content_type'
```

**Comment by justicesuh** [comment]
hm.. the test passes for me
I'll look into it tomorrow

**Comment by dhermes** [comment]
Thanks. You are running the tests locally via `tox`, yes?

**Comment by justicesuh** [comment]
yes, I am also using the code in production

**Comment by dhermes** [comment]
Notice it's a test fixture `_Blob` which encounters `an unexpected keyword argument 'content_type'`: https://github.com/GoogleCloudPlatform/gcloud-python/blob/9c4867ab3a26b6f5e19f85c5d66e3c9083a8d83f/gcloud/storage/test_bucket.py#L525-L533

**Pull request closed without merging**
