### PR TITLE
Add Logging Handler

### PR DESCRIPTION
**Pull request by waprin**
New PR for #1497 , replaces #1881 .

### CODE REVIEW

**Comment by daspecster** [comment]
@waprin cool! We can close #1881 now then?

**Comment by waprin** [comment]
I don't think so because I think there's a lot we need to add:

- handler for fluentd logging agent
- at least one async transport that batches calls, a background thread worker
- possibly a bit more for good integration with flask/django logging

**Comment by waprin** [comment]
This PR is for a feature branch anyway so would be good to merge if its LGTM (got reviewed in #1881)

**Comment by tseaver** [comment]
@waprin I closed #1881, which was identical to this PR except for the target branch.  We can continue to work out the remaining features you have planned on the `stdlib-handler-feature` branch, and then merge it all at one go when ready.

**Comment by waprin** [comment]
Yes I was suggesting we merge this PR, since it would be a merge into this feature branch. That way I can get reviews on smaller PRs. But if you'd prefer I just keep pushing commits here, also fine.

**Comment by waprin** [comment]
cc @sharbison3

**Comment by tseaver** [comment]
@waprin Thanks for the work!  I'd say create new PRs for the other feature work you have outlined.

**Pull request merged**
