### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by davidraleigh**
Returns ```None```:
```python
blob = bucket.get_blob('/remote/path/to/file.txt')
```

Returns blob:
```python
blob = bucket.get_blob('remote/path/to/file.txt')
```

### CODE REVIEW

**Comment by tseaver** [comment]
LGTM.

@jgeewax this is certainly not an issue where copyright assignment would matter:  do we need to wait for CLA to be happy before merging?

**Comment by davidraleigh** [comment]
I signed it!

**Comment by tseaver** [comment]
Thank you for the patch!

**Comment by jgeewax** [comment]
@dhermes : In general, the safe bet is to get a CLA signed on everything. I agree it seems silly to require  this for things like typo fixes, but it's still important.

**Pull request merged**
