### PR TITLE
Switching datastore cursors to URLsafe base64 encoding.

### PR DESCRIPTION
**Pull request by jonparrott**
Fixes [getting-started-python#8](https://github.com/GoogleCloudPlatform/getting-started-python/issues/8)

### CODE REVIEW

**Comment by tseaver** [comment]
Given that our code only sends the cursor as a member of a protobuf passed as the body of a `POST` request (with `Content-Type: application/x-protobuf`), I don't know why the `urlsafe_` encoding variants should matter:  the cursor never appears as an item in a URL path or query string, nor even in a body encoded via `www-form-urlencoded`/`multipart-formdata`.  Do we know whether the back-end uses the `urlsafe_` variant to encode the cursor?

@jonparrott Were you able to reproduce https://github.com/GoogleCloudPlatform/getting-started-python/issues/8 before this patch, and then have it not fail with the patch?

**Comment by dhermes** [comment]
> I don't know why the `urlsafe_` encoding variants should matter

For users creating URLs to page through search results with the cursors

----

> Do we know whether the back-end uses the `urlsafe_` variant to encode the cursor?

The backend uses bytes. The only reason we encode bytes as base64 is for our end-users and we decode it when bringing it back in to a protobuf (e.g. if the user gets a base64 encoded cursor from a `next_page()` and then they use that as an end cursor).

**Comment by jonparrott** [comment]
Inside of `gcloud-python`, the cursor is never passed around in a URL or query string, but in user applications it's a common pattern:

```python
def list():
    cursor = request.params.get('cursor', None)
    query = ds.query(kind='Book', order=['title'])
    it = query.fetch(limit=limit, start_cursor=cursor)
    entities, more_results, cursor = it.next_page()
    return "Next page: {}".format(url_for('list', cursor=cursor))
```
(abridged)

Returns something like:

```
/list?cursor=CkUKEwoFdGl0bGUSChoIdGhlb2RvcmUSKmoVc35iaWd0YWJsZS1zZmFuLXRlc3QxchELEgRCb29rGICAgIC+goMKDBgAIAA=
```

which fails due to the `+` present.

**Comment by jonparrott** [comment]
Thanks, @tseaver. I'll be on the lookout for the next release so I can update getting-started-python.

**Pull request merged**
