### PR TITLE
Combining get_all_blobs and Bucket.iterator.

### PR DESCRIPTION
**Pull request by dhermes**
Also adding page_token, projection and fields as arguments to the newly creating function (list_blobs).

This is "proposed" in #761. If there are issues we don't have to move forward with it.

### CODE REVIEW

**Comment by dhermes** [comment]
@tseaver PTAL

**Comment by tseaver** [comment]
LGTM.  My only reservation is that `list_blobs` returns an iterator, rather than a list;  probably just a nit.

**Comment by dhermes** [comment]
I tried to keep the functionality mostly the same. In general, an iterator is the way to go because `_BlobIterator` could make a **lot** of requests before finishing.

**Comment by tseaver** [comment]
It was really the name, `list_blobs`, that gave me pause (not the returning an iterator part).

**Comment by dhermes** [comment]
Gotcher. Mapping to the name `storage.objects.list` (eek `objects != blobs`).

**Pull request merged**
