### PR TITLE
Upgrading version to 0.4.3.

### PR DESCRIPTION
**Pull request by dhermes**
@tseaver This is just in preparation for cutting a release tomorrow.

I am just going to start writing the release notes and hopefully we can get most of the pending PRs merged before we cut `0.4.3`.

----

Using last release PR (#678) as a template.

### CODE REVIEW

**Comment by dhermes** [comment]
With `HEAD` the current `HEAD` in this PR:

```bash
$ git log 0.4.2..HEAD \
> | grep 'Merge pull request ' \
> | awk -F ' ' '{print $4}' \
> | sort
```

yields:

#654
#672
#682
#683
#689
#693
#694
#695
#698
#699
#700
#713
#715
#716
#718

**Comment by dhermes** [comment]
This is my plan for the release notes on the tag:

**Comment by dhermes** [comment]
@tseaver I'm heading to the airport. WDYT about cutting this release today? I just updated the notes after all the merges this morning (afternoon for you).

**Comment by tseaver** [comment]
LGTM for a 0.4.3 release.

**Pull request merged**
