### PR TITLE
Ditch Connection.new_bucket method in storage

### PR DESCRIPTION
**Pull request by dhermes**
This was seldom being used and didn't actually create a new bucket.

~~**NOTE**: Has #581 as a diffbase. (NOW MERGED).~~

### CODE REVIEW

**Comment by dhermes** [comment]
@tseaver The one place where the use of `new_bucket` was "needed" was in `delete_bucket`.

So now instead of

```python
bucket_path = self.new_bucket(bucket_name).path
```

I re-use the code snippet from the `Bucket.path` property:

```python
bucket_path = '/b/' + bucket_name
```

WYDT about putting path helpers in `_helpers`? (Similar are needed for objects.)

**Comment by tseaver** [comment]
Maybe make the "path generation" bit a `@classmethod` on `Bucket`?  It seems pretty closely tied to the responsibilities of that class.

**Comment by dhermes** [comment]
@tseaver I added a static method `Bucket.path_helper`. PTAL

**Comment by tseaver** [comment]
LGTM

**Pull request merged**
