### PR TITLE
Making datastore client inherit from base client

### PR DESCRIPTION
**Pull request by dhermes**
**NOTE**: This has #953 as a diffbase.

@tseaver This will likely conflict with #944, it's really more of an "ideas" PR.

### CODE REVIEW

**Comment by dhermes** [comment]
@tseaver PTAL. I re-created this PR after you finished migrating `datastore` to the client pattern.

**Comment by tseaver** [comment]
Crap, I was just working on this one. :(

**Comment by dhermes** [comment]
What to do? Did you forget this PR existed?

**Comment by tseaver** [comment]
I think I prefer #1004:  I was able to simplify some of the testing interactions w/ the mocked connection, and reduce coupling between 'test_client' and 'test_connection'.

**Comment by tseaver** [comment]
I didn't realize you were refreshing it. :(

**Comment by dhermes** [comment]
Closing. Bowing out to #1004

**Comment by tseaver** [comment]
Sorry about that.  I should've checked with you in Hangouts first.

**Comment by dhermes** [comment]
No worries.

**Pull request closed without merging**
