### PR TITLE
Appveyor: this-time-for-sure-rocky

### PR DESCRIPTION
**Pull request by tseaver**
Install GAX-related wrappers via pip to work around #1972.

### CODE REVIEW

**Comment by tseaver** [comment]
@daspecster I'm thinking to cancel the Travis build and just merge in order to poke Appveyor:

 https://ci.appveyor.com/project/dhermes/gcloud-python/

**Comment by tseaver** [comment]
https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.487.master

**Comment by tseaver** [comment]
@daspecster woohoo!  We have a [real test failure](https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.487.master/job/n6ghhbo3him42y6b) (rather than a build failure) on Appveyor:

```python
======================================================================
FAIL: test_read_from_cli_info (gcloud.test__helpers.Test__get_default_service_project_id)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\gcloud-python\gcloud\test__helpers.py", line 223, in test_read_from_cli_info
    self.assertEqual('test-project-id', project_id)
AssertionError: 'test-project-id' != None
```

**Comment by daspecster** [comment]
yay! This looks familiar too!

**Comment by tseaver** [comment]
@daspecster do we have an issue open for that?

**Comment by daspecster** [comment]
Nope, but there is now!

**Pull request merged**
